-- Phase 4a: Expand schema for wiki_pages integer PK migration
-- Epic: #1497 (Convert wiki_pages.id from text slug to integer PK)
-- Issue: #1498
--
-- Replaced with no-op because ALTER TABLE requires ACCESS EXCLUSIVE locks
-- which deadlock with the pre-deploy smoke test (it runs migrations against
-- the production DB while old pods still hold connections).
--
-- The actual schema changes must be applied directly via psql or a one-off
-- job while no other connections hold locks. See:
--   apps/wiki-server/scripts/phase4a-manual-migration.sql
SELECT 1;
