-- Phase D2a: Stop writing page_id_old in citation_quotes and resource_citations.
-- This is a no-op Drizzle migration. The actual DDL is in:
--   scripts/phase-d2a-citations-predeploy.sql
--
-- Changes applied by the manual script:
-- 1. citation_quotes.page_id_old: DROP NOT NULL
-- 2. citation_quotes: CREATE UNIQUE INDEX (page_id_int, footnote) — replaces (page_id_old, footnote) for ON CONFLICT
-- 3. resource_citations: PK migrated from (resource_id, page_id_old) to (resource_id, page_id_int)
-- 4. resource_citations.page_id_old: DROP NOT NULL
-- 5. resource_citations.page_id_int: SET NOT NULL
--
-- See Discussion #1497 Phase D2a for context.
SELECT 1;
