-- QUA-64: auto-suggest source URL candidates for unverifiable verdicts.
--
-- Stores 1-3 candidate URLs generated by web search when the sourcing verdict
-- is `unverifiable`. Composite identity matches the sourcing verdicts table.

CREATE TABLE IF NOT EXISTS "sourcing_url_suggestions" (
  "id" bigserial PRIMARY KEY,
  "record_type" text NOT NULL,
  "record_id" text NOT NULL,
  "field_name" text,
  "entity_id" text,
  "suggested_url" text NOT NULL,
  "title" text,
  "snippet" text,
  "relevance_score" real,
  "source_provider" text NOT NULL,
  "generator_model" text,
  "status" text NOT NULL DEFAULT 'pending',
  "reviewed_at" timestamptz,
  "reviewed_by" text,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_sus_record"
  ON "sourcing_url_suggestions" ("record_type", "record_id");
CREATE INDEX IF NOT EXISTS "idx_sus_entity"
  ON "sourcing_url_suggestions" ("entity_id");
CREATE INDEX IF NOT EXISTS "idx_sus_status"
  ON "sourcing_url_suggestions" ("status");
CREATE INDEX IF NOT EXISTS "idx_sus_created"
  ON "sourcing_url_suggestions" ("created_at");

-- Unique per (record, field, url). COALESCE collapses NULL field_name to '' so
-- row-level suggestions dedup against themselves.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_sus_record_field_url"
  ON "sourcing_url_suggestions" (
    "record_type",
    "record_id",
    COALESCE("field_name", ''),
    "suggested_url"
  );

-- CHECK constraint mirrors the TypeScript status enum.
DO $$ BEGIN
  ALTER TABLE "sourcing_url_suggestions"
    ADD CONSTRAINT chk_sus_status
    CHECK (status IN ('pending', 'approved', 'rejected', 'auto_verified'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
