-- APPLY the bad-Exa cleanup: clear source-URL columns for suspect ids.
-- First failure: [556/892]
-- Scrollback covered: [556..602]
-- Generated by: dev/exa-failure-build-clear-sql.mjs
--
-- Pre-flight: run dev/exa-failure-preview.sql FIRST and confirm
-- the numbers look right. Only then run this file.
--
-- Run with: psql_prod -f dev/exa-failure-clear-source-urls.sql
--
-- Safety: each table block does:
--   1. count rows that match (id ∈ suspects AND col IS NOT NULL)
--   2. RAISE EXCEPTION if the count exceeds the suspect-cap (impossible
--      under normal conditions; would mean a SQL injection / typo)
--   3. UPDATE ... = NULL with the same WHERE clause, RETURNING the ids
--   4. RAISE NOTICE with the actual updated count
-- If any RAISE EXCEPTION fires, the entire transaction rolls back.

BEGIN;

-- ===== page_citations (cap: 47 ids, column: url) =====
DO $$
DECLARE
  to_clear int;
  cleared  int;
BEGIN
  SELECT count(*) INTO to_clear
  FROM page_citations
  WHERE id IN (2738, 2739, 2740, 2741, 2750, 2751, 2752, 2753, 2769, 2951, 3219, 3229, 3308, 3370, 3382, 3385, 3386, 3391, 3392, 3393, 3441, 3442, 3444, 3445, 3449, 3450, 3452, 3453, 3454, 3461, 3465, 3469, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3713, 3714, 3715, 3717, 3806, 3900, 5018, 5019) AND url IS NOT NULL;

  IF to_clear > 47 THEN
    RAISE EXCEPTION 'safety check: page_citations matched % rows but cap is 47 — aborting', to_clear;
  END IF;

  RAISE NOTICE 'page_citations: % rows will be cleared (cap 47)', to_clear;

  UPDATE page_citations
  SET url = NULL
  WHERE id IN (2738, 2739, 2740, 2741, 2750, 2751, 2752, 2753, 2769, 2951, 3219, 3229, 3308, 3370, 3382, 3385, 3386, 3391, 3392, 3393, 3441, 3442, 3444, 3445, 3449, 3450, 3452, 3453, 3454, 3461, 3465, 3469, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3713, 3714, 3715, 3717, 3806, 3900, 5018, 5019)
    AND url IS NOT NULL;

  GET DIAGNOSTICS cleared = ROW_COUNT;
  RAISE NOTICE 'page_citations: cleared % rows', cleared;

  IF cleared <> to_clear THEN
    RAISE EXCEPTION 'safety check: planned % rows but UPDATE wrote % — aborting', to_clear, cleared;
  END IF;
END $$;

-- All sanity checks passed. Commit.
COMMIT;
