-- Preview the bad-Exa cleanup. READ-ONLY. No writes.
-- First failure: [556/892]
-- Scrollback covered: [556..602]
-- Generated by: dev/exa-failure-build-clear-sql.mjs
--
-- Run with: psql_prod -f dev/exa-failure-preview.sql
--
-- For each suspect table this prints:
--   suspect_count   = how many ids we plan to clear (the cap)
--   rows_with_url   = how many of those currently have the URL set
--                     (this is what the UPDATE will hit)
--   rows_null       = how many are already NULL (UPDATE will skip these)
--
-- Sanity rule: rows_with_url + rows_null must equal suspect_count.
-- If not, some ids do not exist in the table → investigate before applying.

-- ===== page_citations (47 suspect ids, column: url) =====
SELECT 'page_citations'::text AS tbl,
       47::int AS suspect_count,
       count(*) FILTER (WHERE url IS NOT NULL) AS rows_with_url,
       count(*) FILTER (WHERE url IS NULL)     AS rows_null,
       count(*)                                    AS rows_found
FROM page_citations
WHERE id IN (2738, 2739, 2740, 2741, 2750, 2751, 2752, 2753, 2769, 2951, 3219, 3229, 3308, 3370, 3382, 3385, 3386, 3391, 3392, 3393, 3441, 3442, 3444, 3445, 3449, 3450, 3452, 3453, 3454, 3461, 3465, 3469, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3713, 3714, 3715, 3717, 3806, 3900, 5018, 5019);

-- Show a sample of the URLs that would be cleared (up to 10):
SELECT id, url
FROM page_citations
WHERE id IN (2738, 2739, 2740, 2741, 2750, 2751, 2752, 2753, 2769, 2951, 3219, 3229, 3308, 3370, 3382, 3385, 3386, 3391, 3392, 3393, 3441, 3442, 3444, 3445, 3449, 3450, 3452, 3453, 3454, 3461, 3465, 3469, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3713, 3714, 3715, 3717, 3806, 3900, 5018, 5019) AND url IS NOT NULL
ORDER BY id LIMIT 10;
