/**
 * Core data layer: types, database loading, and basic entity lookups.
 *
 * Reads database.json (generated by scripts/build-data.mjs) which contains
 * pre-transformed typedEntities. Runs at build time / server-component level only.
 *
 * This module is the foundation for all other data modules.
 * Consumers should import from "@/data" (index.ts) for backward compatibility.
 */

import fs from "fs";
import path from "path";
import { loadYaml } from "@lib/yaml";
import { fetchFromWikiServer, withApiFallback, type WithSource } from "@lib/wiki-server";
import {
  TypedEntitySchema,
  type TypedEntity,
  type GenericEntity,
  isRisk,
  isPerson,
  isOrganization,
  isPolicy,
} from "./entity-schemas";
import type { ValidSubcategory } from "./valid-subcategories";

// Re-export for consumers
export type { WithSource };

// database.json is generated here by prebuild
const LOCAL_DATA_DIR = path.resolve(process.cwd(), "src/data");

// Source YAML data lives at the repo root
export const DATA_DIR = path.resolve(process.cwd(), "../../data");

// ============================================================================
// CORE TYPES
// ============================================================================

export interface IdRegistryMaps {
  byNumericId: Record<string, string>; // E1 → slug
  bySlug: Record<string, string>; // slug → E1
}

/**
 * Legacy Fact interface — kept as a bridge type for calc-engine and
 * AnthropicStakeholdersTable. The old facts pipeline has been retired;
 * database.facts is always empty. New code should use KB data instead.
 */
export interface Fact {
  value?: string;
  numeric?: number;
  low?: number;
  high?: number;
  asOf?: string;
  label?: string;
  source?: string;
  sourceResource?: string;
  sourceTitle?: string;
  sourcePublication?: string;
  sourceCredibility?: number;
  note?: string;
  entity: string;
  factId: string;
}

/** Raw entity shape as stored in database.json (before transformation) */
export interface RawEntity {
  id: string;
  type: string;
  title: string;
  description?: string;
  severity?: string;
  likelihood?: string | { level: string; status?: string; display?: string };
  timeframe?: string | { median: number; earliest?: number; latest?: number; display?: string };
  maturity?: string;
  website?: string;
  customFields?: { label: string; value: string; link?: string }[];
  relatedTopics?: string[];
  relatedEntries?: { id: string; type: string; relationship?: string }[];
  tags?: string[];
  lastUpdated?: string;
  sourceRefs?: string[];
  sources?: { title: string; url?: string; author?: string; date?: string }[];
  content?: unknown;
  numericId?: string;
  path?: string;
  status?: string;
  clusters?: string[];
  causeEffectGraph?: {
    title?: string;
    description?: string;
    nodes?: { id: string; [k: string]: unknown }[];
  };
}

export interface RelatedGraphEntry {
  id: string;
  type: string;
  title: string;
  score: number;
  label?: string;
}

export interface CruxPosition {
  view: string;
  probability?: string;
  holders?: string[];
  implications?: string;
}

export interface CruxData {
  id: string;
  question: string;
  domain?: string;
  description?: string;
  importance?: string;
  resolvability?: string;
  currentState?: string;
  positions?: CruxPosition[];
  wouldUpdateOn?: string[];
  relatedCruxes?: string[];
  relevantResearch?: Array<{ title: string; url?: string }>;
  timeframe?: string;
  summary?: string;
}

export interface BacklinkEntry {
  id: string;
  type: string;
  title: string;
  relationship?: string;
}

export type ContentFormat = 'article' | 'table' | 'diagram' | 'index' | 'dashboard';

export interface ChangeEntry {
  date: string;
  branch: string;
  title: string;
  summary: string;
  pr?: number;
  model?: string;
  duration?: string;
  cost?: string;
}

/** Serialized claim reference data stored in database.json */
export interface SerializedClaimRef {
  claimId: number;
  claimText: string;
  sourceUrl?: string;
  sourceTitle?: string;
  verdict?: string;
  verdictScore?: number;
  referenceId: string;
}

/** Serialized citation data stored in database.json */
export interface SerializedCitation {
  title?: string;
  url?: string;
  note?: string;
  resourceId?: string;
  referenceId: string;
}

/** Per-page reference data stored in database.json */
export interface SerializedPageReferences {
  claimReferences: SerializedClaimRef[];
  citations: SerializedCitation[];
}

export interface Resource {
  id: string;
  url: string;
  title: string;
  authors?: string[];
  published_date?: string;
  type: string;
  local_filename?: string;
  importance?: number;
  abstract?: string;
  summary?: string;
  review?: string;
  key_points?: string[];
  cited_by?: string[] | null;
  fetched_at?: string;
  tags?: string[];
  publication_id?: string;
  credibility_override?: number;
}

export interface Publication {
  id: string;
  name: string;
  type: string;
  credibility: number;
  peer_reviewed?: boolean;
  domains: string[];
  description?: string;
  credibility_rationale?: string;
  website?: string;
}

export interface Expert {
  id: string;
  name: string;
  affiliation?: string;
  role?: string;
  website?: string;
  knownFor?: string[];
}

export interface Organization {
  id: string;
  name: string;
  type: string;
  founded?: string;
  headquarters?: string;
  website?: string;
  funding?: string;
  employees?: string;
}

export interface Page {
  id: string;
  path: string;
  filePath: string;
  title: string;
  quality: number | null;
  readerImportance: number | null;
  researchImportance: number | null;
  tacticalValue: number | null;
  contentFormat: ContentFormat;
  tractability: number | null;
  neglectedness: number | null;
  uncertainty: number | null;
  causalLevel: string | null;
  lastUpdated: string | null;
  dateCreated?: string | null;
  llmSummary: string | null;
  description: string | null;
  ratings: {
    novelty?: number;
    rigor?: number;
    actionability?: number;
    completeness?: number;
  } | null;
  category: string;
  subcategory?: ValidSubcategory | null;
  tags?: string[];
  clusters?: string[];
  updateFrequency?: number | null;
  evergreen?: boolean;
  changeHistory?: ChangeEntry[];
  wordCount?: number;
  backlinkCount?: number;
  metrics?: {
    wordCount: number;
    tableCount: number;
    diagramCount: number;
    internalLinks: number;
    externalLinks: number;
    footnoteCount: number;
    bulletRatio: number;
    sectionCount: number;
    hasOverview: boolean;
    structuralScore: number;
  };
  suggestedQuality?: number;
  unconvertedLinkCount?: number;
  redundancy?: {
    maxSimilarity: number;
    similarPages: Array<{
      id: string;
      title: string;
      path: string;
      similarity: number;
    }>;
  };
  /** Resolved canonical entity type (e.g. 'person', 'organization', 'risk') */
  entityType?: string;
  /** Citation health stats from wiki-server (attached at build time) */
  citationHealth?: {
    total: number;
    withQuotes: number;
    verified: number;
    accuracyChecked: number;
    accurate: number;
    inaccurate: number;
    avgScore: number | null;
  };
  /** Computed hallucination risk — used by UI banners and AI agent triage */
  hallucinationRisk?: {
    /** Risk bucket: 'low' | 'medium' | 'high' */
    level: "low" | "medium" | "high";
    /** Numeric score 0-100 (higher = riskier) */
    score: number;
    /** Machine-readable factors explaining the score */
    factors: string[];
  };
  /** Pre-computed page coverage (structural completeness) from build-data */
  coverage?: {
    passing: number;
    total: number;
    targets: {
      tables: number;
      diagrams: number;
      internalLinks: number;
      externalLinks: number;
      footnotes: number;
      references: number;
    };
    actuals?: {
      tables: number;
      diagrams: number;
      internalLinks: number;
      externalLinks: number;
      footnotes: number;
      references: number;
      quotesWithQuotes: number;
      quotesTotal: number;
      accuracyChecked: number;
      accuracyTotal: number;
    };
    items: Record<string, "green" | "amber" | "red">;
    editHistoryCount?: number;
    ratingsString?: string;
  };
  /** Pre-computed reader importance rank (1 = most important) */
  readerRank?: number;
  /** Pre-computed research importance rank (1 = most important) */
  researchRank?: number;
  /** Pre-computed blended "recommended" score for ExploreGrid default sort */
  recommendedScore?: number;
}

interface DatabaseShape {
  typedEntities?: Array<Record<string, unknown>>;
  resources: Resource[];
  publications: Publication[];
  experts: Expert[];
  organizations: Organization[];
  cruxes: CruxData[];
  prItems: Record<string, unknown>[];
  backlinks: Record<string, BacklinkEntry[]>;
  relatedGraph: Record<string, RelatedGraphEntry[]>;
  pathRegistry: Record<string, string>;
  idRegistry: IdRegistryMaps;
  pages: Page[];
  /** Page → resource IDs mapping (computed at build time from inline <R>, cited_by, URL matching) */
  pageResources: Record<string, string[]>;
  stats: Record<string, unknown>;
  /** Pre-computed update schedule items (staleness, priority, etc.) */
  updateSchedule?: Array<{
    id: string;
    numericId: string;
    title: string;
    quality: number | null;
    readerImportance: number | null;
    lastUpdated: string | null;
    updateFrequency: number;
    daysSinceUpdate: number;
    daysUntilDue: number;
    staleness: number;
    priority: number;
    category: string;
  }>;
  /** Page reference index: page → { claimReferences, citations } for DB-driven footnotes */
  pageReferenceIndex?: Record<string, SerializedPageReferences>;
  /** Pre-aggregated hallucination risk statistics */
  riskStats?: {
    total: number;
    high: number;
    medium: number;
    low: number;
    avgScore: number;
    topFactors: Array<{ factor: string; count: number }>;
  };
  /** Citation quotes bundled at build time, keyed by pageId */
  citationQuotes?: Record<string, Array<{
    footnote: number;
    url: string | null;
    resourceId: string | null;
    claimText: string;
    sourceQuote: string | null;
    sourceTitle: string | null;
    sourceType: string | null;
    quoteVerified: boolean;
    verificationScore: number | null;
    verifiedAt: string | null;
    accuracyVerdict: string | null;
    accuracyScore: number | null;
    accuracyIssues: string | null;
    accuracySupportingQuotes: string | null;
    verificationDifficulty: string | null;
    accuracyCheckedAt: string | null;
  }>>;
  /**
   * Statement-backed citation dot data bundled at build time, keyed by page slug.
   * Populated by buildStatementCitationDots() from /api/statements/citation-dots/all.
   * Each entry is keyed by footnoteResourceId (e.g. "cr-abc123") and must be mapped
   * to a numeric footnote number via the referenceMap from renderMdxPage().
   */
  statementCitationDots?: Record<string, Array<{
    footnoteResourceId: string;
    claimText: string;
    url: string | null;
    resourceId: string | null;
    sourceQuote: string | null;
    sourceTitle: string | null;
    sourceType: string | null;
    quoteVerified: boolean;
    accuracyVerdict: string | null;
    accuracyScore: number | null;
    accuracyIssues: string | null;
    accuracyCheckedAt: string | null;
  }>>;
  /** KB (Knowledge Base) structured entity data from packages/kb */
  kb?: import("@longterm-wiki/kb").SerializedKB;
  /** KB fact verification status: factId → verdict (from citation quotes cross-reference) */
  kbFactVerification?: Record<string, string>;
}

// ============================================================================
// DATABASE LOADING
// ============================================================================

/** Union of fully-typed entities and generic (unknown-type) entities */
export type AnyEntity = TypedEntity | GenericEntity;

let _database: DatabaseShape | null = null;
let _typedEntities: AnyEntity[] | null = null;

export function getDatabase(): DatabaseShape {
  if (_database) return _database;

  const dbPath = path.join(LOCAL_DATA_DIR, "database.json");

  try {
    const raw = fs.readFileSync(dbPath, "utf-8");
    _database = JSON.parse(raw) as DatabaseShape;
  } catch (err) {
    throw new Error(
      `Failed to load database from ${dbPath}: ${err instanceof Error ? err.message : err}. ` +
      `Run "pnpm prebuild" first.`
    );
  }
  return _database;
}

/** Get all typed entities from the database */
export function getTypedEntities(): AnyEntity[] {
  if (_typedEntities) return _typedEntities;

  const db = getDatabase();

  if (!db.typedEntities || db.typedEntities.length === 0) {
    throw new Error(
      'database.json is missing typedEntities. ' +
      'Run "pnpm --filter longterm-next prebuild" to rebuild.'
    );
  }

  const entities: AnyEntity[] = [];
  const isDev = process.env.NODE_ENV === "development";

  for (const raw of db.typedEntities) {
    const result = TypedEntitySchema.safeParse(raw);
    if (result.success) {
      entities.push(result.data);
    } else {
      // Unknown entity types — keep all fields as-is.
      // Don't re-parse through GenericEntitySchema as Zod would strip extra keys
      // like content, currentAssessment, ratings, causeEffectGraph.
      if (isDev) {
        const id = (raw as Record<string, unknown>).id;
        const type = (raw as Record<string, unknown>).entityType as string;
        console.warn(
          `[entity-validation] ${id} (${type}): ${result.error.issues.map(i => i.message).join(", ")}`
        );
      }
      entities.push(raw as unknown as GenericEntity);
    }
  }

  _typedEntities = entities;
  return _typedEntities;
}

// ============================================================================
// TYPES (re-exported for consumers)
// ============================================================================

export type { TypedEntity, GenericEntity, RiskEntity, PersonEntity, OrganizationEntity, PolicyEntity } from "./entity-schemas";
export { isRisk, isPerson, isOrganization, isPolicy } from "./entity-schemas";

/** @deprecated Use TypedEntity instead */
interface Entity {
  id: string;
  type: string;
  title: string;
  description?: string;
  severity?: string;
  likelihood?: string | { level: string; status?: string; display?: string };
  timeframe?: string | { median: number; earliest?: number; latest?: number; display?: string };
  maturity?: string;
  website?: string;
  customFields?: { label: string; value: string; link?: string }[];
  relatedTopics?: string[];
  relatedEntries?: { id: string; type: string; relationship?: string }[];
  tags?: string[];
  lastUpdated?: string;
  sourceRefs?: string[];
  sources?: { title: string; url?: string; author?: string; date?: string }[];
  content?: unknown;
}

// ============================================================================
// ID RESOLUTION
// ============================================================================

/**
 * Resolve an ID that may be numeric (E35) or a slug (deepmind) to its slug form.
 * Returns the original ID if it's already a slug or not found in the registry.
 */
export function resolveId(id: string): string {
  if (/^E\d+$/.test(id)) {
    const registry = getIdRegistry();
    return registry.byNumericId[id] || id;
  }
  return id;
}

export function getIdRegistry(): IdRegistryMaps {
  return getDatabase().idRegistry;
}

// ============================================================================
// LOOKUP INDEXES (built lazily)
// ============================================================================

let _typedEntityIndex: Map<string, AnyEntity> | null = null;
let _resourceIndex: Map<string, Resource> | null = null;
let _publicationIndex: Map<string, Publication> | null = null;
let _expertIndex: Map<string, Expert> | null = null;
let _orgIndex: Map<string, Organization> | null = null;
let _pageIndex: Map<string, Page> | null = null;

function typedEntityIndex() {
  if (!_typedEntityIndex) {
    _typedEntityIndex = new Map(getTypedEntities().map(e => [e.id, e]));
  }
  return _typedEntityIndex;
}

function resourceIndex() {
  if (!_resourceIndex) {
    const db = getDatabase();
    _resourceIndex = new Map((db.resources || []).map((r) => [r.id, r]));
  }
  return _resourceIndex;
}

function publicationIndex() {
  if (!_publicationIndex) {
    const db = getDatabase();
    _publicationIndex = new Map(
      (db.publications || []).map((p) => [p.id, p])
    );
  }
  return _publicationIndex;
}

function expertIndex() {
  if (!_expertIndex) {
    const db = getDatabase();
    _expertIndex = new Map((db.experts || []).map((e) => [e.id, e]));
  }
  return _expertIndex;
}

function orgIndex() {
  if (!_orgIndex) {
    const db = getDatabase();
    _orgIndex = new Map((db.organizations || []).map((o) => [o.id, o]));
  }
  return _orgIndex;
}

function pageIndex() {
  if (!_pageIndex) {
    const db = getDatabase();
    _pageIndex = new Map((db.pages || []).map((p) => [p.id, p]));
  }
  return _pageIndex;
}

// ============================================================================
// LOOKUP FUNCTIONS
// ============================================================================

/** Get a typed entity by ID — accepts numeric (E35) or slug (deepmind) */
export function getTypedEntityById(id: string): AnyEntity | undefined {
  return typedEntityIndex().get(resolveId(id));
}

/** @deprecated Use getTypedEntityById for new code */
export function getEntityById(id: string): Entity | undefined {
  // Return typed entity cast to the old Entity interface for backward compat
  const typed = typedEntityIndex().get(resolveId(id));
  if (!typed) return undefined;
  return {
    id: typed.id,
    type: typed.entityType,
    title: typed.title,
    description: typed.description,
    tags: typed.tags,
    relatedEntries: typed.relatedEntries,
    sources: typed.sources,
    lastUpdated: typed.lastUpdated,
    website: typed.website,
    customFields: typed.customFields,
    // Type-specific fields (spread them for backward compat)
    ...(isRisk(typed) ? {
      severity: typed.severity,
      likelihood: typed.likelihood,
      timeframe: typed.timeframe,
      maturity: typed.maturity,
    } : {}),
  };
}

export function getResourceById(id: string): Resource | undefined {
  return resourceIndex().get(id);
}

/** Get all resources */
export function getAllResources(): Resource[] {
  const db = getDatabase();
  return db.resources ?? [];
}

/** Get resource IDs for a page (computed at build time from inline <R>, cited_by, URL matching) */
export function getResourcesForPage(pageId: string): string[] {
  const db = getDatabase();
  return db.pageResources?.[resolveId(pageId)] ?? [];
}

/** Get page IDs that cite a given resource (reverse lookup of pageResources) */
export function getPagesForResource(resourceId: string): string[] {
  const db = getDatabase();
  const pr = db.pageResources ?? {};
  const pages: string[] = [];
  for (const [pageId, ids] of Object.entries(pr)) {
    if ((ids as string[]).includes(resourceId)) {
      pages.push(pageId);
    }
  }
  return pages;
}

/** Get DB-driven reference data for a page (for the reference preprocessor) */
export function getPageReferences(pageId: string): SerializedPageReferences | null {
  const db = getDatabase();
  return db.pageReferenceIndex?.[resolveId(pageId)] ?? null;
}

export function getPublicationById(id: string): Publication | undefined {
  return publicationIndex().get(id);
}

/** Get all publications */
export function getAllPublications(): Publication[] {
  const db = getDatabase();
  return db.publications ?? [];
}

/** Get resources that belong to a publication */
export function getResourcesForPublication(publicationId: string): Resource[] {
  return getAllResources().filter((r) => r.publication_id === publicationId);
}

export function getExpertById(id: string): Expert | undefined {
  return expertIndex().get(id);
}

export function getOrganizationById(id: string): Organization | undefined {
  return orgIndex().get(id);
}

export function getPageById(id: string): Page | undefined {
  return pageIndex().get(resolveId(id));
}

export function getAllPages(): Page[] {
  return getDatabase().pages || [];
}

// ============================================================================
// RESOURCE HELPERS
// ============================================================================

export function getResourceCredibility(
  resource: Resource
): number | undefined {
  if (resource.credibility_override !== undefined) return resource.credibility_override;
  if (resource.publication_id) {
    const pub = getPublicationById(resource.publication_id);
    return pub?.credibility;
  }
  return undefined;
}

export function getResourcePublication(
  resource: Resource
): Publication | undefined {
  if (resource.publication_id) {
    return getPublicationById(resource.publication_id);
  }
  return undefined;
}

// Re-export loadYaml for use in domain modules
export { loadYaml };
// Re-export wiki-server helpers
export { fetchFromWikiServer, withApiFallback };
