/**
 * Data layer for longterm-wiki
 *
 * Reads database.json (generated by scripts/build-data.mjs) which contains
 * pre-transformed typedEntities. Runs at build time / server-component level only.
 *
 * Typed entities are validated via Zod schemas at load time.
 * See entity-schemas.ts for the schema definitions.
 */

import fs from "fs";
import path from "path";
import { loadYaml } from "@lib/yaml";
import { fetchFromWikiServer, withApiFallback, type WithSource } from "@lib/wiki-server";
import {
  TypedEntitySchema,
  type TypedEntity,
  type GenericEntity,
  isRisk,
  isPerson,
  isOrganization,
  isPolicy,
} from "./entity-schemas";

// database.json is generated here by prebuild
const LOCAL_DATA_DIR = path.resolve(process.cwd(), "src/data");

// Source YAML data lives at the repo root
const DATA_DIR = path.resolve(process.cwd(), "../../data");

// ============================================================================
// DATABASE LOADING
// ============================================================================

interface IdRegistryMaps {
  byNumericId: Record<string, string>; // E1 → slug
  bySlug: Record<string, string>; // slug → E1
}

export interface Fact {
  value?: string;
  numeric?: number;
  /** Lower bound of range (for estimates like "$20-26 billion") */
  low?: number;
  /** Upper bound of range */
  high?: number;
  asOf?: string;
  /** Short human-readable name (e.g., "Anthropic post-money valuation") */
  label?: string;
  source?: string;
  sourceResource?: string;
  /** Resolved resource metadata (populated at build time from sourceResource) */
  sourceTitle?: string;
  sourcePublication?: string;
  sourceCredibility?: number;
  note?: string;
  noCompute?: boolean;
  /** Measure ID from data/fact-measures.yaml — groups related facts into timeseries.
   *  Auto-inferred from fact ID at build time if not set explicitly. */
  measure?: string;
  /** Subject override — defaults to parent entity. Use for benchmark/comparison facts
   *  (e.g., subject: "industry-average") that shouldn't appear in entity timeseries. */
  subject?: string;
  compute?: string;
  format?: string;
  formatDivisor?: number;
  entity: string;
  factId: string;
  computed?: boolean;
}

export interface FactMeasure {
  id: string;
  label: string;
  unit: string;
  category: string;
  direction?: "higher" | "lower";
  description?: string;
  display?: {
    divisor?: number;
    prefix?: string;
    suffix?: string;
  };
  relatedMeasures?: string[];
  applicableTo?: string[];
}

/** A timeseries entry — a fact observation for a specific entity+measure at a point in time */
export interface TimeseriesPoint {
  entity: string;
  factId: string;
  measure: string;
  asOf: string;
  value?: string;
  numeric?: number;
  low?: number;
  high?: number;
  note?: string;
  source?: string;
}

/** Raw entity shape as stored in database.json (before transformation) */
interface RawEntity {
  id: string;
  type: string;
  title: string;
  description?: string;
  severity?: string;
  likelihood?: string | { level: string; status?: string; display?: string };
  timeframe?: string | { median: number; earliest?: number; latest?: number; display?: string };
  maturity?: string;
  website?: string;
  customFields?: { label: string; value: string; link?: string }[];
  relatedTopics?: string[];
  relatedEntries?: { id: string; type: string; relationship?: string }[];
  tags?: string[];
  lastUpdated?: string;
  sourceRefs?: string[];
  sources?: { title: string; url?: string; author?: string; date?: string }[];
  content?: unknown;
  numericId?: string;
  path?: string;
  status?: string;
  clusters?: string[];
  causeEffectGraph?: {
    title?: string;
    description?: string;
    nodes?: { id: string; [k: string]: unknown }[];
  };
}

interface RelatedGraphEntry {
  id: string;
  type: string;
  title: string;
  score: number;
  label?: string;
}

export interface CruxPosition {
  view: string;
  probability?: string;
  holders?: string[];
  implications?: string;
}

export interface CruxData {
  id: string;
  question: string;
  domain?: string;
  description?: string;
  importance?: string;
  resolvability?: string;
  currentState?: string;
  positions?: CruxPosition[];
  wouldUpdateOn?: string[];
  relatedCruxes?: string[];
  relevantResearch?: Array<{ title: string; url?: string }>;
  timeframe?: string;
  summary?: string;
}

export interface Intervention {
  id: string;
  name: string;
  category?: string;
  description?: string;
  riskCoverage?: {
    accident?: string;
    misuse?: string;
    structural?: string;
    epistemic?: string;
  };
  primaryMechanism?: string;
  tractability?: string;
  neglectedness?: string;
  importance?: string;
  overallPriority?: string;
  timelineFit?: string;
  currentState?: string;
  fundingLevel?: string;
  fundingShare?: string;
  recommendedShift?: string;
  wikiPageId?: string;
  relatedInterventions?: string[];
  relevantResearch?: Array<{ title: string; url?: string }>;
}

interface DatabaseShape {
  typedEntities?: Array<Record<string, unknown>>;
  resources: Resource[];
  publications: Publication[];
  experts: Expert[];
  organizations: Organization[];
  interventions: Intervention[];
  cruxes: CruxData[];
  proposals: Proposal[];
  prItems: PrItem[];
  backlinks: Record<string, BacklinkEntry[]>;
  relatedGraph: Record<string, RelatedGraphEntry[]>;
  pathRegistry: Record<string, string>;
  idRegistry: IdRegistryMaps;
  pages: Page[];
  facts: Record<string, Fact>;
  factMeasures: Record<string, FactMeasure>;
  /** Timeseries index: measure ID → sorted array of observations */
  factTimeseries: Record<string, TimeseriesPoint[]>;
  /** Reverse index: "entity.factId" → pages that reference it via <F> */
  factUsage: Record<string, FactUsagePage[]>;
  /** Page → resource IDs mapping (computed at build time from inline <R>, cited_by, URL matching) */
  pageResources: Record<string, string[]>;
  /** Footnote index: page → { footnotes, sources } for unified citation rendering */
  footnoteIndex?: Record<string, FootnoteIndexEntry>;
  stats: Record<string, unknown>;
  /** Pre-computed update schedule items (staleness, priority, etc.) */
  updateSchedule?: Array<{
    id: string;
    numericId: string;
    title: string;
    quality: number | null;
    readerImportance: number | null;
    lastUpdated: string | null;
    updateFrequency: number;
    daysSinceUpdate: number;
    daysUntilDue: number;
    staleness: number;
    priority: number;
    category: string;
  }>;
  /** Pre-aggregated hallucination risk statistics */
  riskStats?: {
    total: number;
    high: number;
    medium: number;
    low: number;
    avgScore: number;
    topFactors: Array<{ factor: string; count: number }>;
  };
}

// ============================================================================
// DATABASE LOADING
// ============================================================================

/** Union of fully-typed entities and generic (unknown-type) entities */
type AnyEntity = TypedEntity | GenericEntity;

let _database: DatabaseShape | null = null;
let _typedEntities: AnyEntity[] | null = null;

function getDatabase(): DatabaseShape {
  if (_database) return _database;

  const dbPath = path.join(LOCAL_DATA_DIR, "database.json");

  try {
    const raw = fs.readFileSync(dbPath, "utf-8");
    _database = JSON.parse(raw) as DatabaseShape;
  } catch (err) {
    throw new Error(
      `Failed to load database from ${dbPath}: ${err instanceof Error ? err.message : err}. ` +
      `Run "pnpm prebuild" first.`
    );
  }
  return _database;
}

/** Get all typed entities from the database */
export function getTypedEntities(): AnyEntity[] {
  if (_typedEntities) return _typedEntities;

  const db = getDatabase();

  if (!db.typedEntities || db.typedEntities.length === 0) {
    throw new Error(
      'database.json is missing typedEntities. ' +
      'Run "pnpm --filter longterm-next prebuild" to rebuild.'
    );
  }

  const entities: AnyEntity[] = [];
  const isDev = process.env.NODE_ENV === "development";

  for (const raw of db.typedEntities) {
    const result = TypedEntitySchema.safeParse(raw);
    if (result.success) {
      entities.push(result.data);
    } else {
      // Unknown entity types (ai-transition-model-*, etc.) — keep all fields as-is.
      // Don't re-parse through GenericEntitySchema as Zod would strip extra keys
      // like content, currentAssessment, ratings, causeEffectGraph.
      if (isDev) {
        const id = (raw as Record<string, unknown>).id;
        const type = (raw as Record<string, unknown>).entityType as string;
        // Suppress warnings for known catch-all types that intentionally skip
        // the discriminated union (they carry extra fields Zod would strip).
        const isCatchAll = typeof type === "string" && type.startsWith("ai-transition-model-");
        if (!isCatchAll) {
          console.warn(
            `[entity-validation] ${id} (${type}): ${result.error.issues.map(i => i.message).join(", ")}`
          );
        }
      }
      entities.push(raw as unknown as GenericEntity);
    }
  }

  _typedEntities = entities;
  return _typedEntities;
}

// ============================================================================
// TYPES (re-exported for consumers)
// ============================================================================

// Re-export typed entity types for consumers
export type { TypedEntity, GenericEntity, RiskEntity, PersonEntity, OrganizationEntity, PolicyEntity } from "./entity-schemas";
export type { AnyEntity };

/** @deprecated Use TypedEntity instead */
interface Entity {
  id: string;
  type: string;
  title: string;
  description?: string;
  severity?: string;
  likelihood?: string | { level: string; status?: string; display?: string };
  timeframe?: string | { median: number; earliest?: number; latest?: number; display?: string };
  maturity?: string;
  website?: string;
  customFields?: { label: string; value: string; link?: string }[];
  relatedTopics?: string[];
  relatedEntries?: { id: string; type: string; relationship?: string }[];
  tags?: string[];
  lastUpdated?: string;
  sourceRefs?: string[];
  sources?: { title: string; url?: string; author?: string; date?: string }[];
  content?: unknown;
}

/** Single footnote entry in the footnoteIndex */
export interface FootnoteEntry {
  url: string | null;
  title: string | null;
  resourceId?: string;
}

/** Source group in the footnoteIndex — deduped by URL */
export interface FootnoteSourceEntry {
  url: string;
  title: string;
  domain: string;
  footnoteNumbers: number[];
  resourceId: string | null;
}

/** Per-page footnote index data */
export interface FootnoteIndexEntry {
  footnotes: Record<number, FootnoteEntry>;
  sources: FootnoteSourceEntry[];
}

export interface Resource {
  id: string;
  url: string;
  title: string;
  authors?: string[];
  published_date?: string;
  type: string;
  summary?: string;
  tags?: string[];
  publication_id?: string;
  credibility_override?: number;
}

interface Publication {
  id: string;
  name: string;
  type: string;
  credibility: number;
  peer_reviewed?: boolean;
  domains: string[];
  description?: string;
}

interface Expert {
  id: string;
  name: string;
  affiliation?: string;
  role?: string;
  website?: string;
  knownFor?: string[];
}

interface Organization {
  id: string;
  name: string;
  type: string;
  founded?: string;
  headquarters?: string;
  website?: string;
  funding?: string;
  employees?: string;
}

interface BacklinkEntry {
  id: string;
  type: string;
  title: string;
  relationship?: string;
}

export type ContentFormat = 'article' | 'table' | 'diagram' | 'index' | 'dashboard';

export interface StructuredSummary {
  oneLiner: string;
  keyPoints: string[];
  bottomLine: string;
}

export interface ChangeEntry {
  date: string;
  branch: string;
  title: string;
  summary: string;
  pr?: number;
  model?: string;
  duration?: string;
  cost?: string;
}

export interface Page {
  id: string;
  path: string;
  filePath: string;
  title: string;
  quality: number | null;
  readerImportance: number | null;
  researchImportance: number | null;
  tacticalValue: number | null;
  contentFormat: ContentFormat;
  tractability: number | null;
  neglectedness: number | null;
  uncertainty: number | null;
  causalLevel: string | null;
  lastUpdated: string | null;
  dateCreated?: string | null;
  llmSummary: string | null;
  structuredSummary: StructuredSummary | null;
  description: string | null;
  ratings: {
    novelty?: number;
    rigor?: number;
    actionability?: number;
    completeness?: number;
  } | null;
  category: string;
  subcategory?: string | null;
  tags?: string[];
  clusters?: string[];
  updateFrequency?: number | null;
  evergreen?: boolean;
  changeHistory?: ChangeEntry[];
  wordCount?: number;
  backlinkCount?: number;
  metrics?: {
    wordCount: number;
    tableCount: number;
    diagramCount: number;
    internalLinks: number;
    externalLinks: number;
    footnoteCount: number;
    bulletRatio: number;
    sectionCount: number;
    hasOverview: boolean;
    structuralScore: number;
  };
  suggestedQuality?: number;
  unconvertedLinkCount?: number;
  redundancy?: {
    maxSimilarity: number;
    similarPages: Array<{
      id: string;
      title: string;
      path: string;
      similarity: number;
    }>;
  };
  /** Resolved canonical entity type (e.g. 'person', 'organization', 'risk') */
  entityType?: string;
  /** Citation health stats from wiki-server (attached at build time) */
  citationHealth?: {
    total: number;
    withQuotes: number;
    verified: number;
    accuracyChecked: number;
    accurate: number;
    inaccurate: number;
    avgScore: number | null;
  };
  /** Computed hallucination risk — used by UI banners and AI agent triage */
  hallucinationRisk?: {
    /** Risk bucket: 'low' | 'medium' | 'high' */
    level: "low" | "medium" | "high";
    /** Numeric score 0-100 (higher = riskier) */
    score: number;
    /** Machine-readable factors explaining the score */
    factors: string[];
  };
  /** Pre-computed page coverage (structural completeness) from build-data */
  coverage?: {
    passing: number;
    total: number;
    targets: {
      tables: number;
      diagrams: number;
      internalLinks: number;
      externalLinks: number;
      footnotes: number;
      references: number;
    };
    actuals?: {
      tables: number;
      diagrams: number;
      internalLinks: number;
      externalLinks: number;
      footnotes: number;
      references: number;
      quotesWithQuotes: number;
      quotesTotal: number;
      accuracyChecked: number;
      accuracyTotal: number;
    };
    items: Record<string, "green" | "amber" | "red">;
    editHistoryCount?: number;
    ratingsString?: string;
    factCount?: number;
  };
  /** Pre-computed reader importance rank (1 = most important) */
  readerRank?: number;
  /** Pre-computed research importance rank (1 = most important) */
  researchRank?: number;
  /** Pre-computed blended "recommended" score for ExploreGrid default sort */
  recommendedScore?: number;
}

// ============================================================================
// LOOKUP INDEXES (built lazily)
// ============================================================================

let _typedEntityIndex: Map<string, AnyEntity> | null = null;
let _resourceIndex: Map<string, Resource> | null = null;
let _publicationIndex: Map<string, Publication> | null = null;
let _expertIndex: Map<string, Expert> | null = null;
let _orgIndex: Map<string, Organization> | null = null;
let _pageIndex: Map<string, Page> | null = null;

function typedEntityIndex() {
  if (!_typedEntityIndex) {
    _typedEntityIndex = new Map(getTypedEntities().map(e => [e.id, e]));
  }
  return _typedEntityIndex;
}

function resourceIndex() {
  if (!_resourceIndex) {
    const db = getDatabase();
    _resourceIndex = new Map((db.resources || []).map((r) => [r.id, r]));
  }
  return _resourceIndex;
}

function publicationIndex() {
  if (!_publicationIndex) {
    const db = getDatabase();
    _publicationIndex = new Map(
      (db.publications || []).map((p) => [p.id, p])
    );
  }
  return _publicationIndex;
}

function expertIndex() {
  if (!_expertIndex) {
    const db = getDatabase();
    _expertIndex = new Map((db.experts || []).map((e) => [e.id, e]));
  }
  return _expertIndex;
}

function orgIndex() {
  if (!_orgIndex) {
    const db = getDatabase();
    _orgIndex = new Map((db.organizations || []).map((o) => [o.id, o]));
  }
  return _orgIndex;
}

function pageIndex() {
  if (!_pageIndex) {
    const db = getDatabase();
    _pageIndex = new Map((db.pages || []).map((p) => [p.id, p]));
  }
  return _pageIndex;
}

// ============================================================================
// LOOKUP FUNCTIONS
// ============================================================================

/** Get a typed entity by ID — accepts numeric (E35) or slug (deepmind) */
export function getTypedEntityById(id: string): AnyEntity | undefined {
  return typedEntityIndex().get(resolveId(id));
}

/** @deprecated Use getTypedEntityById for new code */
export function getEntityById(id: string): Entity | undefined {
  // Return typed entity cast to the old Entity interface for backward compat
  const typed = typedEntityIndex().get(resolveId(id));
  if (!typed) return undefined;
  return {
    id: typed.id,
    type: typed.entityType,
    title: typed.title,
    description: typed.description,
    tags: typed.tags,
    relatedEntries: typed.relatedEntries,
    sources: typed.sources,
    lastUpdated: typed.lastUpdated,
    website: typed.website,
    customFields: typed.customFields,
    // Type-specific fields (spread them for backward compat)
    ...(isRisk(typed) ? {
      severity: typed.severity,
      likelihood: typed.likelihood,
      timeframe: typed.timeframe,
      maturity: typed.maturity,
    } : {}),
  };
}

export function getResourceById(id: string): Resource | undefined {
  return resourceIndex().get(id);
}

/** Get resource IDs for a page (computed at build time from inline <R>, cited_by, URL matching) */
export function getResourcesForPage(pageId: string): string[] {
  const db = getDatabase();
  return db.pageResources?.[resolveId(pageId)] ?? [];
}

/** Get footnote index data for a page (computed at build time from MDX footnotes) */
export function getFootnoteIndex(pageId: string): FootnoteIndexEntry | undefined {
  const db = getDatabase();
  return db.footnoteIndex?.[resolveId(pageId)];
}

export function getPublicationById(id: string): Publication | undefined {
  return publicationIndex().get(id);
}

export function getExpertById(id: string): Expert | undefined {
  return expertIndex().get(id);
}

export function getOrganizationById(id: string): Organization | undefined {
  return orgIndex().get(id);
}

export function getPageById(id: string): Page | undefined {
  return pageIndex().get(resolveId(id));
}

export function getAllPages(): Page[] {
  return getDatabase().pages || [];
}

export interface UpdateScheduleItem {
  id: string;
  numericId: string;
  title: string;
  quality: number | null;
  readerImportance: number | null;
  lastUpdated: string | null;
  updateFrequency: number;
  daysSinceUpdate: number;
  daysUntilDue: number;
  staleness: number;
  priority: number;
  category: string;
}

export async function getUpdateSchedule(): Promise<WithSource<UpdateScheduleItem[]>> {
  return withApiFallback(
    async () => {
      const data = await fetchFromWikiServer<UpdateScheduleItem[]>(
        `/api/pages/update-schedule`
      );
      return data;
    },
    // Local fallback: pre-computed at build time in build-data.mjs
    () => getDatabase().updateSchedule || []
  );
}

export interface PageRankingItem {
  id: string;
  numericId: string;
  title: string;
  quality: number | null;
  readerImportance: number | null;
  readerRank: number | null;
  researchImportance: number | null;
  researchRank: number | null;
  tacticalValue: number | null;
  category: string;
  wordCount: number;
}

export function getPageRankings(): PageRankingItem[] {
  const db = getDatabase();
  const pages = db.pages || [];

  // Ranks are pre-computed at build time in build-data.mjs
  const items = pages
    .filter((p: Page) => p.readerImportance != null || p.researchImportance != null)
    .map((p: Page) => ({
      id: p.id,
      numericId: db.idRegistry?.bySlug[p.id] || p.id,
      title: p.title,
      quality: p.quality,
      readerImportance: p.readerImportance,
      readerRank: p.readerRank ?? null,
      researchImportance: p.researchImportance,
      researchRank: p.researchRank ?? null,
      tacticalValue: p.tacticalValue,
      category: p.category,
      wordCount: p.wordCount ?? p.metrics?.wordCount ?? 0,
    }));

  // Default sort by readership importance
  items.sort((a, b) => (b.readerImportance ?? 0) - (a.readerImportance ?? 0));
  return items;
}

export interface PageChangeItem {
  pageId: string;
  pageTitle: string;
  pagePath: string;
  numericId: string;
  date: string;
  branch: string;
  sessionTitle: string;
  summary: string;
  category: string;
  pr?: number;
  model?: string;
  duration?: string;
  cost?: string;
}

export interface PageChangePageInfo {
  pageId: string;
  pageTitle: string;
  pagePath: string;
  numericId: string;
  category: string;
}

export interface PageChangesSession {
  sessionKey: string;
  date: string;
  branch: string;
  sessionTitle: string;
  summary: string;
  pr?: number;
  model?: string;
  duration?: string;
  cost?: string;
  issues?: string[];
  learnings?: string[];
  recommendations?: string[];
  pages: PageChangePageInfo[];
}

export function getPageChanges(): PageChangeItem[] {
  const db = getDatabase();
  const pages = db.pages || [];
  const items: PageChangeItem[] = [];

  for (const page of pages) {
    if (!page.changeHistory || page.changeHistory.length === 0) continue;
    const numericId = db.idRegistry?.bySlug[page.id] || page.id;
    for (const entry of page.changeHistory) {
      items.push({
        pageId: page.id,
        pageTitle: page.title,
        pagePath: page.path,
        numericId,
        date: entry.date,
        branch: entry.branch,
        sessionTitle: entry.title,
        summary: entry.summary,
        category: page.category,
        ...(entry.pr !== undefined && { pr: entry.pr }),
        ...(entry.model !== undefined && { model: entry.model }),
        ...(entry.duration !== undefined && { duration: entry.duration }),
        ...(entry.cost !== undefined && { cost: entry.cost }),
      });
    }
  }

  // Sort by date descending (most recent first)
  items.sort((a, b) => b.date.localeCompare(a.date));
  return items;
}

export function getPageChangeSessions(): PageChangesSession[] {
  const db = getDatabase();
  const pages = db.pages || [];
  const sessionMap = new Map<string, PageChangesSession>();

  for (const page of pages) {
    if (!page.changeHistory || page.changeHistory.length === 0) continue;
    const numericId = db.idRegistry?.bySlug[page.id] || page.id;
    for (const entry of page.changeHistory) {
      const sessionKey = `${entry.date}|${entry.branch}`;
      if (!sessionMap.has(sessionKey)) {
        sessionMap.set(sessionKey, {
          sessionKey,
          date: entry.date,
          branch: entry.branch,
          sessionTitle: entry.title,
          summary: entry.summary,
          ...(entry.pr !== undefined && { pr: entry.pr }),
          ...(entry.model !== undefined && { model: entry.model }),
          ...(entry.duration !== undefined && { duration: entry.duration }),
          ...(entry.cost !== undefined && { cost: entry.cost }),
          pages: [],
        });
      }
      sessionMap.get(sessionKey)!.pages.push({
        pageId: page.id,
        pageTitle: page.title,
        pagePath: page.path,
        numericId,
        category: page.category,
      });
    }
  }

  // Sort by date descending (most recent first)
  return Array.from(sessionMap.values()).sort((a, b) =>
    b.date.localeCompare(a.date)
  );
}

export interface PageCoverageItem {
  id: string;
  numericId: string;
  title: string;
  // Quality & importance
  quality: number | null;
  readerImportance: number | null;
  researchImportance: number | null;
  tacticalValue: number | null;
  // Classification
  contentFormat: ContentFormat;
  wordCount: number;
  category: string;
  entityType: string | null;
  subcategory: string | null;
  // Coverage score
  score: number;      // passing count
  total: number;      // total items (13)
  // Hallucination risk
  riskLevel: "low" | "medium" | "high" | null;
  riskScore: number | null;
  // Temporal
  lastUpdated: string | null;
  updateFrequency: number | null;
  // Ratings (1–10)
  novelty: number | null;
  rigor: number | null;
  actionability: number | null;
  completeness: number | null;
  // Citation health
  citationTotal: number;
  citationWithQuotes: number;
  citationAccuracyChecked: number;
  citationAvgScore: number | null;
  // Structural
  backlinkCount: number;
  sectionCount: number;
  unconvertedLinkCount: number;
  // Boolean items
  llmSummary: boolean;
  structuredSummary: boolean;
  schedule: boolean;
  entity: boolean;
  editHistory: boolean;
  // Numeric item statuses + actual/target values
  tables: "green" | "amber" | "red";
  tablesActual: number;
  tablesTarget: number;
  diagrams: "green" | "amber" | "red";
  diagramsActual: number;
  diagramsTarget: number;
  internalLinks: "green" | "amber" | "red";
  internalLinksActual: number;
  internalLinksTarget: number;
  externalLinks: "green" | "amber" | "red";
  externalLinksActual: number;
  externalLinksTarget: number;
  footnotes: "green" | "amber" | "red";
  footnotesActual: number;
  footnotesTarget: number;
  references: "green" | "amber" | "red";
  referencesActual: number;
  referencesTarget: number;
  quotes: "green" | "amber" | "red";
  quotesActual: number;
  quotesTotal: number;
  accuracy: "green" | "amber" | "red";
  accuracyActual: number;
  accuracyTotal: number;
}

export function getPageCoverageItems(): PageCoverageItem[] {
  const db = getDatabase();
  const pages = db.pages || [];
  const items: PageCoverageItem[] = [];

  for (const page of pages) {
    const cov = page.coverage;
    if (!cov) continue;

    const numericId = db.idRegistry?.bySlug[page.id] || page.id;
    const ch = page.citationHealth;
    items.push({
      id: page.id,
      numericId,
      title: page.title,
      // Quality & importance
      quality: page.quality,
      readerImportance: page.readerImportance,
      researchImportance: page.researchImportance,
      tacticalValue: page.tacticalValue,
      // Classification
      contentFormat: page.contentFormat,
      wordCount: page.wordCount ?? page.metrics?.wordCount ?? 0,
      category: page.category,
      entityType: page.entityType ?? null,
      subcategory: page.subcategory ?? null,
      // Coverage
      score: cov.passing,
      total: cov.total,
      // Hallucination risk
      riskLevel: page.hallucinationRisk?.level ?? null,
      riskScore: page.hallucinationRisk?.score ?? null,
      // Temporal
      lastUpdated: page.lastUpdated,
      updateFrequency: page.updateFrequency ?? null,
      // Ratings
      novelty: page.ratings?.novelty ?? null,
      rigor: page.ratings?.rigor ?? null,
      actionability: page.ratings?.actionability ?? null,
      completeness: page.ratings?.completeness ?? null,
      // Citation health
      citationTotal: ch?.total ?? 0,
      citationWithQuotes: ch?.withQuotes ?? 0,
      citationAccuracyChecked: ch?.accuracyChecked ?? 0,
      citationAvgScore: ch?.avgScore ?? null,
      // Structural
      backlinkCount: page.backlinkCount ?? 0,
      sectionCount: page.metrics?.sectionCount ?? 0,
      unconvertedLinkCount: page.unconvertedLinkCount ?? 0,
      // Booleans
      llmSummary: cov.items.llmSummary === "green",
      structuredSummary: cov.items.structuredSummary === "green",
      schedule: cov.items.schedule === "green",
      entity: cov.items.entity === "green",
      editHistory: cov.items.editHistory === "green",
      // Metric statuses + actuals
      tables: cov.items.tables as "green" | "amber" | "red",
      tablesActual: cov.actuals?.tables ?? 0,
      tablesTarget: cov.targets.tables,
      diagrams: cov.items.diagrams as "green" | "amber" | "red",
      diagramsActual: cov.actuals?.diagrams ?? 0,
      diagramsTarget: cov.targets.diagrams,
      internalLinks: cov.items.internalLinks as "green" | "amber" | "red",
      internalLinksActual: cov.actuals?.internalLinks ?? 0,
      internalLinksTarget: cov.targets.internalLinks,
      externalLinks: cov.items.externalLinks as "green" | "amber" | "red",
      externalLinksActual: cov.actuals?.externalLinks ?? 0,
      externalLinksTarget: cov.targets.externalLinks,
      footnotes: cov.items.footnotes as "green" | "amber" | "red",
      footnotesActual: cov.actuals?.footnotes ?? 0,
      footnotesTarget: cov.targets.footnotes,
      references: cov.items.references as "green" | "amber" | "red",
      referencesActual: cov.actuals?.references ?? 0,
      referencesTarget: cov.targets.references,
      quotes: cov.items.quotes as "green" | "amber" | "red",
      quotesActual: cov.actuals?.quotesWithQuotes ?? 0,
      quotesTotal: cov.actuals?.quotesTotal ?? 0,
      accuracy: cov.items.accuracy as "green" | "amber" | "red",
      accuracyActual: cov.actuals?.accuracyChecked ?? 0,
      accuracyTotal: cov.actuals?.accuracyTotal ?? 0,
    });
  }

  // Sort by score ascending (worst coverage first)
  items.sort((a, b) => (a.score / a.total) - (b.score / b.total));
  return items;
}

export async function getPageCitationHealth(pageId: string) {
  const result = await withApiFallback(
    () => fetchFromWikiServer<{
      total: number;
      withQuotes: number;
      verified: number;
      accuracyChecked: number;
      accurate: number;
      inaccurate: number;
      avgScore: number | null;
    }>(`/api/citations/health/${pageId}`),
    () => {
      const page = getPageById(pageId);
      return page?.citationHealth ?? null;
    }
  );
  return result.data;
}

// ============================================================================
// RISK STATS (pre-aggregated at build time)
// ============================================================================

export interface RiskStats {
  total: number;
  high: number;
  medium: number;
  low: number;
  avgScore: number;
  topFactors: Array<{ factor: string; count: number }>;
}

export async function getRiskStats(): Promise<RiskStats | null> {
  const result = await withApiFallback(
    () => fetchFromWikiServer<RiskStats>(`/api/hallucination-risk/stats`),
    () => getDatabase().riskStats ?? null
  );
  return result.data;
}

export function getResourceCredibility(
  resource: Resource
): number | undefined {
  if (resource.credibility_override !== undefined) return resource.credibility_override;
  if (resource.publication_id) {
    const pub = getPublicationById(resource.publication_id);
    return pub?.credibility;
  }
  return undefined;
}

export function getResourcePublication(
  resource: Resource
): Publication | undefined {
  if (resource.publication_id) {
    return getPublicationById(resource.publication_id);
  }
  return undefined;
}

// ============================================================================
// PATH REGISTRY & ENTITY HREF
// ============================================================================

/**
 * Resolve an ID that may be numeric (E35) or a slug (deepmind) to its slug form.
 * Returns the original ID if it's already a slug or not found in the registry.
 */
export function resolveId(id: string): string {
  if (/^E\d+$/.test(id)) {
    const registry = getIdRegistry();
    return registry.byNumericId[id] || id;
  }
  return id;
}

export function getEntityPath(id: string): string | null {
  const slug = resolveId(id);
  const db = getDatabase();
  return db.pathRegistry?.[slug] || db.pathRegistry?.[`__index__/${slug}`] || null;
}

export function getIdRegistry(): IdRegistryMaps {
  return getDatabase().idRegistry;
}

export function getEntityHref(id: string, _type?: string): string {
  const registry = getIdRegistry();
  // If already a numeric ID (E35), use it directly
  if (/^E\d+$/.test(id) && registry.byNumericId[id]) {
    return `/wiki/${id}`;
  }
  // Otherwise look up slug → numeric ID
  const numericId = registry.bySlug[id];
  return numericId ? `/wiki/${numericId}` : `/wiki/${id}`;
}

// ============================================================================
// BACKLINKS
// ============================================================================

export function getBacklinksFor(
  entityId: string
): Array<{
  id: string;
  type: string;
  title: string;
  href: string;
  relationship?: string;
}> {
  const slug = resolveId(entityId);
  const db = getDatabase();
  const links = db.backlinks?.[slug] || [];
  return links.map((link) => ({
    ...link,
    href: getEntityHref(link.id, link.type),
  }));
}

/** Server response shape for backlinks endpoint */
interface ServerBacklink {
  id: string;
  type: string;
  title: string;
  relationship?: string;
}

/**
 * Fetch backlinks from wiki-server with fallback to local database.json.
 * Adds `href` to each entry (server doesn't include path information).
 */
export async function getBacklinksWithFallback(
  entityId: string
): Promise<WithSource<Array<{
  id: string;
  type: string;
  title: string;
  href: string;
  relationship?: string;
}>>> {
  const slug = resolveId(entityId);

  return withApiFallback(
    async () => {
      const data = await fetchFromWikiServer<{ backlinks: ServerBacklink[] }>(
        `/api/links/backlinks/${encodeURIComponent(slug)}`
      );
      if (!data) return null;
      return data.backlinks.map((link) => ({
        ...link,
        href: getEntityHref(link.id, link.type),
      }));
    },
    () => getBacklinksFor(entityId)
  );
}

// ============================================================================
// RELATED GRAPH (bidirectional, multi-signal)
// ============================================================================

export function getRelatedGraphFor(
  entityId: string
): Array<{
  id: string;
  type: string;
  title: string;
  href: string;
  score: number;
  label?: string;
}> {
  const slug = resolveId(entityId);
  const db = getDatabase();
  const entries = db.relatedGraph?.[slug] || [];
  return entries.map((entry) => ({
    ...entry,
    href: getEntityHref(entry.id, entry.type),
  }));
}

/** Server response shape for related endpoint */
interface ServerRelatedEntry {
  id: string;
  type: string;
  title: string;
  score: number;
  label?: string;
}

/**
 * Fetch related pages from wiki-server with fallback to local database.json.
 * Adds `href` to each entry (server doesn't include path information).
 */
export async function getRelatedGraphWithFallback(
  entityId: string
): Promise<WithSource<Array<{
  id: string;
  type: string;
  title: string;
  href: string;
  score: number;
  label?: string;
}>>> {
  const slug = resolveId(entityId);

  return withApiFallback(
    async () => {
      const data = await fetchFromWikiServer<{ related: ServerRelatedEntry[] }>(
        `/api/links/related/${encodeURIComponent(slug)}`
      );
      if (!data) return null;
      return data.related.map((entry) => ({
        ...entry,
        href: getEntityHref(entry.id, entry.type),
      }));
    },
    () => getRelatedGraphFor(entityId)
  );
}

// ============================================================================
// CANONICAL FACTS
// ============================================================================

export function getFact(entityId: string, factId: string): Fact | undefined {
  const slug = resolveId(entityId);
  const db = getDatabase();
  return db.facts?.[`${slug}.${factId}`];
}

export function getFactValue(entityId: string, factId: string): string | undefined {
  return getFact(entityId, factId)?.value;
}

export function getFactsForEntity(entityId: string): Record<string, Fact> {
  const resolvedId = resolveId(entityId);
  const db = getDatabase();
  const result: Record<string, Fact> = {};
  for (const [key, fact] of Object.entries(db.facts || {})) {
    if (fact.entity === resolvedId) {
      result[fact.factId] = fact;
    }
  }
  return result;
}

// ============================================================================
// SERVER-BACKED FACT FETCH (with local fallback)
// ============================================================================

/** Server response shape for a single fact from /api/facts/by-entity */
interface ServerFact {
  entity: string;
  factId: string;
  value?: string;
  numeric?: number;
  low?: number;
  high?: number;
  asOf?: string;
  label?: string;
  source?: string;
  sourceResource?: string;
  sourceTitle?: string;
  sourcePublication?: string;
  sourceCredibility?: number;
  note?: string;
  noCompute?: boolean;
  measure?: string;
  subject?: string;
  compute?: string;
  format?: string;
  formatDivisor?: number;
  computed?: boolean;
}

function serverFactToFact(sf: ServerFact): Fact {
  return {
    entity: sf.entity,
    factId: sf.factId,
    value: sf.value,
    numeric: sf.numeric,
    low: sf.low,
    high: sf.high,
    asOf: sf.asOf,
    label: sf.label,
    source: sf.source,
    sourceResource: sf.sourceResource,
    sourceTitle: sf.sourceTitle,
    sourcePublication: sf.sourcePublication,
    sourceCredibility: sf.sourceCredibility,
    note: sf.note,
    noCompute: sf.noCompute,
    measure: sf.measure,
    subject: sf.subject,
    compute: sf.compute,
    format: sf.format,
    formatDivisor: sf.formatDivisor,
    computed: sf.computed,
  };
}

/**
 * Fetch all facts for an entity from wiki-server with fallback to local database.json.
 * Follows the same withApiFallback pattern as getRelatedGraphWithFallback/getBacklinksWithFallback.
 */
export async function getFactsForEntityWithFallback(
  entityId: string
): Promise<WithSource<Record<string, Fact>>> {
  return withApiFallback(
    async () => {
      const data = await fetchFromWikiServer<{ facts: ServerFact[] }>(
        `/api/facts/by-entity/${encodeURIComponent(entityId)}`
      );
      if (!data) return null;
      const result: Record<string, Fact> = {};
      for (const sf of data.facts) {
        result[sf.factId] = serverFactToFact(sf);
      }
      return result;
    },
    () => getFactsForEntity(entityId)
  );
}

/**
 * Fetch a single fact from wiki-server with fallback to local database.json.
 * Uses getFactsForEntityWithFallback internally (one request per entity).
 */
export async function getFactWithFallback(
  entityId: string,
  factId: string
): Promise<Fact | undefined> {
  const result = await getFactsForEntityWithFallback(entityId);
  return result.data[factId];
}

export function getAllFacts(): Array<Fact & { key: string }> {
  const db = getDatabase();
  return Object.entries(db.facts || {}).map(([key, fact]) => ({
    ...fact,
    key,
  }));
}

// ============================================================================
// FACT MEASURES & TIMESERIES
// ============================================================================

/** Get all measure definitions */
export function getFactMeasures(): Record<string, FactMeasure> {
  return getDatabase().factMeasures || {};
}

/** Get a single measure definition by ID */
export function getFactMeasure(measureId: string): FactMeasure | undefined {
  return getDatabase().factMeasures?.[measureId];
}

/**
 * Get timeseries for a measure, optionally filtered by entity.
 * Returns observations sorted chronologically (oldest first).
 */
export function getMeasureTimeseries(measureId: string, entityId?: string): TimeseriesPoint[] {
  const db = getDatabase();
  const series = db.factTimeseries?.[measureId] || [];
  if (entityId) {
    return series.filter(p => p.entity === entityId);
  }
  return series;
}

/**
 * Get all timeseries data for a given entity, grouped by measure.
 * Returns a map of measureId → sorted observations.
 */
export function getEntityTimeseries(entityId: string): Record<string, TimeseriesPoint[]> {
  const db = getDatabase();
  const result: Record<string, TimeseriesPoint[]> = {};
  for (const [measureId, series] of Object.entries(db.factTimeseries || {})) {
    const filtered = series.filter(p => p.entity === entityId);
    if (filtered.length > 0) {
      result[measureId] = filtered;
    }
  }
  return result;
}

/** Get all measures that have data for a given entity */
export function getEntityMeasures(entityId: string): FactMeasure[] {
  const db = getDatabase();
  const measures: FactMeasure[] = [];
  const seen = new Set<string>();
  for (const [measureId, series] of Object.entries(db.factTimeseries || {})) {
    if (seen.has(measureId)) continue;
    if (series.some(p => p.entity === entityId)) {
      const measure = db.factMeasures?.[measureId];
      if (measure) {
        measures.push(measure);
        seen.add(measureId);
      }
    }
  }
  return measures;
}

// ============================================================================
// SERVER-BACKED TIMESERIES FETCH (with local fallback)
// ============================================================================

/** Server response shape for a timeseries point from /api/facts/timeseries */
interface ServerTimeseriesPoint {
  entity: string;
  factId: string;
  measure: string;
  asOf: string;
  value?: string;
  numeric?: number;
  low?: number;
  high?: number;
  note?: string;
  source?: string;
}

function serverPointToPoint(sp: ServerTimeseriesPoint): TimeseriesPoint {
  return {
    entity: sp.entity,
    factId: sp.factId,
    measure: sp.measure,
    asOf: sp.asOf,
    value: sp.value,
    numeric: sp.numeric,
    low: sp.low,
    high: sp.high,
    note: sp.note,
    source: sp.source,
  };
}

/**
 * Fetch timeseries for a measure from wiki-server, optionally filtered by entity.
 * Falls back to local database.json.
 */
export async function getMeasureTimeseriesWithFallback(
  measureId: string,
  entityId?: string
): Promise<TimeseriesPoint[]> {
  const url = entityId
    ? `/api/facts/timeseries/${encodeURIComponent(entityId)}?measure=${encodeURIComponent(measureId)}`
    : `/api/facts/timeseries?measure=${encodeURIComponent(measureId)}`;

  const result = await withApiFallback(
    async () => {
      const data = await fetchFromWikiServer<{ timeseries: ServerTimeseriesPoint[] }>(url);
      if (!data) return null;
      return data.timeseries.map(serverPointToPoint);
    },
    () => getMeasureTimeseries(measureId, entityId)
  );
  return result.data;
}

/**
 * Fetch all timeseries data for an entity from wiki-server.
 * Returns a map of measureId → sorted observations.
 * Falls back to local database.json.
 */
export async function getEntityTimeseriesWithFallback(
  entityId: string
): Promise<Record<string, TimeseriesPoint[]>> {
  const result = await withApiFallback(
    async () => {
      const data = await fetchFromWikiServer<{ timeseries: ServerTimeseriesPoint[] }>(
        `/api/facts/timeseries/${encodeURIComponent(entityId)}`
      );
      if (!data) return null;
      const grouped: Record<string, TimeseriesPoint[]> = {};
      for (const sp of data.timeseries) {
        if (!grouped[sp.measure]) grouped[sp.measure] = [];
        grouped[sp.measure].push(serverPointToPoint(sp));
      }
      return grouped;
    },
    () => getEntityTimeseries(entityId)
  );
  return result.data;
}

// ============================================================================
// FACT USAGE (reverse index: which pages use each fact)
// ============================================================================

export interface FactUsagePage {
  id: string;
  title: string;
  path: string;
}

/** Get the reverse index of which pages reference each fact via the <F> component.
 *  Returns a map of "entity.factId" → array of pages that use it. */
export function getFactUsage(): Record<string, FactUsagePage[]> {
  return getDatabase().factUsage || {};
}

// ============================================================================
// INTERVENTIONS
// ============================================================================

export function getInterventions(): Intervention[] {
  const db = getDatabase();
  return db.interventions || [];
}

// ============================================================================
// CRUXES
// ============================================================================

let _cruxIndex: Map<string, CruxData> | null = null;

function cruxIndex(): Map<string, CruxData> {
  if (_cruxIndex) return _cruxIndex;
  const db = getDatabase();
  _cruxIndex = new Map((db.cruxes || []).map((c) => [c.id, c]));
  return _cruxIndex;
}

export function getCruxById(id: string): CruxData | undefined {
  return cruxIndex().get(id);
}

export function getCruxes(): CruxData[] {
  const db = getDatabase();
  return db.cruxes || [];
}

export function getCruxesByDomain(domain: string): CruxData[] {
  return getCruxes().filter(
    (c) => c.domain?.toLowerCase() === domain.toLowerCase()
  );
}

// ============================================================================
// PROPOSALS
// ============================================================================

export interface Proposal {
  id: string;
  name: string;
  description?: string;
  sourcePageId?: string;
  domain?: string;
  stance?: string;
  costEstimate?: string;
  evEstimate?: string;
  feasibility?: string;
  honestConcerns?: string;
  status?: string;
  leadOrganizations?: string[];
  relatedProposals?: string[];
}

export function getProposals(): Proposal[] {
  const db = getDatabase();
  return db.proposals || [];
}

// ============================================================================
// PR ITEMS (GitHub pull request metadata)
// ============================================================================

export interface PrItem {
  number: number;
  title: string;
  body: string;
  state: string;
  branch: string;
  author: string;
  createdAt: string;
  updatedAt: string;
  mergedAt: string | null;
  closedAt: string | null;
  labels: string[];
}

export function getPrItems(): PrItem[] {
  const db = getDatabase();
  return db.prItems || [];
}

// ============================================================================
// INSIGHTS
// ============================================================================

/** Build path→title lookup from pages, normalising trailing slashes. */
function getPageTitleMap(): Map<string, string> {
  const db = getDatabase();
  const map = new Map<string, string>();
  for (const page of db.pages || []) {
    map.set(page.path, page.title);
    if (!page.path.endsWith("/")) {
      map.set(page.path + "/", page.title);
    }
  }
  return map;
}

// ============================================================================
// INFOBOX DATA HELPERS
// ============================================================================

export function getEntityInfoBoxData(entityId: string) {
  const entity = getTypedEntityById(entityId);
  if (!entity) return null;

  const resolvedRelatedEntries = entity.relatedEntries?.map((entry) => ({
    id: entry.id,
    type: entry.type,
    title:
      getTypedEntityById(entry.id)?.title ||
      entry.id
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" "),
    href: getEntityHref(entry.id, entry.type),
  }));

  // Resolve likelihood/timeframe to strings
  let likelihoodStr: string | undefined;
  let timeframeStr: string | undefined;
  let category: string | undefined;
  let maturity: string | undefined;
  let relatedSolutions: Array<{ id: string; title: string; type: string; href: string }> | undefined;
  let severity: string | undefined;

  if (isRisk(entity)) {
    severity = entity.severity;
    category = entity.riskCategory;
    maturity = entity.maturity;
    if (entity.likelihood) {
      likelihoodStr =
        typeof entity.likelihood === "string"
          ? entity.likelihood
          : entity.likelihood?.display || entity.likelihood?.level;
    }
    if (entity.timeframe) {
      timeframeStr =
        typeof entity.timeframe === "string"
          ? entity.timeframe
          : entity.timeframe?.display || String(entity.timeframe?.median || "");
    }
    // Find related solutions
    const allEntities = getTypedEntities();
    relatedSolutions = [];
    for (const solution of allEntities) {
      if (
        solution.entityType === "safety-agenda" ||
        solution.entityType === "approach" ||
        solution.entityType === "project"
      ) {
        const linkedRisks =
          solution.relatedEntries?.filter((re) => re.type === "risk") || [];
        if (linkedRisks.some((r) => r.id === entity.id)) {
          relatedSolutions.push({
            id: solution.id,
            title: solution.title,
            type: solution.entityType,
            href: getEntityHref(solution.id, solution.entityType),
          });
        }
      }
    }
  }

  // Person-specific fields
  let affiliation: string | undefined;
  let role: string | undefined;
  let knownFor: string | undefined;

  if (isPerson(entity)) {
    affiliation = entity.affiliation;
    role = entity.role;
    knownFor = entity.knownFor?.join(", ");
  }

  // Organization-specific fields
  let founded: string | undefined;
  let location: string | undefined;
  let headcount: string | undefined;
  let funding: string | undefined;
  let orgType: string | undefined;

  if (isOrganization(entity)) {
    founded = entity.founded;
    location = entity.headquarters;
    headcount = entity.employees;
    funding = entity.funding;
    orgType = entity.orgType;
  }

  // Policy-specific fields
  let introduced: string | undefined;
  let policyStatus: string | undefined;
  let policyAuthor: string | undefined;
  let scope: string | undefined;

  if (isPolicy(entity)) {
    introduced = entity.introduced;
    policyStatus = entity.policyStatus;
    policyAuthor = entity.author;
    scope = entity.scope;
  }

  // Resolve summaryPage to title + href
  let summaryPage: { title: string; href: string } | undefined;
  if (entity.summaryPage) {
    const summaryEntity = getTypedEntityById(entity.summaryPage);
    const summaryPageData = getPageById(entity.summaryPage);
    const summaryTitle =
      summaryEntity?.title ||
      summaryPageData?.title ||
      entity.summaryPage
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");
    summaryPage = {
      title: summaryTitle,
      href: getEntityHref(entity.summaryPage),
    };
  }

  return {
    type: entity.entityType,
    title: entity.title,
    severity,
    likelihood: likelihoodStr,
    timeframe: timeframeStr,
    website: entity.website,
    customFields: entity.customFields,
    relatedTopics: entity.relatedTopics,
    relatedEntries: resolvedRelatedEntries,
    category,
    maturity,
    relatedSolutions,
    summaryPage,
    // Person
    affiliation,
    role,
    knownFor,
    // Organization
    founded,
    location,
    headcount,
    funding,
    orgType,
    // Policy
    introduced,
    policyStatus,
    policyAuthor,
    scope,
    // Overview
    childPages: entity.entityType === "overview"
      ? getChildPagesForOverview(entity.id)
      : undefined,
  };
}

// ============================================================================
// CHILD PAGES (for overview entities)
// ============================================================================

export interface ChildPageEntry {
  id: string;
  title: string;
  type: string;
  href: string;
}

/**
 * Find all entities that reference this overview page via `summaryPage`.
 * Returns them grouped by entity type for display in the InfoBox.
 */
export function getChildPagesForOverview(overviewId: string): ChildPageEntry[] {
  const allEntities = getTypedEntities();
  const children: ChildPageEntry[] = [];

  for (const entity of allEntities) {
    if (entity.summaryPage === overviewId) {
      children.push({
        id: entity.id,
        title: entity.title,
        type: entity.entityType,
        href: getEntityHref(entity.id, entity.entityType),
      });
    }
  }

  // Sort alphabetically by title
  children.sort((a, b) => a.title.localeCompare(b.title));
  return children;
}

// ============================================================================
// EXTERNAL LINKS (loads YAML via fs)
// ============================================================================

export interface ExternalLinksData {
  wikipedia?: string;
  wikidata?: string;
  lesswrong?: string;
  alignmentForum?: string;
  eaForum?: string;
  stampy?: string;
  arbital?: string;
  eightyK?: string;
  grokipedia?: string;
}

let _externalLinksMap: Map<string, ExternalLinksData> | null = null;

function loadExternalLinksMap(): Map<string, ExternalLinksData> {
  if (_externalLinksMap) return _externalLinksMap;

  try {
    const yamlPath = path.join(DATA_DIR, "external-links.yaml");
    const raw = fs.readFileSync(yamlPath, "utf-8");
    const entries = loadYaml<Array<{
      pageId: string;
      links: ExternalLinksData;
    }>>(raw);
    _externalLinksMap = new Map();
    for (const entry of entries) {
      if (entry.pageId && entry.links) {
        _externalLinksMap.set(entry.pageId, entry.links);
      }
    }
    return _externalLinksMap;
  } catch {
    return new Map();
  }
}

export function getExternalLinks(
  pageId: string
): ExternalLinksData | undefined {
  return loadExternalLinksMap().get(resolveId(pageId));
}

// ============================================================================
// EXPLORE PAGE DATA
// ============================================================================

export interface ExploreItem {
  id: string;
  numericId: string;
  title: string;
  type: string;
  description: string | null;
  tags: string[];
  clusters: string[];
  wordCount: number | null;
  quality: number | null;
  readerImportance: number | null;
  researchImportance: number | null;
  tacticalValue: number | null;
  backlinkCount: number | null;
  category: string | null;
  riskCategory: string | null;
  lastUpdated: string | null;
  dateCreated?: string | null;
  contentFormat?: ContentFormat;
  href?: string;
  meta?: string;
  sourceTitle?: string;
  /** Pre-computed blended score for "recommended" sort (build-time) */
  recommendedScore?: number;
}

// Map page categories to entity-like types for display
const CATEGORY_TO_TYPE: Record<string, string> = {
  responses: "approach",
  organizations: "organization",
  people: "person",
  factors: "model",
  "intelligence-paradigms": "capability",
  models: "model",
  scenarios: "model",
  reports: "analysis",
  cruxes: "crux",
  worldviews: "concept",
  risks: "risk",
  forecasting: "model",
  "foundation-models": "capability",
  incidents: "historical",
  other: "concept",
};

// Table items are now derived from pages with contentFormat=table.
// The hardcoded TABLES array has been eliminated — all table pages are
// detected automatically via the contentFormat field in frontmatter.

export function getExploreItems(): ExploreItem[] {
  const db = getDatabase();
  const typedEntities = getTypedEntities();
  const pageMap = new Map((db.pages || []).map((p) => [p.id, p]));
  const entityIds = new Set(typedEntities.map((e) => e.id));

  // Items from typed entities (only those with actual content pages)
  const entityItems: ExploreItem[] = typedEntities.filter((entity) => pageMap.has(entity.id)).map((entity) => {
    const page = pageMap.get(entity.id)!;
    return {
      id: entity.id,
      numericId: entity.numericId || db.idRegistry?.bySlug[entity.id] || entity.id,
      title: entity.title,
      type: page?.contentFormat === "table" ? "table" : page?.contentFormat === "diagram" ? "diagram" : entity.entityType,
      description: page?.llmSummary || page?.description || entity.description || null,
      tags: entity.tags || [],
      clusters: entity.clusters?.length ? entity.clusters : (page?.clusters || []),
      wordCount: page?.wordCount ?? null,
      quality: page?.quality ?? null,
      readerImportance: page?.readerImportance ?? null,
      researchImportance: page?.researchImportance ?? null,
      tacticalValue: page?.tacticalValue ?? null,
      backlinkCount: page?.backlinkCount ?? null,
      category: page?.category ?? null,
      riskCategory: isRisk(entity) ? (entity.riskCategory || null) : null,
      lastUpdated: page?.lastUpdated ?? null,
      dateCreated: page?.dateCreated ?? null,
      contentFormat: page?.contentFormat,
      recommendedScore: page?.recommendedScore,
    };
  });

  // Items from pages that have no entity
  const pageOnlyItems: ExploreItem[] = (db.pages || [])
    .filter((p) => !entityIds.has(p.id))
    .filter((p) => p.title && p.category !== "schema")
    .map((page) => ({
      id: page.id,
      numericId: db.idRegistry?.bySlug[page.id] || page.id,
      title: page.title,
      type: page.contentFormat === "table" ? "table" : page.contentFormat === "diagram" ? "diagram" : CATEGORY_TO_TYPE[page.category] || "concept",
      description: page.llmSummary || page.description || null,
      tags: page.tags || [],
      clusters: page.clusters || [],
      wordCount: page.wordCount ?? null,
      quality: page.quality ?? null,
      readerImportance: page.readerImportance ?? null,
      researchImportance: page.researchImportance ?? null,
      tacticalValue: page.tacticalValue ?? null,
      backlinkCount: page.backlinkCount ?? null,
      category: page.category ?? null,
      riskCategory: null,
      lastUpdated: page.lastUpdated ?? null,
      dateCreated: page.dateCreated ?? null,
      contentFormat: page.contentFormat,
      recommendedScore: page.recommendedScore,
    }));

  // Diagram items — entities with causeEffectGraph data
  // Generic entities preserve all raw fields including causeEffectGraph.
  // Entity IDs may differ from page IDs (e.g. entity "tmc-compute" → page "compute",
  // entity "misalignment-potential" → page "factors-misalignment-potential-overview"),
  // so we resolve the correct page for each diagram entity.
  function resolveDiagramHref(e: AnyEntity): string | null {
    const raw = e as unknown as RawEntity;
    // 1. Direct match: entity ID is the page ID
    if (pageMap.has(e.id)) return getEntityHref(e.id);
    // 2. Entity has explicit path field → derive page ID from path
    if (raw.path) {
      const segments = raw.path.replace(/\/$/, "").split("/");
      const pageId = segments[segments.length - 1];
      if (pageId && pageMap.has(pageId)) {
        const numId = db.idRegistry?.bySlug[pageId];
        return numId ? `/wiki/${numId}` : `/wiki/${pageId}`;
      }
    }
    // 3. Factor entities: try "factors-{id}-overview" pattern
    const overviewId = `factors-${e.id}-overview`;
    if (pageMap.has(overviewId)) {
      const numId = db.idRegistry?.bySlug[overviewId];
      return numId ? `/wiki/${numId}` : `/wiki/${overviewId}`;
    }
    return null;
  }

  const diagramItems: ExploreItem[] = typedEntities
    .filter((e) => {
      const ceg = (e as unknown as RawEntity).causeEffectGraph;
      if (!ceg?.nodes?.length) return false;
      // Only include diagrams that resolve to a valid page
      return resolveDiagramHref(e) !== null;
    })
    .map((e) => {
      const ceg = (e as unknown as RawEntity).causeEffectGraph!;
      const nodeCount = ceg.nodes?.length || 0;
      return {
        id: `diagram-${e.id}`,
        numericId: `diagram-${e.id}`,
        title: ceg.title || e.title,
        type: "diagram",
        description: ceg.description || `Cause-effect diagram for ${e.title}`,
        tags: [] as string[],
        clusters: ["ai-safety"],
        wordCount: null,
        quality: null,
        readerImportance: null,
        researchImportance: null,
        tacticalValue: null,
        backlinkCount: null,
        category: null,
        riskCategory: null,
        lastUpdated: e.lastUpdated || null,
        dateCreated: null,
        contentFormat: "diagram" as ContentFormat,
        href: resolveDiagramHref(e)!,
        meta: `${nodeCount} nodes`,
      };
    });

  return [...entityItems, ...pageOnlyItems, ...diagramItems];
}
