/**
 * TableBase — Core data layer: types, database loading, and basic entity lookups.
 *
 * This module is the "TableBase" layer of the wiki's Three Bases architecture:
 *   - **TableBase** (this file): Typed relational records — entities, resources,
 *     publications, experts. Source of truth: YAML files in data/entities/, data/resources/.
 *   - **FactBase** (factbase.ts): Structured triples with temporal data and provenance.
 *     Source of truth: YAML files in packages/factbase/data/fb-entities/.
 *   - **WikiBase**: Long-form prose MDX articles (content/docs/).
 *     Represented here as the `Page` interface.
 *
 * Reads database.json (generated by scripts/build-data.mjs) which contains
 * pre-transformed typedEntities. Runs at build time / server-component level only.
 *
 * This module is the foundation for all other data modules.
 * Consumers should import from "@/data" (index.ts) for backward compatibility.
 *
 * See: content/docs/internal/data-architecture.mdx for the full naming guide.
 */

import fs from "fs";
import path from "path";
import { loadYaml } from "@lib/yaml";
import { fetchFromWikiServer, withApiFallback, type WithSource } from "@lib/wiki-server";
import {
  TypedEntitySchema,
  GenericEntityPassthroughSchema,
  type TypedEntity,
  type GenericEntity,
  type PersonEntity,
  isRisk,
  isPerson,
  isOrganization,
  isPolicy,
} from "./entity-schemas";
import type { ValidSubcategory } from "./valid-subcategories";
import { isSid, isAnySid, SID_PREFIX } from "@/lib/stable-id";
import { extractDomain } from "@/lib/resource-types";
import { isCandidateRecordId } from "@wiki-server/api-types";
import {
  SOURCE_CHECK_VERDICT_PRIORITY,
  type SourcingVerdictType,
} from "@/components/shared/verdict-styles";

// Re-export for consumers
export type { WithSource };

// database.json is generated here by prebuild
const LOCAL_DATA_DIR = path.resolve(process.cwd(), "src/data");

// Source YAML data lives at the repo root
export const DATA_DIR = path.resolve(process.cwd(), "../../data");

// ============================================================================
// CORE TYPES
// ============================================================================

export interface IdRegistryMaps {
  byWikiId: Record<string, string>; // E1 → slug
  bySlug: Record<string, string>; // slug → E1
  stableIdToSlug?: Record<string, string>; // 10-char stableId → slug (from YAML entities)
  byStableId?: Record<string, string>; // stableId → slug (optional for backward compat)
  stableIdBySlug?: Record<string, string>; // slug → stableId (optional for backward compat)
}

/**
 * Legacy Fact interface — kept as a bridge type for calc-engine and
 * AnthropicStakeholdersTable. The old facts pipeline has been retired;
 * database.facts is always empty. New code should use KB data instead.
 */
export interface Fact {
  value?: string;
  numeric?: number;
  low?: number;
  high?: number;
  asOf?: string;
  label?: string;
  source?: string;
  sourceTitle?: string;
  sourcePublication?: string;
  sourceCredibility?: number;
  note?: string;
  entity: string;
  factId: string;
}

/** Raw entity shape as stored in database.json (before transformation) */
export interface RawEntity {
  id: string;
  stableId?: string;
  type: string;
  title: string;
  description?: string;
  severity?: string;
  likelihood?: string | { level: string; status?: string; display?: string };
  timeframe?: string | { median: number; earliest?: number; latest?: number; display?: string };
  maturity?: string;
  website?: string;
  customFields?: { label: string; value: string; link?: string }[];
  relatedTopics?: string[];
  relatedEntries?: { id: string; type: string; relationship?: string }[];
  aliases?: string[];
  tags?: string[];
  lastUpdated?: string;
  sourceRefs?: string[];
  sources?: { title: string; url?: string; author?: string; date?: string }[];
  content?: unknown;
  wikiId?: string;
  path?: string;
  status?: string;
  clusters?: string[];
  causeEffectGraph?: {
    title?: string;
    description?: string;
    nodes?: { id: string; [k: string]: unknown }[];
  };
}

interface RelatedGraphEntry {
  id: string;
  type: string;
  title: string;
  score: number;
  label?: string;
}

export interface BacklinkEntry {
  id: string;
  type: string;
  title: string;
  relationship?: string;
}

export type ContentFormat = 'article' | 'table' | 'diagram' | 'index' | 'dashboard';

export interface ChangeEntry {
  date: string;
  branch: string;
  title: string;
  summary: string;
  pr?: number;
  model?: string;
  duration?: string;
  cost?: string;
}

/** Serialized claim reference data stored in database.json */
interface SerializedClaimRef {
  claimId: number;
  claimText: string;
  sourceUrl?: string;
  sourceTitle?: string;
  verdict?: string;
  verdictScore?: number;
  referenceId: string;
}

/** Serialized citation data stored in database.json */
interface SerializedCitation {
  title?: string;
  url?: string;
  note?: string;
  resourceId?: string;
  referenceId: string;
}

/** Per-page reference data stored in database.json */
export interface SerializedPageReferences {
  claimReferences: SerializedClaimRef[];
  citations: SerializedCitation[];
}

export interface Resource {
  id: string;
  url: string;
  title: string;
  authors?: string[];
  published_date?: string;
  type: string;
  local_filename?: string;
  abstract?: string;
  summary?: string;
  review?: string;
  key_points?: string[];
  cited_by?: string[] | null;
  fetched_at?: string;
  tags?: string[];
  publication_id?: string;
  credibility_override?: number;
  stable_id?: string;
  /** HTTP reachability: ok | dead | soft_404 | not_found | timeout | unreachable | paywall | error.
   *  Distinct from enrichment_status (LLM pipeline stage). */
  fetch_status?: string;
  archive_url?: string;
  author_entity_ids?: string[];
  stance?: string;
  // Enrichment fields
  context_note?: string;
  resource_purpose?: string;
  resource_subtype?: string;
  type_metadata?: Record<string, unknown>;
  publisher_entity_id?: string;
  related_entity_ids?: string[];
  /** LLM enrichment pipeline stage: pending | fetched | classified | enriched | reviewed.
   *  Distinct from fetch_status (HTTP reachability). */
  enrichment_status?: string;
  importance_score?: number;
  content_hash?: string;
  // Sub-table data
  paper?: ResourcePaper;
  forum_post?: ResourceForumPost;
  policy_doc?: ResourcePolicyDoc;
}

export interface ResourcePaper {
  arxiv_id?: string;
  doi?: string;
  semantic_scholar_id?: string;
  abstract?: string;
  citation_count?: number;
  influential_citation_count?: number;
  categories?: string[];
  methodology?: string;
  year?: number;
}

export interface ResourceForumPost {
  forum: string;
  forum_post_id?: string;
  forum_slug?: string;
  karma?: number;
  comment_count?: number;
  author_username?: string;
  forum_tags?: string[];
  sequence_title?: string;
  curated?: boolean;
  cross_posted_from?: string;
  canonical_forum?: string;
}

export interface ResourcePolicyDoc {
  document_type?: string;
  jurisdiction_entity_id?: string;
  agency_entity_id?: string;
  policy_entity_id?: string;
  effective_date?: string;
  document_status?: string;
  reference_number?: string;
}

export interface Publication {
  id: string;
  name: string;
  type: string;
  credibility: number;
  peer_reviewed?: boolean;
  domains: string[];
  description?: string;
  credibility_rationale?: string;
  website?: string;
}

export interface Organization {
  id: string;
  name: string;
  type: string;
  founded?: string;
  headquarters?: string;
  website?: string;
  funding?: string;
  employees?: string;
}

/** WikiBase: a long-form prose wiki page (MDX article). */
export interface Page {
  id: string;
  path: string;
  filePath: string;
  title: string;
  quality: number | null;
  readerImportance: number | null;
  researchImportance: number | null;
  tacticalValue: number | null;
  contentFormat: ContentFormat;
  causalLevel: string | null;
  lastUpdated: string | null;
  dateCreated?: string | null;
  summary: string | null;
  description: string | null;
  ratings: {
    novelty?: number;
    rigor?: number;
    actionability?: number;
    completeness?: number;
  } | null;
  category: string;
  subcategory?: ValidSubcategory | null;
  tags?: string[];
  clusters?: string[];
  updateFrequency?: number | null;
  evergreen?: boolean;
  changeHistory?: ChangeEntry[];
  wordCount?: number;
  backlinkCount?: number;
  metrics?: {
    wordCount: number;
    tableCount: number;
    diagramCount: number;
    internalLinks: number;
    externalLinks: number;
    footnoteCount: number;
    bulletRatio: number;
    sectionCount: number;
    hasOverview: boolean;
    structuralScore: number;
  };
  suggestedQuality?: number;
  unconvertedLinkCount?: number;
  redundancy?: {
    maxSimilarity: number;
    similarPages: Array<{
      id: string;
      title: string;
      path: string;
      similarity: number;
    }>;
  };
  /** Resolved canonical entity type (e.g. 'person', 'organization', 'risk') */
  entityType?: string;
  /** Citation health stats from wiki-server (attached at build time) */
  citationHealth?: {
    total: number;
    withQuotes: number;
    verified: number;
    accuracyChecked: number;
    accurate: number;
    inaccurate: number;
    avgScore: number | null;
  };
  /** Computed hallucination risk — used by UI banners and AI agent triage */
  hallucinationRisk?: {
    /** Risk bucket: 'low' | 'medium' | 'high' */
    level: "low" | "medium" | "high";
    /** Numeric score 0-100 (higher = riskier) */
    score: number;
    /** Machine-readable factors explaining the score */
    factors: string[];
  };
  /** Pre-computed page coverage (structural completeness) from build-data */
  coverage?: {
    passing: number;
    total: number;
    targets: {
      tables: number;
      diagrams: number;
      internalLinks: number;
      externalLinks: number;
      footnotes: number;
      references: number;
    };
    actuals?: {
      tables: number;
      diagrams: number;
      internalLinks: number;
      externalLinks: number;
      footnotes: number;
      references: number;
      quotesWithQuotes: number;
      quotesTotal: number;
      accuracyChecked: number;
      accuracyTotal: number;
    };
    items: Record<string, "green" | "amber" | "red">;
    editHistoryCount?: number;
    ratingsString?: string;
  };
  /** Pre-computed reader importance rank (1 = most important) */
  readerRank?: number;
  /** Pre-computed research importance rank (1 = most important) */
  researchRank?: number;
  /** Pre-computed blended "recommended" score for ExploreGrid default sort */
  recommendedScore?: number;
}

/** TableBase: typed relational records (Postgres/YAML entities). */
interface TableBaseShape {
  typedEntities?: Array<Record<string, unknown>>;
  publications: Publication[];
  organizations: Organization[];
  pathRegistry: Record<string, string>;
  idRegistry: IdRegistryMaps;
  pages: Page[];
  /** Page → resource IDs mapping (computed at build time from inline <R>, cited_by, URL matching) */
  pageResources: Record<string, string[]>;
  stats: Record<string, unknown>;
  /** Pre-aggregated hallucination risk statistics */
  riskStats?: {
    total: number;
    high: number;
    medium: number;
    low: number;
    avgScore: number;
    topFactors: Array<{ factor: string; count: number }>;
  };
  /** Policy stakeholder PG IDs, keyed by "policyEntityStableId:stakeholderDisplayName" -> stakeholder 10-char ID.
   *  Used to look up sourcing verdicts for stakeholder rows on legislation pages. */
  policyStakeholderIds?: Record<string, string>;
  /** Entity→resource relationship links from entity_resources table */
  entityResourceLinks?: Record<string, { authored: string[]; subject: string[] }>;
}

// ============================================================================
// PER-ENTITY BUNDLE (loaded from generated/entities/<id>.json)
// ============================================================================

/**
 * Per-entity JSON bundle generated by build-data.mjs.
 * Contains all the data needed to render a single entity's wiki page,
 * avoiding the need to load the full database.json.
 */
export interface EntityBundle {
  entity?: Record<string, unknown>;
  page?: Page;
  backlinks?: BacklinkEntry[];
  relatedGraph?: RelatedGraphEntry[];
  citationQuotes?: Array<Record<string, unknown>>;
  pageReferences?: SerializedPageReferences;
  pageResources?: string[];
}

const GENERATED_ENTITY_DIR = path.resolve(process.cwd(), "src/data/generated/entities");

/** In-memory cache for per-entity bundles (Map<entityId, bundle | null>) */
const _entityBundleCache = new Map<string, EntityBundle | null>();

/**
 * Load a per-entity JSON bundle from generated/entities/<id>.json.
 * Returns null if the file doesn't exist (entity may not have been bundled).
 * Results are cached in memory for the lifetime of the process.
 */
export function getEntityBundle(entityId: string): EntityBundle | null {
  if (!entityId) return null;
  const slug = resolveIdWithoutRegistry(entityId);

  if (_entityBundleCache.has(slug)) {
    return _entityBundleCache.get(slug)!;
  }

  // Sanitize slug for filename (some IDs contain path separators)
  const safeFilename = slug.replace(/\//g, "__");
  const bundlePath = path.join(GENERATED_ENTITY_DIR, `${safeFilename}.json`);
  try {
    const raw = fs.readFileSync(bundlePath, "utf-8");
    const bundle = JSON.parse(raw) as EntityBundle;
    _entityBundleCache.set(slug, bundle);
    return bundle;
  } catch {
    _entityBundleCache.set(slug, null);
    return null;
  }
}

/**
 * Resolve a wiki ID (E35) or stableId (both sid_-prefixed and legacy 10-char) to slug
 * without loading the full database. Falls back to the full registry if needed,
 * but tries the lightweight approach first.
 */
function resolveIdWithoutRegistry(id: string): string {
  // Wiki ID: E35 → slug
  if (/^E\d+$/.test(id)) {
    const registry = getIdRegistry();
    return registry.byWikiId[id] || id;
  }
  // StableId: sid_-prefixed → slug
  if (isSid(id)) {
    const registry = getIdRegistry();
    return registry.byStableId?.[id] || id;
  }
  return id;
}

// ============================================================================
// DATABASE LOADING
// ============================================================================

/** Union of fully-typed entities and generic (unknown-type) entities */
export type AnyEntity = TypedEntity | GenericEntity;

let _database: TableBaseShape | null = null;
let _typedEntities: AnyEntity[] | null = null;

export function getTableBase(): TableBaseShape {
  if (_database) return _database;

  const dbPath = path.join(LOCAL_DATA_DIR, "database.json");

  try {
    const raw = fs.readFileSync(dbPath, "utf-8");
    _database = JSON.parse(raw) as TableBaseShape;
  } catch (err) {
    throw new Error(
      `Failed to load database from ${dbPath}: ${err instanceof Error ? err.message : err}. ` +
      `Run "pnpm prebuild" first.`
    );
  }
  return _database;
}

/** Get all typed entities from the database */
export function getTypedEntities(): AnyEntity[] {
  if (_typedEntities) return _typedEntities;

  const db = getTableBase();

  if (!db.typedEntities || db.typedEntities.length === 0) {
    throw new Error(
      'database.json is missing typedEntities. ' +
      'Run "pnpm --filter longterm-next prebuild" to rebuild.'
    );
  }

  const entities: AnyEntity[] = [];
  const isDev = process.env.NODE_ENV === "development";

  for (const raw of db.typedEntities) {
    const result = TypedEntitySchema.safeParse(raw);
    if (result.success) {
      entities.push(result.data);
      continue;
    }

    if (isDev) {
      const rawRecord = raw as Record<string, unknown>;
      const id = typeof rawRecord.id === "string" ? rawRecord.id : "<unknown>";
      const type = typeof rawRecord.entityType === "string" ? rawRecord.entityType : "<unknown>";
      console.warn(
        `[entity-validation] ${id} (${type}): ${result.error.issues.map(i => i.message).join(", ")}`
      );
    }

    // GenericEntityPassthroughSchema preserves unknown keys
    // (causeEffectGraph, content, currentAssessment, etc.).
    const genericResult = GenericEntityPassthroughSchema.safeParse(raw);
    if (genericResult.success) {
      entities.push(genericResult.data as GenericEntity);
      continue;
    }
    if (isDev) {
      const rawRecord = raw as Record<string, unknown>;
      const id = typeof rawRecord.id === "string" ? rawRecord.id : "<unknown>";
      console.warn(`[entity-validation] ${id}: failed generic parse too — skipping`);
    }
  }

  _typedEntities = entities;
  return _typedEntities;
}

// ============================================================================
// TYPES (re-exported for consumers)
// ============================================================================

export type { TypedEntity, GenericEntity, RiskEntity, PersonEntity, OrganizationEntity, PolicyEntity, AiModelEntity, BenchmarkEntity, ProjectEntity, ApproachEntity, EventEntity, ExpertPosition } from "./entity-schemas";
export { isRisk, isPerson, isOrganization, isPolicy, isAiModel, isBenchmark, isProject, isApproach, isEvent } from "./entity-schemas";

// ============================================================================
// ID RESOLUTION
// ============================================================================

/**
 * Resolve an ID that may be numeric (E35), a stableId (sid_-prefixed or legacy 10-char),
 * or a slug (deepmind) to its slug form.
 * Returns the original ID if it's already a slug or not found in the registry.
 */
export function resolveId(id: string): string {
  // Wiki ID: E35 → slug
  if (/^E\d+$/.test(id)) {
    const registry = getIdRegistry();
    return registry.byWikiId[id] || id;
  }
  // StableId: sid_-prefixed → slug
  if (isSid(id)) {
    const registry = getIdRegistry();
    return registry.byStableId?.[id] || id;
  }
  return id;
}

export function getIdRegistry(): IdRegistryMaps {
  return getTableBase().idRegistry;
}

// ============================================================================
// LOOKUP INDEXES (built lazily)
// ============================================================================

let _typedEntityIndex: Map<string, AnyEntity> | null = null;
let _entityStableIdIndex: Map<string, AnyEntity> | null = null;
let _resourceIndex: Map<string, Resource> | null = null;
let _stableIdIndex: Map<string, Resource> | null = null;
let _publicationIndex: Map<string, Publication> | null = null;
let _pageIndex: Map<string, Page> | null = null;

function typedEntityIndex() {
  if (!_typedEntityIndex) {
    _typedEntityIndex = new Map(getTypedEntities().map(e => [e.id, e]));
  }
  return _typedEntityIndex;
}

/** Lazy index: entity.stableId → entity. Covers all typed entities. */
function entityStableIdIndex(): Map<string, AnyEntity> {
  if (!_entityStableIdIndex) {
    _entityStableIdIndex = new Map();
    for (const e of getTypedEntities()) {
      if (e.stableId) {
        _entityStableIdIndex.set(e.stableId, e);
      }
    }
  }
  return _entityStableIdIndex;
}

/**
 * Get a typed entity by stableId.
 * Handles both sid_-prefixed IDs (e.g. "sid_fVMqY7vpMA") and legacy bare IDs
 * (e.g. "fVMqY7vpMA") — the latter appear in source_check_verdicts.entityId.
 */
export function getTypedEntityByStableId(stableId: string): AnyEntity | undefined {
  const registry = getIdRegistry();
  const slug = registry.byStableId?.[stableId];
  if (slug) {
    const entity = typedEntityIndex().get(slug);
    if (entity) return entity;
  }
  // Fallback: scan entities by their stableId field
  const byIndex = entityStableIdIndex().get(stableId);
  if (byIndex) return byIndex;

  // If the ID is a bare 10-char ID (no sid_ prefix), try with the prefix.
  // source_check_verdicts.entityId often stores bare IDs while entities use sid_ prefix.
  if (!isSid(stableId) && isAnySid(stableId)) {
    const prefixed = `${SID_PREFIX}${stableId}`;
    const slugP = registry.byStableId?.[prefixed];
    if (slugP) {
      const entity = typedEntityIndex().get(slugP);
      if (entity) return entity;
    }
    return entityStableIdIndex().get(prefixed);
  }

  return undefined;
}

function loadResources(): Resource[] {
  // Resources are in a separate file (split from database.json for size)
  const resourcesPath = path.join(LOCAL_DATA_DIR, "resources.json");
  try {
    return JSON.parse(fs.readFileSync(resourcesPath, "utf-8"));
  } catch {
    // Fallback to database.json if separate file doesn't exist (backward compat)
    const db = getTableBase();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- backward compat: resources was removed from TableBaseShape
    return ((db as any).resources as Resource[]) || [];
  }
}

function resourceIndex() {
  if (!_resourceIndex) {
    const resources = loadResources();
    _resourceIndex = new Map();
    _stableIdIndex = new Map();
    for (const r of resources) {
      _resourceIndex.set(r.id, r);
      if (r.stable_id) {
        const existing = _stableIdIndex.get(r.stable_id);
        if (existing && existing.id !== r.id) {
          throw new Error(
            `Duplicate resource stable_id "${r.stable_id}" for "${existing.id}" and "${r.id}"`
          );
        }
        _stableIdIndex.set(r.stable_id, r);
      }
    }
  }
  return _resourceIndex;
}

function stableIdIndex() {
  if (!_stableIdIndex) resourceIndex(); // builds both indexes
  return _stableIdIndex!;
}

function publicationIndex() {
  if (!_publicationIndex) {
    const db = getTableBase();
    _publicationIndex = new Map(
      (db.publications || []).map((p) => [p.id, p])
    );
  }
  return _publicationIndex;
}

function pageIndex() {
  if (!_pageIndex) {
    const db = getTableBase();
    _pageIndex = new Map((db.pages || []).map((p) => [p.id, p]));
  }
  return _pageIndex;
}

// ============================================================================
// LOOKUP FUNCTIONS
// ============================================================================

/** Get a typed entity by ID — accepts numeric (E35) or slug (deepmind) */
export function getTypedEntityById(id: string): AnyEntity | undefined {
  return typedEntityIndex().get(resolveId(id));
}

/** Get a person entity by ID, or null if not found / not a person */
export function getPersonEntityById(id: string): PersonEntity | null {
  const entity = getTypedEntityById(id);
  return entity && isPerson(entity) ? entity : null;
}

export function getResourceById(id: string): Resource | undefined {
  return resourceIndex().get(id);
}

/**
 * Resolve a resource by hash ID or stable_id.
 * Tries hash ID first (16-char hex), then stable_id (10-char alphanumeric).
 */
export function resolveResource(id: string): Resource | undefined {
  return resourceIndex().get(id) ?? stableIdIndex().get(id);
}

let _allResources: Resource[] | null = null;

/** Get all resources (loaded from separate resources.json) */
export function getAllResources(): Resource[] {
  if (_allResources) return _allResources;
  _allResources = loadResources();
  return _allResources;
}

/** Get resource IDs for a page (computed at build time from inline <R>, cited_by, URL matching) */
export function getResourcesForPage(pageId: string): string[] {
  const slug = resolveId(pageId);
  // Try per-entity bundle first (avoids loading full database.json)
  const bundle = getEntityBundle(slug);
  if (bundle?.pageResources) return bundle.pageResources;
  const db = getTableBase();
  return db.pageResources?.[slug] ?? [];
}

/** Get page IDs that cite a given resource (reverse lookup of pageResources) */
export function getPagesForResource(resourceId: string): string[] {
  const db = getTableBase();
  const pr = db.pageResources ?? {};
  const pages: string[] = [];
  for (const [pageId, ids] of Object.entries(pr)) {
    if ((ids as string[]).includes(resourceId)) {
      pages.push(pageId);
    }
  }
  return pages;
}

/** Get DB-driven reference data for a page (for the reference preprocessor).
 * Reads from per-entity bundle only — no longer in main database.json. */
export function getPageReferences(pageId: string): SerializedPageReferences | null {
  const slug = resolveId(pageId);
  const bundle = getEntityBundle(slug);
  return bundle?.pageReferences ?? null;
}

export function getPublicationById(id: string): Publication | undefined {
  return publicationIndex().get(id);
}

/** Get entity_resources links for a given entity stableId, or null if not populated */
export function getEntityResourceLinks(
  stableId: string,
): { authored: string[]; subject: string[] } | null {
  const db = getTableBase();
  return db.entityResourceLinks?.[stableId] ?? null;
}

/** Get all publications */
export function getAllPublications(): Publication[] {
  const db = getTableBase();
  return db.publications ?? [];
}

/** Get resources that belong to a publication */
export function getResourcesForPublication(publicationId: string): Resource[] {
  return getAllResources().filter((r) => r.publication_id === publicationId);
}

export function getPageById(id: string): Page | undefined {
  const slug = resolveId(id);
  // Try per-entity bundle first (avoids loading full database for single-page lookups)
  const bundle = getEntityBundle(slug);
  if (bundle?.page) return bundle.page;
  return pageIndex().get(slug);
}

export function getAllPages(): Page[] {
  return getTableBase().pages || [];
}

// ============================================================================
// RESOURCE HELPERS
// ============================================================================

/** Lazily-built map from domain → publication (includes subdomain matching). */
let _domainToPublication: Map<string, Publication> | null = null;

function domainToPublicationIndex(): Map<string, Publication> {
  if (!_domainToPublication) {
    _domainToPublication = new Map();
    for (const pub of getAllPublications()) {
      for (const domain of pub.domains) {
        // Store the exact domain (lowercased, www-stripped) for lookup
        const normalized = domain.toLowerCase().replace(/^www\./, "");
        _domainToPublication.set(normalized, pub);
      }
    }
  }
  return _domainToPublication;
}

/**
 * Look up a publication by resource domain.
 * Handles subdomain matching: a publication with domain "nytimes.com"
 * matches "www.nytimes.com" and "cooking.nytimes.com" too.
 */
export function getPublicationByDomain(domain: string): Publication | undefined {
  if (!domain) return undefined;
  const idx = domainToPublicationIndex();
  const normalized = domain.toLowerCase().replace(/^www\./, "");

  // Exact match first
  const exact = idx.get(normalized);
  if (exact) return exact;

  // Subdomain match: check if the resource domain ends with ".{pubDomain}"
  for (const [pubDomain, pub] of idx) {
    if (normalized.endsWith(`.${pubDomain}`)) {
      return pub;
    }
  }
  return undefined;
}

export function getResourceCredibility(
  resource: Resource
): number | undefined {
  if (resource.credibility_override !== undefined) return resource.credibility_override;
  if (resource.publication_id) {
    const pub = getPublicationById(resource.publication_id);
    if (pub?.credibility !== undefined) return pub.credibility;
  }
  const domain = extractDomain(resource.url);
  if (domain) {
    const domainPub = getPublicationByDomain(domain);
    if (domainPub?.credibility !== undefined) return domainPub.credibility;
  }
  return undefined;
}

export function getResourcePublication(
  resource: Resource
): Publication | undefined {
  if (resource.publication_id) {
    const pub = getPublicationById(resource.publication_id);
    if (pub) return pub;
  }
  const domain = extractDomain(resource.url);
  if (domain) {
    return getPublicationByDomain(domain);
  }
  return undefined;
}

// ============================================================================
// PERSON NAME LOOKUP
// ============================================================================

let _personNameIndex: Map<string, string> | null = null;

/**
 * Build a lazily-cached index of person name → entity ID.
 * Normalizes to lowercase for case-insensitive matching.
 */
function personNameIndex(): Map<string, string> {
  if (!_personNameIndex) {
    _personNameIndex = new Map();
    for (const entity of getTypedEntities()) {
      if (isPerson(entity)) {
        _personNameIndex.set(entity.title.toLowerCase(), entity.id);
      }
    }
  }
  return _personNameIndex;
}

/**
 * Find a person entity by name (case-insensitive).
 * Returns the entity ID if a matching person is found, undefined otherwise.
 */
export function findPersonByName(name: string): string | undefined {
  return personNameIndex().get(name.toLowerCase());
}

// ============================================================================
// BENCHMARK RESULTS
// ============================================================================

interface PGBenchmarkResult {
  benchmarkId: string;
  score: number;
  unit: string | null;
  date: string | null;
  sourceUrl: string | null;
  testedBy: string | null;
  testedByOrgId: string | null;
  evaluationDate: string | null;
  methodologyNotes: string | null;
}

let _benchmarkResults: Record<string, PGBenchmarkResult[]> | null = null;

/** Get all PG benchmark results keyed by model ID.
 * Loaded from a separate benchmark-results.json (split from database.json). */
export function getBenchmarkResults(): Record<string, PGBenchmarkResult[]> {
  if (_benchmarkResults) return _benchmarkResults;
  const filePath = path.join(LOCAL_DATA_DIR, "benchmark-results.json");
  try {
    _benchmarkResults = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    return _benchmarkResults!;
  } catch {
    _benchmarkResults = {};
    return _benchmarkResults;
  }
}

/** Get PG benchmark results for a specific model. Returns empty array if none. */
export function getBenchmarkResultsByModel(modelId: string): PGBenchmarkResult[] {
  return getBenchmarkResults()[modelId] ?? [];
}

// ============================================================================
// RESEARCH AREAS
// ============================================================================

interface PGResearchArea {
  id: string;
  wikiId: string | null;
  title: string;
  description: string | null;
  status: string;
  cluster: string | null;
  parentAreaId: string | null;
  firstProposed: string | null;
  firstProposedYear: number | null;
  tags: string[];
  metadata: Record<string, unknown>;
  source: string | null;
  notes: string | null;
  orgCount: number;
  paperCount: number;
  grantCount: number;
  totalFunding: string;
  riskCount: number;
}

let _researchAreas: PGResearchArea[] | null = null;

function loadResearchAreas(): PGResearchArea[] {
  if (_researchAreas) return _researchAreas;
  const filePath = path.join(LOCAL_DATA_DIR, "research-areas.json");
  try {
    _researchAreas = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    return _researchAreas!;
  } catch {
    _researchAreas = [];
    return _researchAreas;
  }
}

/**
 * Get enriched research areas from PG.
 * Loaded from a separate research-areas.json (split from database.json).
 *
 * By default, excludes empty stub areas (0 orgs AND 0 papers) since they add
 * noise to the directory without providing browseable content. Pass
 * `includeEmpty: true` to get all areas (e.g., for internal dashboards).
 */
export function getResearchAreasFromPG(
  options: { includeEmpty?: boolean } = {},
): PGResearchArea[] {
  const all = loadResearchAreas();
  if (options.includeEmpty) return all;
  return all.filter((a) => a.orgCount > 0 || a.paperCount > 0);
}

// ============================================================================
// RESEARCH AREA DETAILS
// Entity lists (orgs, papers, grants) for research area detail pages.
// Loaded from research-area-details.json (built from wiki-server at build time).
// ============================================================================

interface ResearchAreaDetailOrg {
  organizationId: string;
  role: string;
  notes: string | null;
}

interface ResearchAreaDetailPaper {
  id: number;
  resourceId: string | null;
  title: string;
  url: string | null;
  authors: string | null;
  publishedDate: string | null;
  citationCount: number | null;
  isSeminal: boolean;
  sortOrder: number;
  notes: string | null;
}

interface ResearchAreaDetailGrant {
  id: string;
  name: string;
  amount: number | null;
  date: string | null;
  organizationId: string;
  granteeId: string | null;
  confidence: number | null;
}

interface ResearchAreaDetailFundingByOrg {
  organizationId: string;
  grantCount: number;
  totalAmount: string;
}

export interface ResearchAreaDetail {
  organizations: ResearchAreaDetailOrg[];
  papers: ResearchAreaDetailPaper[];
  grants: ResearchAreaDetailGrant[];
  fundingByOrg: ResearchAreaDetailFundingByOrg[];
}

let _researchAreaDetails: Record<string, ResearchAreaDetail> | null = null;

function loadResearchAreaDetails(): Record<string, ResearchAreaDetail> {
  if (_researchAreaDetails) return _researchAreaDetails;
  const filePath = path.join(LOCAL_DATA_DIR, "research-area-details.json");
  try {
    _researchAreaDetails = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    return _researchAreaDetails!;
  } catch {
    _researchAreaDetails = {};
    return _researchAreaDetails;
  }
}

/** Get detail data (orgs, papers, grants) for a research area by ID. */
export function getResearchAreaDetail(areaId: string): ResearchAreaDetail | null {
  return loadResearchAreaDetails()[areaId] ?? null;
}

// ============================================================================
// RECORD VERDICTS
// Used by SourcingBadge on organization, grant, and funding-round detail pages.
// ============================================================================

export interface RecordVerdict {
  verdict: string;
  confidence: number | null;
  sourcesChecked: number;
  needsRecheck: boolean;
  lastComputedAt: string | null;
}

let _recordVerdicts: Record<string, RecordVerdict> | null = null;

/** Get all record verdicts (keyed by "recordType:recordId").
 * Loaded from a separate record-verdicts.json (split from database.json). */
function getRecordVerdicts(): Record<string, RecordVerdict> {
  if (_recordVerdicts) return _recordVerdicts;
  const filePath = path.join(LOCAL_DATA_DIR, "record-verdicts.json");
  try {
    _recordVerdicts = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    return _recordVerdicts!;
  } catch {
    _recordVerdicts = {};
    return _recordVerdicts;
  }
}

/**
 * Shared dev-mode warning for the QUA-417 composite-key bug class.
 * No-op in production.
 */
function warnMalformedRecordId(
  fn: string,
  recordType: string,
  recordId: string,
): void {
  if (process.env.NODE_ENV !== "production") {
    // eslint-disable-next-line no-console
    console.warn(
      `[sourcing] ${fn}(${JSON.stringify(recordType)}, ${JSON.stringify(recordId)}): ` +
        `recordId failed isCandidateRecordId guard (likely a composite React key — see QUA-417). ` +
        `Returning null; the verdict lookup would have silently missed anyway.`,
    );
  }
}

/**
 * Get the sourcing verdict for a specific record.
 *
 * QUA-423: runtime guard against composite React keys passed as recordId
 * (the QUA-417 bug shape). Returns null fast + dev-mode warning pointing at
 * the real fix, rather than silently missing the lookup and returning null
 * for a different reason.
 */
export function getRecordVerdict(recordType: string, recordId: string): RecordVerdict | null {
  if (!isCandidateRecordId(recordId)) {
    warnMalformedRecordId("getRecordVerdict", recordType, recordId);
    return null;
  }
  return getRecordVerdicts()[`${recordType}:${recordId}`] ?? null;
}

/**
 * Get the sourcing verdict for a specific field of a record.
 * Returns null if no per-field verdict exists for this field.
 *
 * QUA-423: same composite-key guard as getRecordVerdict.
 */
export function getFieldVerdict(recordType: string, recordId: string, fieldName: string): RecordVerdict | null {
  if (!isCandidateRecordId(recordId)) {
    warnMalformedRecordId("getFieldVerdict", recordType, recordId);
    return null;
  }
  return getRecordVerdicts()[`${recordType}:${recordId}:${fieldName}`] ?? null;
}

/** Get all per-field verdicts for a specific record.
 * Returns a map of fieldName -> RecordVerdict. */
export function getFieldVerdicts(recordType: string, recordId: string): Record<string, RecordVerdict> {
  const all = getRecordVerdicts();
  const prefix = `${recordType}:${recordId}:`;
  const result: Record<string, RecordVerdict> = {};
  for (const [key, v] of Object.entries(all)) {
    if (key.startsWith(prefix)) {
      const fieldName = key.slice(prefix.length);
      result[fieldName] = v;
    }
  }
  return result;
}

export type RecordVerdictStats = {
  total: number;
} & Record<SourcingVerdictType, number>;

const VALID_VERDICT_KEYS: ReadonlySet<string> = new Set<SourcingVerdictType>([
  "confirmed",
  "contradicted",
  "unverifiable",
  "outdated",
  "partial",
  "unchecked",
]);

function emptyVerdictStats(): RecordVerdictStats {
  return { total: 0, confirmed: 0, contradicted: 0, unverifiable: 0, outdated: 0, partial: 0, unchecked: 0 };
}

/** Get sourcing stats for a specific record type */
export function getRecordVerdictStats(recordType: string): RecordVerdictStats {
  const verdicts = getRecordVerdicts();
  const stats = emptyVerdictStats();
  for (const [key, v] of Object.entries(verdicts)) {
    if (!key.startsWith(`${recordType}:`)) continue;
    // Per-field entries are three-segment keys ("grant:g_abc:amount") — skip.
    if (key.split(":").length > 2) continue;
    stats.total++;
    if (VALID_VERDICT_KEYS.has(v.verdict)) {
      stats[v.verdict as SourcingVerdictType]++;
    }
  }
  return stats;
}

/**
 * Sourcing stats restricted to a caller-supplied set of record IDs.
 *
 * Use this when the directory page deduplicates or filters records before
 * rendering, so the count of recorded verdicts cannot exceed the visible row
 * total. IDs absent from the verdict map are counted as `unchecked` so total
 * always equals `recordIds.size`. Per-field verdicts (3-segment keys) are
 * ignored.
 */
export function getRecordVerdictStatsForIds(
  recordType: string,
  recordIds: ReadonlySet<string>,
): RecordVerdictStats {
  const verdicts = getRecordVerdicts();
  const stats = emptyVerdictStats();
  for (const id of recordIds) {
    stats.total++;
    const v = verdicts[`${recordType}:${id}`];
    const verdictName: SourcingVerdictType =
      v && VALID_VERDICT_KEYS.has(v.verdict)
        ? (v.verdict as SourcingVerdictType)
        : "unchecked";
    stats[verdictName]++;
  }
  return stats;
}

// ============================================================================
// POLICY STAKEHOLDER IDS
// Maps "policyEntityStableId:stakeholderDisplayName" -> PG stakeholder ID.
// Used by legislation pages to look up sourcing verdicts for stakeholder rows.
// ============================================================================

/** Get the PG stakeholder ID for a YAML stakeholder on a specific policy entity. */
export function getPolicyStakeholderId(
  policyEntityStableId: string,
  stakeholderDisplayName: string,
): string | null {
  const map = getTableBase().policyStakeholderIds;
  if (!map) return null;
  return map[`${policyEntityStableId}:${stakeholderDisplayName}`] ?? null;
}

/**
 * Pick the worst-case verdict from a list of verdict strings, ignoring any
 * values not in the canonical priority map. Pure function — exported for unit
 * tests and for any caller that has already resolved a list of verdicts.
 *
 * Routes through SOURCE_CHECK_VERDICT_PRIORITY (verdict-styles.ts) so this
 * helper and rollupVerdictFromSummary stay in sync. Per QUA-429: ordering is
 * `contradicted > outdated > partial > unverifiable > confirmed > unchecked`
 * (lower number in the priority map = worse / more actionable).
 *
 * Note: `unchecked` is included in the canonical map but is dominated by every
 * real verdict, so a list like ["confirmed", "unchecked"] still returns
 * "confirmed".
 */
export function pickWorstVerdict(
  verdicts: readonly string[],
): string | null {
  let worst: string | null = null;
  let worstPriority = Infinity;
  for (const v of verdicts) {
    const p = SOURCE_CHECK_VERDICT_PRIORITY[v];
    if (p === undefined) continue;
    if (p < worstPriority) {
      worstPriority = p;
      worst = v;
    }
  }
  return worst;
}

/**
 * Roll up per-child sourcing verdicts to a single worst-case verdict
 * string. Generic across any parent→child relationship (e.g. policy→stakeholder,
 * org→personnel, publication→citation). Callers are responsible for resolving
 * their domain-specific name→id mapping before calling this.
 *
 * This is a workaround for parent record types that lack their own
 * sourcing coverage yet (QUA-214). When coverage lands, call sites should
 * prefer the parent's own verdict and/or combine it with the aggregated
 * children via pickWorstVerdict.
 *
 * Returns null if `recordIds` is empty or none of the ids have a verdict.
 */
export function aggregateRecordVerdicts(
  recordType: string,
  recordIds: readonly string[],
): string | null {
  if (recordIds.length === 0) return null;
  const verdicts: string[] = [];
  for (const id of recordIds) {
    const v = getRecordVerdict(recordType, id);
    if (v) verdicts.push(v.verdict);
  }
  return pickWorstVerdict(verdicts);
}

// Re-export loadYaml for use in domain modules
export { loadYaml };
// Re-export wiki-server helpers
export { fetchFromWikiServer, withApiFallback };
