/**
 * People Create Subcommand
 *
 * Generate YAML entity stubs for discovered person candidates.
 */

import type { CommandResult } from '../../lib/command-types.ts';
import {
  type DiscoverCommandOptions,
  discoverCandidates,
} from './shared.ts';

export async function createCommand(
  _args: string[],
  options: DiscoverCommandOptions,
): Promise<CommandResult> {
  const minAppearances = options.minAppearances
    ? parseInt(options.minAppearances, 10)
    : 2;

  const candidates = discoverCandidates();

  const filtered = Array.from(candidates.values())
    .filter((c) => c.appearances >= minAppearances)
    .sort((a, b) => b.score - a.score || b.appearances - a.appearances);

  if (filtered.length === 0) {
    return {
      exitCode: 0,
      output: `No candidates with ${minAppearances}+ appearances to create.`,
    };
  }

  const lines: string[] = [];
  lines.push('# Candidate person entity YAML entries');
  lines.push('# Generated by `crux people create`');
  lines.push('# Review each entry before adding to data/entities/people.yaml');
  lines.push(
    '# Entity IDs must be allocated via: pnpm crux ids allocate <slug>',
  );
  lines.push('');

  for (const c of filtered) {
    // Collect related org IDs from sources
    const relatedOrgs = new Set<string>();
    for (const s of c.sources) {
      if (s.type === 'org-keyPeople') {
        const match = s.context.match(/\(([a-z0-9-]+)\)$/);
        if (match) relatedOrgs.add(match[1]);
      }
    }

    // Find role from experts.yaml source
    let role = '';
    const expertSource = c.sources.find((s) => s.type === 'expert');
    if (expertSource) {
      const roleMatch = expertSource.context.match(
        /\(([^)]+?)(?:\s+@\s+[^)]+)?\)/,
      );
      if (roleMatch && roleMatch[1] !== 'no role') {
        role = roleMatch[1];
      }
    }

    lines.push(`- id: ${c.id}`);
    lines.push(`  numericId: # Run: pnpm crux ids allocate ${c.id}`);
    lines.push('  type: person');
    lines.push(`  title: ${c.name}`);

    if (role) {
      lines.push('  customFields:');
      lines.push('    - label: Role');
      lines.push(`      value: "${role}"`);
    }

    if (relatedOrgs.size > 0) {
      lines.push('  relatedEntries:');
      for (const orgId of relatedOrgs) {
        lines.push(`    - id: ${orgId}`);
        lines.push('      type: organization');
      }
    }

    const sourceTypes = [...new Set(c.sources.map((s) => s.type))].join(', ');
    lines.push('  description: >-');
    lines.push(
      `    TODO: Add description for ${c.name}. Discovered from: ${sourceTypes}.`,
    );
    lines.push('');
  }

  return { exitCode: 0, output: lines.join('\n') };
}
