/**
 * People Link-Resources Subcommand
 *
 * Match literature papers to person entities by author name.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { CommandResult } from '../../lib/command-types.ts';
import {
  type LinkResourcesCommandOptions,
  type PersonEntity,
  type LiteratureCategoryFull,
  DATA_DIR,
  parseYaml,
  stringifyYaml,
  buildAuthorLookup,
  matchAuthor,
} from './shared.ts';

export async function linkResourcesCommand(
  _args: string[],
  options: LinkResourcesCommandOptions,
): Promise<CommandResult> {
  const verbose = !!options.verbose;
  const apply = !!options.apply;

  // Load people entities
  const peoplePath = path.join(DATA_DIR, 'entities/people.yaml');
  if (!fs.existsSync(peoplePath)) {
    return { exitCode: 1, output: 'Error: data/entities/people.yaml not found' };
  }
  const people: PersonEntity[] = parseYaml(fs.readFileSync(peoplePath, 'utf8'));

  // Load literature
  const litPath = path.join(DATA_DIR, 'literature.yaml');
  if (!fs.existsSync(litPath)) {
    return { exitCode: 1, output: 'Error: data/literature.yaml not found' };
  }
  const litData = parseYaml(fs.readFileSync(litPath, 'utf8'));
  const categories: LiteratureCategoryFull[] = litData.categories || [];

  // Build name lookup
  const authorLookup = buildAuthorLookup(people);

  if (verbose) {
    console.log(`Loaded ${people.length} people entities`);
    console.log(`Loaded ${categories.length} literature categories`);
    console.log(`Author lookup has ${authorLookup.size} name variants`);
  }

  // Match papers to people
  const matchMap = new Map<string, { personId: string; personName: string; literature: Array<{ title: string; year?: number; type?: string; link?: string; category: string }> }>();

  // Initialize entries for all people
  for (const person of people) {
    const cleanName = person.title.replace(/\s*\(.*?\)\s*$/, '').trim();
    matchMap.set(person.id, {
      personId: person.id,
      personName: cleanName,
      literature: [],
    });
  }

  let totalPapers = 0;
  let matchedPapers = 0;
  const unmatchedAuthors = new Set<string>();

  for (const category of categories) {
    for (const paper of category.papers) {
      totalPapers++;
      let paperMatched = false;

      for (const author of paper.authors) {
        const entityId = matchAuthor(author, authorLookup);
        if (entityId) {
          const entry = matchMap.get(entityId);
          if (entry) {
            entry.literature.push({
              title: paper.title,
              year: paper.year,
              type: paper.type,
              link: paper.link,
              category: category.name,
            });
            paperMatched = true;
          }
        } else {
          unmatchedAuthors.add(author);
        }
      }

      if (paperMatched) matchedPapers++;
    }
  }

  // Build output
  const lines: string[] = [];
  lines.push(`\n  People-Resource Linking Report`);
  lines.push(`  ${'='.repeat(40)}`);
  lines.push(`  Total papers in literature.yaml: ${totalPapers}`);
  lines.push(`  Papers matched to at least one person: ${matchedPapers}`);
  lines.push(`  Unmatched papers: ${totalPapers - matchedPapers}`);

  // People with matches
  const peopleWithMatches = [...matchMap.values()].filter(
    (m) => m.literature.length > 0,
  );
  peopleWithMatches.sort((a, b) => b.literature.length - a.literature.length);

  lines.push(`\n  People with linked publications: ${peopleWithMatches.length} / ${people.length}`);
  lines.push('');

  for (const match of peopleWithMatches) {
    lines.push(`  ${match.personName} (${match.personId}): ${match.literature.length} publications`);
    if (verbose) {
      for (const lit of match.literature) {
        lines.push(`    - ${lit.title} (${lit.year ?? 'n/a'})`);
      }
    }
  }

  if (verbose && unmatchedAuthors.size > 0) {
    lines.push(`\n  Unmatched authors (${unmatchedAuthors.size}):`);
    for (const author of [...unmatchedAuthors].sort()) {
      lines.push(`    - ${author}`);
    }
  }

  // Write mapping file if --apply
  if (apply) {
    const outputData = peopleWithMatches.map((match) => ({
      personId: match.personId,
      personName: match.personName,
      publications: match.literature.map((lit) => ({
        title: lit.title,
        year: lit.year,
        type: lit.type,
        link: lit.link,
        category: lit.category,
      })),
    }));

    const outputPath = path.join(DATA_DIR, 'people-resources.yaml');
    const yamlOutput = stringifyYaml(outputData, { lineWidth: 120 });
    fs.writeFileSync(outputPath, `# Auto-generated by: pnpm crux people link-resources --apply\n# Maps person entities to their publications from literature.yaml\n# Last generated: ${new Date().toISOString().split('T')[0]}\n\n${yamlOutput}`);
    lines.push(`\n  Wrote ${outputPath}`);
  } else {
    lines.push(`\n  (dry run — use --apply to write data/people-resources.yaml)`);
  }

  return { exitCode: 0, output: lines.join('\n') };
}
