/**
 * People Link-Resources Subcommand
 *
 * Match literature papers to person entities by author name.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { CommandResult } from '../../lib/command-types.ts';
import {
  type LinkResourcesCommandOptions,
  type PersonEntity,
  type LiteratureCategoryFull,
  DATA_DIR,
  parseYaml,
  stringifyYaml,
  buildAuthorLookup,
  matchAuthor,
} from './shared.ts';

export async function linkResourcesCommand(
  _args: string[],
  options: LinkResourcesCommandOptions,
): Promise<CommandResult> {
  const verbose = !!options.verbose;
  const apply = !!options.apply;

  // Load people entities
  const peoplePath = path.join(DATA_DIR, 'entities/people.yaml');
  if (!fs.existsSync(peoplePath)) {
    return { exitCode: 1, output: 'Error: data/entities/people.yaml not found' };
  }
  const people: PersonEntity[] = parseYaml(fs.readFileSync(peoplePath, 'utf8'));

  // Load literature
  const litPath = path.join(DATA_DIR, 'literature.yaml');
  if (!fs.existsSync(litPath)) {
    return { exitCode: 1, output: 'Error: data/literature.yaml not found' };
  }
  const litData = parseYaml(fs.readFileSync(litPath, 'utf8'));
  const categories: LiteratureCategoryFull[] = litData.categories || [];

  // Build name lookup
  const authorLookup = buildAuthorLookup(people);

  if (verbose) {
    console.log(`Loaded ${people.length} people entities`);
    console.log(`Loaded ${categories.length} literature categories`);
    console.log(`Author lookup has ${authorLookup.size} name variants`);
  }

  // Match papers to people
  const matchMap = new Map<string, { personId: string; personName: string; literature: Array<{ title: string; year?: number; type?: string; link?: string; category: string }> }>();

  // Initialize entries for all people
  for (const person of people) {
    const cleanName = person.title.replace(/\s*\(.*?\)\s*$/, '').trim();
    matchMap.set(person.id, {
      personId: person.id,
      personName: cleanName,
      literature: [],
    });
  }

  let totalPapers = 0;
  let matchedPapers = 0;
  const unmatchedAuthors = new Set<string>();

  for (const category of categories) {
    for (const paper of category.papers) {
      totalPapers++;
      let paperMatched = false;

      for (const author of paper.authors) {
        const entityId = matchAuthor(author, authorLookup);
        if (entityId) {
          const entry = matchMap.get(entityId);
          if (entry) {
            entry.literature.push({
              title: paper.title,
              year: paper.year,
              type: paper.type,
              link: paper.link,
              category: category.name,
            });
            paperMatched = true;
          }
        } else {
          unmatchedAuthors.add(author);
        }
      }

      if (paperMatched) matchedPapers++;
    }
  }

  // Build output
  const lines: string[] = [];
  lines.push(`\n  People-Resource Linking Report`);
  lines.push(`  ${'='.repeat(40)}`);
  lines.push(`  Total papers in literature.yaml: ${totalPapers}`);
  lines.push(`  Papers matched to at least one person: ${matchedPapers}`);
  lines.push(`  Unmatched papers: ${totalPapers - matchedPapers}`);

  // People with matches
  const peopleWithMatches = [...matchMap.values()].filter(
    (m) => m.literature.length > 0,
  );
  peopleWithMatches.sort((a, b) => b.literature.length - a.literature.length);

  lines.push(`\n  People with linked publications: ${peopleWithMatches.length} / ${people.length}`);
  lines.push('');

  for (const match of peopleWithMatches) {
    lines.push(`  ${match.personName} (${match.personId}): ${match.literature.length} publications`);
    if (verbose) {
      for (const lit of match.literature) {
        lines.push(`    - ${lit.title} (${lit.year ?? 'n/a'})`);
      }
    }
  }

  if (verbose && unmatchedAuthors.size > 0) {
    lines.push(`\n  Unmatched authors (${unmatchedAuthors.size}):`);
    for (const author of [...unmatchedAuthors].sort()) {
      lines.push(`    - ${author}`);
    }
  }

  // Write mapping file if --apply
  if (apply) {
    const outputData = peopleWithMatches.map((match) => ({
      personId: match.personId,
      personName: match.personName,
      publications: match.literature.map((lit) => ({
        title: lit.title,
        year: lit.year,
        type: lit.type,
        link: lit.link,
        category: lit.category,
      })),
    }));

    const outputPath = path.join(DATA_DIR, 'people-resources.yaml');
    const yamlOutput = stringifyYaml(outputData, { lineWidth: 120 });
    fs.writeFileSync(outputPath, `# Auto-generated by: pnpm crux people link-resources --apply\n# Maps person entities to their publications from literature.yaml\n# Last generated: ${new Date().toISOString().split('T')[0]}\n\n${yamlOutput}`);
    lines.push(`\n  Wrote ${outputPath}`);

    // Also sync authorEntityIds to wiki-server resources
    await syncAuthorEntityIds(people, authorLookup, lines, verbose);
  } else {
    lines.push(`\n  (dry run — use --apply to write data/people-resources.yaml and sync to wiki-server)`);
  }

  return { exitCode: 0, output: lines.join('\n') };
}

/**
 * Sync authorEntityIds to wiki-server resources table.
 * Fetches all resources, matches authors to person entities, and batch-updates.
 */
async function syncAuthorEntityIds(
  people: PersonEntity[],
  authorLookup: Map<string, string>,
  lines: string[],
  verbose: boolean,
): Promise<void> {
  const { apiRequest } = await import('../../lib/wiki-server/client.ts');
  const { buildEntityMatcher } = await import('../../lib/grant-import/entity-matcher.ts');
  const matcher = buildEntityMatcher();

  // Fetch all resources from wiki-server
  let allResources: Array<{ id: string; authors: string[] | null; authorEntityIds: string[] | null }> = [];
  let offset = 0;
  while (true) {
    const r = await apiRequest<{ resources: Array<{ id: string; authors: string[] | null; authorEntityIds: string[] | null }>; total: number }>(
      'GET', `/api/resources/all?limit=200&offset=${offset}`,
    );
    if (!r.ok) {
      lines.push(`\n  Warning: Could not fetch resources from wiki-server: ${r.message}`);
      return;
    }
    allResources.push(...r.data.resources);
    if (allResources.length >= r.data.total) break;
    offset += 200;
  }

  lines.push(`\n  Syncing authorEntityIds to wiki-server (${allResources.length} resources)...`);

  // Match authors to entity IDs for each resource
  const updates: Array<{ resourceId: string; authorEntityIds: string[] }> = [];
  let matchedResources = 0;

  for (const resource of allResources) {
    if (!resource.authors || resource.authors.length === 0) continue;

    const entityIds: string[] = [];
    for (const author of resource.authors) {
      // Try the YAML-based author lookup first (exact match)
      const yamlMatch = matchAuthor(author, authorLookup);
      if (yamlMatch) {
        // Convert slug to stableId via the entity matcher
        const entityMatch = matcher.match(yamlMatch);
        if (entityMatch) {
          entityIds.push(entityMatch.stableId);
          continue;
        }
      }
      // Try the entity matcher directly (handles FactBase entities)
      const directMatch = matcher.match(author);
      if (directMatch) {
        entityIds.push(directMatch.stableId);
      }
    }

    if (entityIds.length > 0) {
      // Only update if different from existing
      const existing = new Set(resource.authorEntityIds || []);
      const newIds = new Set(entityIds);
      if (entityIds.length !== existing.size || entityIds.some(id => !existing.has(id))) {
        updates.push({ resourceId: resource.id, authorEntityIds: [...new Set(entityIds)] });
      }
      matchedResources++;
    }
  }

  if (updates.length === 0) {
    lines.push(`  No authorEntityIds changes needed (${matchedResources} resources already linked)`);
    return;
  }

  // Batch update in chunks
  const BATCH_SIZE = 200;
  let totalUpdated = 0;
  for (let i = 0; i < updates.length; i += BATCH_SIZE) {
    const batch = updates.slice(i, i + BATCH_SIZE);
    const r = await apiRequest<{ updated: number }>('PATCH', '/api/resources/author-entity-ids', { items: batch });
    if (r.ok) {
      totalUpdated += r.data.updated;
    } else {
      lines.push(`  Warning: Batch ${Math.floor(i / BATCH_SIZE) + 1} failed: ${r.message}`);
    }
  }

  lines.push(`  Updated authorEntityIds for ${totalUpdated} resources (${matchedResources} total with matched authors)`);
  if (verbose) {
    for (const u of updates.slice(0, 10)) {
      lines.push(`    ${u.resourceId}: ${u.authorEntityIds.length} author(s)`);
    }
    if (updates.length > 10) lines.push(`    ... and ${updates.length - 10} more`);
  }
}
