/**
 * Scorecard → FactBase mirror (QUA-865).
 *
 * Reads "overall" grades from the latest snapshot of each scorecard source
 * (PG `scorecard_grades` via the wiki-server API) and writes them as
 * FactBase facts under each rated organization's per-entity directory at
 * `packages/factbase/data/fb-entities/<slug>/scorecard-grades.yaml`.
 *
 * The managed yaml file is fully owned by this sync — it is rewritten on
 * every run with a "do not edit by hand" header. To keep diffs stable,
 * fact IDs are deterministic via `generateContentFactId(subject, predicate,
 * value, asOf)`, so re-running the sync with unchanged data produces
 * byte-identical output.
 *
 * If an entity exists as a single-file `<slug>.yaml`, it is migrated to
 * `<slug>/entity.yaml` so the directory pattern can host the additional
 * `scorecard-grades.yaml`. Single-file entities not rated by any scorecard
 * are not touched.
 *
 * Why this exists: see QUA-865. Mirroring scorecard grades into FactBase
 * lets `<FBF>` MDX components and coverage scoring read scorecard signals
 * the same way they read every other org-level fact.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, renameSync, rmSync, rmdirSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';
import {
  getAllScorecardGrades,
  type ScorecardGradesAllResult,
} from '../wiki-server/scorecard-grades.ts';
import type { ApiResult } from '../wiki-server/client.ts';
import { generateContentFactId } from '../../../packages/factbase/src/ids.ts';
import { loadAllEntities, type EntityWithType } from '../research/entity-loader.ts';

// ── Types ──────────────────────────────────────────────────────────────

/** Single grade row returned by the wiki-server API. */
export type ApiGrade = ScorecardGradesAllResult['items'][number];

/** A single fact ready to be serialized into yaml. */
export interface MirrorFact {
  id: string;
  property: string;
  value: string;
  asOf: string;
  source: string;
  notes: string;
}

/** Map from entity stableId → facts for that entity, sorted deterministically. */
export type FactsByEntity = Map<string, MirrorFact[]>;

/**
 * Map from `scorecardSource` (PG enum) → factbase predicate id.
 * Predicates are registered in `packages/factbase/data/properties.yaml`
 * under the `scorecards` category.
 */
export const SCORECARD_PREDICATE_BY_SOURCE: Record<string, string> = {
  fli_index: 'fli-index-grade',
  saferai: 'saferai-grade',
  ailabwatch: 'ailabwatch-grade',
  fmti: 'fmti-grade',
  seoul_tracker: 'seoul-tracker-grade',
};

/**
 * Display label for the `notes:` field on each generated fact. Read by
 * humans browsing the yaml; the source is embedded in `source:` itself.
 */
const SOURCE_NOTES_LABEL: Record<string, string> = {
  fli_index: 'FLI AI Safety Index',
  saferai: 'SaferAI Ratings',
  ailabwatch: 'AI Lab Watch',
  fmti: 'Stanford FMTI',
  seoul_tracker: 'Seoul Commitment Tracker',
};

const MANAGED_FILE = 'scorecard-grades.yaml';
const MAIN_FILE = 'entity.yaml';

const MANAGED_HEADER = `# Auto-generated by \`pnpm crux fb sync-scorecard-facts\` (QUA-865).
# Do not edit by hand — changes will be overwritten on next sync.
# Source: scorecard_grades (latest snapshot, dimension_slug='overall').
#
# To regenerate: \`WIKI_SERVER_ENV=prod pnpm crux fb sync-scorecard-facts\`
`;

// ── Pure transforms ────────────────────────────────────────────────────

/**
 * Convert one API grade row into a MirrorFact, or return null if the row
 * cannot be mirrored (unknown source, missing source url, etc.).
 *
 * Pure — no I/O. Used by buildFactsByEntity() and tested in isolation.
 */
export function gradeToFact(grade: ApiGrade): MirrorFact | null {
  // The API typing models scorecardSource as joinable nullable (the row
  // is left-joined to scorecard_snapshots), but in practice every grade
  // has a snapshot. Treat null defensively.
  const source_ = grade.scorecardSource;
  if (!source_) return null;
  const predicate = SCORECARD_PREDICATE_BY_SOURCE[source_];
  if (!predicate) return null;

  // Use scoreRaw because it preserves the exact source representation
  // (letters, percents, FMTI's "X / 100") — that's what humans want to
  // see embedded with <FBF>.
  const value = grade.scoreRaw;
  if (!value) return null;

  // Source: prefer the per-grade deep-link; fall back to the snapshot's
  // top-level source URL. Most grades inherit (sourceUrl is null) so the
  // fallback is the common case.
  const source = grade.sourceUrl ?? grade.snapshotSourceUrl;
  if (!source) return null;

  const asOf = grade.publishedAt;
  if (!asOf) return null;

  const sourceLabel = SOURCE_NOTES_LABEL[source_] ?? source_;
  const wave = formatWaveLabel(asOf);
  const notes = `${sourceLabel} — ${wave}`;

  // Deterministic ID — same (subject, predicate, value, asOf) always
  // yields the same fact id, so re-runs with unchanged data produce
  // byte-identical yaml.
  const id = generateContentFactId(grade.entityId, predicate, value, asOf);

  return {
    id,
    property: predicate,
    value,
    asOf,
    source,
    notes,
  };
}

/**
 * Group API grades by entity stableId, dropping rows that can't be
 * mirrored. Within each entity, facts are sorted by (predicate, asOf) so
 * yaml output is stable.
 */
export function buildFactsByEntity(grades: ApiGrade[]): FactsByEntity {
  const out: FactsByEntity = new Map();
  for (const g of grades) {
    const f = gradeToFact(g);
    if (!f) continue;
    const arr = out.get(g.entityId) ?? [];
    arr.push(f);
    out.set(g.entityId, arr);
  }
  // Stable sort within each entity for deterministic diffs.
  for (const [, arr] of out) {
    arr.sort((a, b) => {
      if (a.property !== b.property) return a.property.localeCompare(b.property);
      return a.asOf.localeCompare(b.asOf);
    });
  }
  return out;
}

/**
 * Build a stableId → fb-entity slug map by reading `data/entities/*.yaml`.
 * The slug is the entity's `id` field (which is also the fb-entity yaml
 * filename stem). Entities without a stableId are skipped.
 *
 * Read each call — the map is small (~600 entries) and we want it fresh
 * if the operator just added a new entity.
 */
export function buildSlugByStableId(entities: EntityWithType[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const e of entities) {
    if (typeof e.stableId !== 'string') continue;
    out.set(e.stableId, e.id);
  }
  return out;
}

// ── YAML serialization ─────────────────────────────────────────────────

/** Render the managed scorecard-grades.yaml content for one entity. */
export function renderScorecardGradesYaml(facts: MirrorFact[]): string {
  // js-yaml emits arrays cleanly; we hand-prepend the comment header so
  // the warning lands at the top regardless of yaml dump options.
  const body = yaml.dump(
    { facts },
    {
      lineWidth: 0, // never wrap source URLs
      noRefs: true,
      sortKeys: false, // preserve {id, property, value, asOf, source, notes}
      quotingType: '"',
      forceQuotes: false,
    },
  );
  return MANAGED_HEADER + body;
}

// ── Filesystem operations ──────────────────────────────────────────────

/**
 * Look up the per-entity directory path for `slug` if the entity has any
 * fb-entity yaml on disk (single-file or directory form). Pure — does not
 * mutate the filesystem.
 *
 * Returns the directory path (which may not yet exist on disk in the
 * single-file case) or null if no fb-entity yaml exists for this slug.
 */
export function findEntityDirPath(slug: string, fbEntitiesDir: string): string | null {
  const dirPath = join(fbEntitiesDir, slug);
  if (existsSync(dirPath) && statSync(dirPath).isDirectory()) return dirPath;
  if (existsSync(join(fbEntitiesDir, `${slug}.yaml`))) return dirPath;
  return null;
}

/**
 * Convert `fb-entities/<slug>.yaml` to `fb-entities/<slug>/entity.yaml`
 * if needed, and return the per-entity directory path. No-op when the
 * directory form is already in place. Returns null when no fb-entity
 * yaml exists for this slug — caller decides whether to skip silently
 * or warn (we don't create stub entities here).
 */
export function ensurePerEntityDir(slug: string, fbEntitiesDir: string): string | null {
  const dirPath = findEntityDirPath(slug, fbEntitiesDir);
  if (!dirPath) return null;

  // If the directory already exists on disk, we're done.
  if (existsSync(dirPath) && statSync(dirPath).isDirectory()) return dirPath;

  // Otherwise the single-file form exists — migrate it.
  mkdirSync(dirPath, { recursive: true });
  renameSync(join(fbEntitiesDir, `${slug}.yaml`), join(dirPath, MAIN_FILE));
  return dirPath;
}

/**
 * Write the managed scorecard-grades file under `fb-entities/<slug>/`,
 * migrating from single-file form if needed. Returns the path written
 * to, or null if the entity has no fb-entity yaml (caller's choice
 * whether to skip silently or warn).
 */
export function writeScorecardGradesForEntity(
  slug: string,
  facts: MirrorFact[],
  fbEntitiesDir: string,
): string | null {
  const dirPath = ensurePerEntityDir(slug, fbEntitiesDir);
  if (!dirPath) return null;

  const filePath = join(dirPath, MANAGED_FILE);
  const content = renderScorecardGradesYaml(facts);
  // Atomic write to avoid half-written yaml if interrupted.
  const tmpPath = filePath + '.tmp';
  writeFileSync(tmpPath, content, 'utf-8');
  renameSync(tmpPath, filePath);
  return filePath;
}

/**
 * Find every existing managed scorecard-grades.yaml in the fb-entities
 * directory. Returns `{slug, path}` tuples — used to clean up files for
 * entities that no longer have scorecard grades (e.g. an org dropped
 * from a wave). Returns an empty list when the fb-entities directory
 * doesn't exist.
 */
export function findExistingManagedFiles(
  fbEntitiesDir: string,
): Array<{ slug: string; path: string }> {
  if (!existsSync(fbEntitiesDir)) return [];
  const out: Array<{ slug: string; path: string }> = [];
  const entries = readdirSync(fbEntitiesDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const candidate = join(fbEntitiesDir, entry.name, MANAGED_FILE);
    if (existsSync(candidate)) out.push({ slug: entry.name, path: candidate });
  }
  return out;
}

/**
 * Remove a managed scorecard-grades.yaml file and, if doing so would leave
 * the per-entity directory holding only `entity.yaml`, "un-migrate" by
 * moving `entity.yaml` back to `<slug>.yaml` so the clean-up doesn't
 * leave behind a directory with a single file.
 *
 * `fbEntitiesDir` must be the canonical fb-entities root that contains
 * `slug` — passed explicitly so this function never silently deletes
 * outside the expected tree.
 *
 * Returns true if anything changed.
 */
export function removeManagedFile(slug: string, fbEntitiesDir: string): boolean {
  const dirPath = join(fbEntitiesDir, slug);
  const filePath = join(dirPath, MANAGED_FILE);
  if (!existsSync(filePath)) return false;
  rmSync(filePath);

  // Examine what's left in the entity directory.
  const remaining = readdirSync(dirPath);
  if (remaining.length === 1 && remaining[0] === MAIN_FILE) {
    // Only entity.yaml left — fold back to single-file form.
    const newSingle = join(fbEntitiesDir, `${slug}.yaml`);
    renameSync(join(dirPath, MAIN_FILE), newSingle);
    rmdirSync(dirPath);
  } else if (remaining.length === 0) {
    rmdirSync(dirPath);
  }

  return true;
}

// ── High-level orchestrator ────────────────────────────────────────────

export interface SyncSummary {
  /** Total grades returned by the API. */
  apiGrades: number;
  /** Distinct entity stableIds with at least one mirrorable grade. */
  entitiesWithGrades: number;
  /** Entities written to (resolved + had a slug + had an existing fb-entity yaml). */
  entitiesWritten: number;
  /** Entities skipped because no fb-entity yaml existed for the slug. */
  entitiesSkippedNoFbYaml: number;
  /** Entities skipped because no slug was found for the stableId. */
  entitiesSkippedNoSlug: number;
  /** Stale managed files removed (entity no longer has any scorecard grades). */
  removed: number;
  /** Per-entity outcomes for verbose output. */
  details: Array<{
    slug: string | null;
    stableId: string | null;
    factCount: number;
    status: 'written' | 'skipped-no-fb-yaml' | 'skipped-no-slug' | 'removed';
    path: string | null;
  }>;
}

export interface SyncOptions {
  /** Override the fb-entities directory for tests. */
  fbEntitiesDir?: string;
  /** Override entity loading for tests. */
  entities?: EntityWithType[];
  /** Inject grades directly (skips the API fetch). */
  grades?: ApiGrade[];
  /** When true, don't write to disk — just compute what would happen. */
  dryRun?: boolean;
}

const DEFAULT_FB_ENTITIES_DIR = join(
  import.meta.dirname!,
  '../../../packages/factbase/data/fb-entities',
);

/**
 * End-to-end sync: fetch latest overall grades, group by entity, write
 * managed yaml files, and clean up stale ones.
 *
 * Idempotent — running twice in a row with no source data change
 * produces zero file changes (deterministic IDs + stable sort + atomic
 * writes).
 */
export async function syncScorecardFactsToYaml(
  opts: SyncOptions = {},
): Promise<SyncSummary> {
  const fbEntitiesDir = opts.fbEntitiesDir ?? DEFAULT_FB_ENTITIES_DIR;

  const grades = opts.grades ?? (await fetchAllOverallGrades());
  const factsByEntity = buildFactsByEntity(grades);

  const entities = opts.entities ?? loadAllEntities();
  const slugByStableId = buildSlugByStableId(entities);

  const summary: SyncSummary = {
    apiGrades: grades.length,
    entitiesWithGrades: factsByEntity.size,
    entitiesWritten: 0,
    entitiesSkippedNoFbYaml: 0,
    entitiesSkippedNoSlug: 0,
    removed: 0,
    details: [],
  };

  const writtenPaths = new Set<string>();

  for (const [stableId, facts] of factsByEntity) {
    const slug = slugByStableId.get(stableId);
    if (!slug) {
      summary.entitiesSkippedNoSlug++;
      summary.details.push({
        slug: null,
        stableId,
        factCount: facts.length,
        status: 'skipped-no-slug',
        path: null,
      });
      continue;
    }

    // For dry-run, look up the would-be path without mutating; for the
    // live path, perform the write and capture the resulting path.
    const path = opts.dryRun
      ? (() => {
          const dir = findEntityDirPath(slug, fbEntitiesDir);
          return dir ? join(dir, MANAGED_FILE) : null;
        })()
      : writeScorecardGradesForEntity(slug, facts, fbEntitiesDir);
    if (!path) {
      summary.entitiesSkippedNoFbYaml++;
      summary.details.push({
        slug,
        stableId,
        factCount: facts.length,
        status: 'skipped-no-fb-yaml',
        path: null,
      });
      continue;
    }
    summary.entitiesWritten++;
    summary.details.push({
      slug,
      stableId,
      factCount: facts.length,
      status: 'written',
      path,
    });
    writtenPaths.add(path);
  }

  // Clean up stale managed files: any existing scorecard-grades.yaml that
  // wasn't written this run belongs to an entity that no longer has any
  // scorecard grades (e.g. dropped from latest wave). In dry-run we still
  // count would-be removals so the operator's preview is accurate.
  const existingManaged = findExistingManagedFiles(fbEntitiesDir);
  for (const { slug, path } of existingManaged) {
    if (writtenPaths.has(path)) continue;
    if (!opts.dryRun) removeManagedFile(slug, fbEntitiesDir);
    summary.removed++;
    summary.details.push({
      slug,
      stableId: null,
      factCount: 0,
      status: 'removed',
      path,
    });
  }

  return summary;
}

// ── Post-sync orchestration helper ─────────────────────────────────────

export interface PostSyncMirrorResult {
  written: number;
  skipped: number;
  removed: number;
}

/**
 * Run the FactBase mirror as a post-step of a scorecard ingest. Returns
 * `{summary, error}` — never throws. Failures are reported as warnings on
 * the console and surfaced in `error` so the caller can include them in
 * its CI output without conflating mirror failures with PG-sync failures.
 *
 * Both `import-scorecards sync` and `scorecards fmti ingest` call this
 * with consistent semantics: a wiki-server outage during the mirror does
 * not fail the PG sync (per QUA-865).
 */
export async function runMirrorAfterSync(
  dryRun: boolean,
): Promise<{ summary: PostSyncMirrorResult | null; error: string | null }> {
  try {
    const summary = await syncScorecardFactsToYaml({ dryRun });
    return {
      summary: {
        written: summary.entitiesWritten,
        skipped: summary.entitiesSkippedNoFbYaml + summary.entitiesSkippedNoSlug,
        removed: summary.removed,
      },
      error: null,
    };
  } catch (err) {
    return {
      summary: null,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

// ── Helpers ─────────────────────────────────────────────────────────────

/**
 * Fetch every overall+latest grade in pages of 200. The API caps `limit`
 * at MAX_PAGE_SIZE (1000), but pagination is cheap and 200 keeps response
 * sizes predictable.
 */
async function fetchAllOverallGrades(): Promise<ApiGrade[]> {
  const PAGE_SIZE = 200;
  const all: ApiGrade[] = [];
  let offset = 0;
  // Hard cap so a buggy server can never spin us forever.
  const HARD_CAP = 5000;
  while (all.length < HARD_CAP) {
    const res: ApiResult<ScorecardGradesAllResult> = await getAllScorecardGrades({
      limit: PAGE_SIZE,
      offset,
      latest: true,
      overall: true,
    });
    if (!res.ok) {
      throw new Error(
        `[scorecard-mirror] failed to fetch grades (offset=${offset}): ${res.error} ${res.message}`,
      );
    }
    all.push(...res.data.items);
    if (res.data.items.length < PAGE_SIZE) break;
    offset += PAGE_SIZE;
  }
  return all;
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

/**
 * Render a human label for the snapshot date, used in the `notes:` field
 * of each generated fact. Falls back to the raw `asOf` string when the
 * date isn't in a recognized form.
 *   2025-12-02  → "December 2025"
 *   2025-10-01  → "October 2025"
 *   2024-06     → "June 2024"
 *   2025        → "2025"
 *   "garbage"   → "garbage" (fall-through; do not throw)
 */
export function formatWaveLabel(asOf: string): string {
  const m = /^(\d{4})(?:-(\d{2}))?(?:-(\d{2}))?$/.exec(asOf);
  if (!m) return asOf;
  const [, yearStr, monthStr] = m;
  const year = Number(yearStr);
  if (!monthStr) return String(year);
  const month = Number(monthStr);
  if (month >= 1 && month <= 12) return `${MONTH_NAMES[month - 1]} ${year}`;
  return asOf;
}

/**
 * Read a managed scorecard-grades.yaml back. Returns the parsed facts
 * array, or [] if the file is empty/missing/malformed. Used by tests
 * and by anyone who needs to inspect what was written without re-running
 * the full loader.
 */
export function readManagedFile(filePath: string): MirrorFact[] {
  if (!existsSync(filePath)) return [];
  const content = readFileSync(filePath, 'utf-8');
  const parsed = yaml.load(content) as { facts?: unknown };
  if (!parsed || !Array.isArray(parsed.facts)) return [];
  return parsed.facts.filter(isMirrorFact);
}

function isMirrorFact(x: unknown): x is MirrorFact {
  if (!x || typeof x !== 'object') return false;
  const o = x as Record<string, unknown>;
  return (
    typeof o.id === 'string' &&
    typeof o.property === 'string' &&
    typeof o.value === 'string' &&
    typeof o.asOf === 'string' &&
    typeof o.source === 'string' &&
    typeof o.notes === 'string'
  );
}
