/**
 * Agent Workspace Command Handlers — Local multi-agent directory management
 *
 * Manages the `lw/` directory structure for running multiple Claude Code agents
 * in parallel, each with its own clone and port configuration.
 *
 * Usage:
 *   crux sys agent-workspace setup <N>       Initialize agent slot N (clone + .env + .agent-slot)
 *   crux sys agent-workspace sync-env        Regenerate .env for all agent slots from .env.base
 *   crux sys agent-workspace list            Show all agent slots with branch/PR/status info
 *   crux sys agent-workspace clean [N]       Remove idle agent slots (on main, no changes)
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  readdirSync,
  statSync,
  lstatSync,
  copyFileSync,
  mkdirSync,
  unlinkSync,
  utimesSync,
  rmSync,
} from 'fs';
import { join, dirname } from 'path';
import { execSync, execFileSync, spawnSync } from 'child_process';
import os from 'os';
import type { CommandOptions as BaseOptions, CommandResult } from '../lib/command-types.ts';
import { PROJECT_ROOT } from '../lib/content-types.ts';
import { getColors } from '../lib/output.ts';
import { truncate } from '../lib/text-utils.ts';
import {
  type Role,
  type SentinelEnv,
  writeSentinel as writeSentinelImpl,
  touchSentinel as touchSentinelImpl,
  checkConflict as checkConflictImpl,
} from '../lib/agent-workspace/sentinel.ts';
import {
  type TmuxExec,
  type TmuxExecResult,
  claimWindow as claimWindowImpl,
} from '../lib/agent-workspace/tmux.ts';
import {
  runDoctor,
  renderPretty as renderDoctorPretty,
  renderJson as renderDoctorJson,
  exitCodeFor as doctorExitCode,
} from '../lib/agent-workspace/doctor/runner.ts';
import {
  dispatchPaths as makeDispatchPaths,
  runPaths as makeRunPaths,
  detectConflict as detectDispatchConflict,
  spawnDispatch,
  supersedeCurrent as supersedeDispatch,
  clearCurrent as clearDispatchCurrent,
  readCurrent as readDispatchCurrent,
  readMeta as readDispatchMeta,
  writeMeta as writeDispatchMeta,
  parseEventsFile as parseDispatchEvents,
  finalizeIfComplete as finalizeDispatchIfComplete,
  realDispatchEnv,
  isPermissionMode,
  formatApiKeyWarning,
  pollForEarlyDispatchError,
  type DispatchOptions,
  type PermissionMode,
} from '../lib/agent-workspace/dispatch.ts';
import { ensureSlotTmpDir } from '../lib/agent-workspace/tsx-cache-isolation.ts';
import { realDoctorEnv } from '../lib/agent-workspace/doctor/env.ts';
import { SLOTS_CHECKS } from '../lib/agent-workspace/doctor/slots.ts';
import { RELEASES_CHECKS } from '../lib/agent-workspace/doctor/releases.ts';

interface CommandOptions extends BaseOptions {
  ci?: boolean;
  json?: boolean;
  force?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Resolve the `lw/` parent directory (sibling to the repo) */
function getLwDir(): string {
  // PROJECT_ROOT is the repo root (e.g., /Users/.../lw/a3 or /Users/.../longterm-wiki)
  // The lw/ dir is the parent when running from an agent slot,
  // or needs to be explicitly at the same level as the repo.
  const parent = dirname(PROJECT_ROOT);
  const dirName = PROJECT_ROOT.split('/').pop() || '';

  // If we're already inside lw/aN or lw/main, parent is lw/
  if (/^(a\d+|main)$/.test(dirName) && parent.endsWith('/lw')) {
    return parent;
  }

  // Otherwise, lw/ is a sibling directory
  return join(parent, 'lw');
}

function getGitRemoteUrl(): string {
  try {
    return execSync('git remote get-url origin', { cwd: PROJECT_ROOT, encoding: 'utf-8' }).trim();
  } catch {
    return 'git@github.com:quantified-uncertainty/longterm-wiki.git';
  }
}

/** Find all agent slot directories under lw/ */
function findSlotDirs(lwDir: string): Array<{ dir: string; slot: number }> {
  if (!existsSync(lwDir)) return [];

  const entries = readdirSync(lwDir).filter((name) => /^a\d+$/.test(name));
  const results: Array<{ dir: string; slot: number }> = [];

  for (const name of entries) {
    const dir = join(lwDir, name);
    if (!statSync(dir).isDirectory()) continue;
    // Derive slot from directory name — .agent-slot files can be corrupted
    const match = name.match(/^a(\d+)$/);
    if (!match) continue;
    const slot = parseInt(match[1], 10);
    results.push({ dir, slot });
  }

  return results.sort((a, b) => a.slot - b.slot);
}

/** Generate .env content from .env.base + port overrides for a given slot */
function generateEnv(envBasePath: string, slot: number): string {
  const base = readFileSync(envBasePath, 'utf-8');

  // Remove any existing port-related lines from base
  const filtered = base
    .split('\n')
    .filter((line) => {
      const key = line.split('=')[0]?.trim();
      return !['DEV_PORT', 'PORT', 'LONGTERMWIKI_SERVER_URL', 'PLAYWRIGHT_BASE_URL'].includes(key);
    })
    .join('\n');

  const portBlock = [
    '',
    `# Agent ${slot} port config (auto-generated by crux sys agent-workspace)`,
    `DEV_PORT=${3010 + slot}`,
    `PORT=${3110 + slot}`,
    `LONGTERMWIKI_SERVER_URL=http://localhost:${3110 + slot}`,
    `PLAYWRIGHT_BASE_URL=http://localhost:${3010 + slot}`,
    '',
  ].join('\n');

  return filtered.trimEnd() + '\n' + portBlock;
}

/** Run a git command in a directory and return trimmed output */
function git(dir: string, ...args: string[]): string {
  try {
    return execFileSync('git', args, { cwd: dir, encoding: 'utf-8', timeout: 10000 }).trim();
  } catch {
    return '';
  }
}

/** Sanitize a string for use in tmux commands — strip shell-unsafe characters */
function sanitizeForTmux(s: string): string {
  return s.replace(/[^a-zA-Z0-9/_.:@#-]/g, '_');
}

/** Copy latest hooks from main/ to a slot directory.
 * Hooks are tracked in git, so checking out old branches reverts them.
 * Overlaying from main/ ensures slots always have the latest fixes
 * (e.g., -t $TMUX_PANE for correct window targeting). */
function overlayHooks(lwDir: string, slotDir: string): boolean {
  const mainHooksDir = join(lwDir, 'main', '.claude', 'hooks');
  const slotHooksDir = join(slotDir, '.claude', 'hooks');

  if (!existsSync(mainHooksDir)) return false;

  // Only these two hooks contain tmux rename logic that needs the -t $TMUX_PANE fix
  const hookFiles = ['session-start.sh', 'heartbeat.sh'];
  let copied = false;

  mkdirSync(slotHooksDir, { recursive: true });
  for (const file of hookFiles) {
    const src = join(mainHooksDir, file);
    const dst = join(slotHooksDir, file);
    if (!existsSync(src)) continue;

    try {
      copyFileSync(src, dst);
      copied = true;
    } catch { /* permission error — slot hooks stay as-is */ }
  }

  return copied;
}

interface TmuxWindowInfo {
  index: string;
  cwd: string;
  name: string;
}

/** Query tmux for all windows with their index, pane CWD, and name */
function listTmuxWindows(): TmuxWindowInfo[] {
  try {
    // Use '|||' as delimiter — tmux's -F doesn't interpret \t as tab in single quotes,
    // so we need a multi-char delimiter that won't appear in paths or window names.
    const raw = execSync(
      `tmux list-windows -F '#{window_index}|||#{pane_current_path}|||#{window_name}'`,
      { encoding: 'utf-8', timeout: 5000 },
    ).trim();
    return raw.split('\n').filter(Boolean).map((line) => {
      const parts = line.split('|||');
      return { index: parts[0] || '', cwd: parts[1] || '', name: parts[2] || '' };
    }).filter((w) => /^\d+$/.test(w.index) && w.cwd);
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// setup
// ---------------------------------------------------------------------------

async function setup(args: string[], options: CommandOptions): Promise<CommandResult> {
  const slotArg = args.find((a) => !a.startsWith('--'));
  if (!slotArg) {
    return {
      exitCode: 1,
      output: `Usage: crux sys agent-workspace setup <N>

  Initialize agent slot N with a fresh clone, .env, and .agent-slot file.

  Creates lw/aN/ with:
    - Git clone of the repository
    - .agent-slot file (contains the slot number)
    - .env generated from lw/.env.base with per-agent port overrides

  Port assignments (deterministic from slot number):
    Agent N → Next.js on port (3010+N), wiki-server on port (3110+N)
    e.g. slot 1 → 3011/3111, slot 10 → 3020/3120

Options:
  --force    Re-initialize even if the slot directory already exists`,
    };
  }

  if (!/^\d+$/.test(slotArg)) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer' };
  }
  const slot = parseInt(slotArg, 10);
  if (slot < 1 || slot > 99) {
    return { exitCode: 1, output: 'Error: Slot number must be between 1 and 99' };
  }

  const lwDir = getLwDir();
  const slotDir = join(lwDir, `a${slot}`);
  const envBasePath = join(lwDir, '.env.base');

  // Ensure lw/ exists
  if (!existsSync(lwDir)) {
    mkdirSync(lwDir, { recursive: true });
  }

  // Check for .env.base
  if (!existsSync(envBasePath)) {
    return {
      exitCode: 1,
      output: `Error: ${envBasePath} not found.\n\nCreate it first by copying your .env (without port-specific lines):\n  cp ${PROJECT_ROOT}/.env ${envBasePath}`,
    };
  }

  // Clone if needed
  if (existsSync(slotDir)) {
    if (!options.force) {
      // Directory exists — no need to read .agent-slot, the dir name is enough
      return {
        exitCode: 0,
        output: `Slot a${slot} already exists at ${slotDir}. Use --force to re-initialize .env and .agent-slot.`,
      };
    }
    // --force: fall through to regenerate .env and repair .agent-slot below
  } else {
    const remote = getGitRemoteUrl();
    console.error(`Cloning ${remote} → ${slotDir}...`);
    execFileSync('git', ['clone', remote, slotDir], { stdio: 'inherit', timeout: 300000 });
  }

  // Write .agent-slot
  writeFileSync(join(slotDir, '.agent-slot'), String(slot) + '\n');

  // Generate .env
  const envContent = generateEnv(envBasePath, slot);
  writeFileSync(join(slotDir, '.env'), envContent);

  let output = `✓ Agent slot a${slot} ready at ${slotDir}\n`;
  output += `  Next.js:     http://localhost:${3010 + slot}\n`;
  output += `  Wiki-server: http://localhost:${3110 + slot}\n`;
  output += `  .env:        generated from .env.base\n`;
  output += `\nNext steps:\n`;
  output += `  cd ${slotDir} && pnpm install && pnpm setup:quick\n`;

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// sync-env
// ---------------------------------------------------------------------------

async function syncEnv(_args: string[], _options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const envBasePath = join(lwDir, '.env.base');

  if (!existsSync(envBasePath)) {
    return {
      exitCode: 1,
      output: `Error: ${envBasePath} not found.`,
    };
  }

  const slots = findSlotDirs(lwDir);
  if (slots.length === 0) {
    return { exitCode: 0, output: 'No agent slots found.' };
  }

  const lines: string[] = [];
  for (const { dir, slot } of slots) {
    const envContent = generateEnv(envBasePath, slot);
    writeFileSync(join(dir, '.env'), envContent);
    // Repair .agent-slot — the directory name is the source of truth, so
    // overwrite whatever (possibly corrupted) value was there before.
    writeFileSync(join(dir, '.agent-slot'), String(slot) + '\n');
    lines.push(`  ✓ a${slot}/.env regenerated (ports ${3010 + slot}/${3110 + slot})`);
  }

  return {
    exitCode: 0,
    output: `Synced .env for ${slots.length} agent slot(s) from ${envBasePath}:\n${lines.join('\n')}`,
  };
}

// ---------------------------------------------------------------------------
// list
// ---------------------------------------------------------------------------

async function list(_args: string[], options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const slots = findSlotDirs(lwDir);

  // Also check for lw/main
  const mainDir = join(lwDir, 'main');
  const hasMain = existsSync(mainDir) && statSync(mainDir).isDirectory();

  if (slots.length === 0 && !hasMain) {
    return { exitCode: 0, output: `No agent workspace found at ${lwDir}` };
  }

  interface SlotInfo {
    slot: string;
    branch: string;
    dirty: number;
    pr: string;
    ports: string;
  }

  const infos: SlotInfo[] = [];

  if (hasMain) {
    const branch = git(mainDir, 'branch', '--show-current') || 'detached';
    const mainPorcelain = git(mainDir, 'status', '--porcelain');
    const dirty = mainPorcelain ? mainPorcelain.split('\n').filter(Boolean).length : 0;
    infos.push({ slot: 'main', branch, dirty, pr: '', ports: 'default' });
  }

  for (const { dir, slot } of slots) {
    const branch = git(dir, 'branch', '--show-current') || 'detached';
    const porcelain = git(dir, 'status', '--porcelain');
    const dirty = porcelain ? porcelain.split('\n').filter(Boolean).length : 0;

    // Try to get PR number (best-effort, don't fail if gh isn't available)
    let pr = '';
    try {
      const prJson = execSync(
        `gh pr view --json number,state --jq '"#" + (.number|tostring) + " " + .state' 2>/dev/null`,
        { cwd: dir, encoding: 'utf-8', timeout: 10000 },
      ).trim();
      if (prJson) pr = prJson;
    } catch {
      // No PR or gh not available
    }

    infos.push({
      slot: `a${slot}`,
      branch,
      dirty,
      pr,
      ports: `${3010 + slot}/${3110 + slot}`,
    });
  }

  if (options.json) {
    return { exitCode: 0, output: JSON.stringify(infos, null, 2) };
  }

  const c = getColors(options.ci);

  let output = `Agent Workspace (${lwDir})\n\n`;
  output += `  ${'Slot'.padEnd(6)} ${'Branch'.padEnd(35)} ${'Dirty'.padEnd(6)} ${'PR'.padEnd(15)} Ports\n`;
  output += `  ${'─'.repeat(6)} ${'─'.repeat(35)} ${'─'.repeat(6)} ${'─'.repeat(15)} ${'─'.repeat(12)}\n`;

  for (const info of infos) {
    const dirtyStr = info.dirty > 0 ? `${info.dirty}` : '—';
    const line = `  ${info.slot.padEnd(6)} ${info.branch.padEnd(35)} ${dirtyStr.padEnd(6)} ${(info.pr || '—').padEnd(15)} ${info.ports}`;

    // Color: idle (main+clean) → dim, active (branch or dirty) → green, merged PR → yellow
    if (info.pr.includes('MERGED')) {
      output += `${c.yellow}${line}${c.reset}\n`;
    } else if (info.branch !== 'main' || info.dirty > 0) {
      output += `${c.green}${line}${c.reset}\n`;
    } else {
      output += `${c.dim}${line}${c.reset}\n`;
    }
  }

  // Branch collision detection: warn if two slots share a non-main branch
  const branchMap = new Map<string, string[]>();
  for (const info of infos) {
    if (info.branch !== 'main' && info.branch !== 'detached') {
      const existing = branchMap.get(info.branch) || [];
      existing.push(info.slot);
      branchMap.set(info.branch, existing);
    }
  }
  for (const [branch, slots] of branchMap) {
    if (slots.length > 1) {
      output += `\n${c.yellow}⚠ Branch collision: ${branch} is checked out in ${slots.join(', ')}${c.reset}`;
    }
  }

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// clean
// ---------------------------------------------------------------------------

async function clean(args: string[], options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const slots = findSlotDirs(lwDir);

  const targetSlot = args.find((a) => !a.startsWith('--'));
  if (targetSlot && !/^\d+$/.test(targetSlot)) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer' };
  }
  const toCheck = targetSlot
    ? slots.filter((s) => s.slot === parseInt(targetSlot, 10))
    : slots;

  if (toCheck.length === 0) {
    return { exitCode: 0, output: 'No agent slots to clean.' };
  }

  const cleaned: string[] = [];
  const skipped: string[] = [];

  for (const { dir, slot } of toCheck) {
    const branch = git(dir, 'branch', '--show-current');
    const porcelain = git(dir, 'status', '--porcelain');
    const dirty = porcelain ? porcelain.split('\n').filter(Boolean).length : 0;

    if (branch !== 'main' || dirty > 0) {
      const reasons: string[] = [];
      if (branch !== 'main') reasons.push(`on branch ${branch}`);
      if (dirty > 0) reasons.push(`${dirty} uncommitted changes`);
      skipped.push(`  a${slot}: ${reasons.join(', ')}`);
      continue;
    }

    if (!options.force) {
      skipped.push(`  a${slot}: idle (use --force to remove)`);
      continue;
    }

    rmSync(dir, { recursive: true, force: true });
    cleaned.push(`  ✓ a${slot} removed`);
  }

  let output = '';
  if (cleaned.length > 0) {
    output += `Cleaned ${cleaned.length} slot(s):\n${cleaned.join('\n')}\n`;
  }
  if (skipped.length > 0) {
    output += `Skipped ${skipped.length} slot(s):\n${skipped.join('\n')}\n`;
  }

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// open
// ---------------------------------------------------------------------------

async function open(args: string[], _options: CommandOptions): Promise<CommandResult> {
  const slotArg = args.find((a) => !a.startsWith('--'));
  if (!slotArg) {
    return { exitCode: 1, output: 'Usage: crux sys agent-workspace open <N> [--claude]\n\nOpens a tmux window at the agent slot directory.' };
  }

  if (!process.env.TMUX) {
    return { exitCode: 1, output: 'Error: Not inside a tmux session. Run this from within tmux.' };
  }

  if (!/^\d+$/.test(slotArg)) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer.' };
  }
  const slot = parseInt(slotArg, 10);
  if (slot < 1) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer.' };
  }

  const lwDir = getLwDir();
  const slotDir = join(lwDir, `a${slot}`);

  if (!existsSync(slotDir)) {
    return { exitCode: 1, output: `Error: Slot a${slot} does not exist at ${slotDir}. Run setup first.` };
  }

  const withClaude = args.includes('--claude');

  // Check if a window for this slot already exists — match by pane CWD, not window name
  // (window names get renamed to A${slot}:${branch} by hooks, so exact name match fails)
  // Use startsWith to handle cases where the user cd'd into a subdirectory
  const windows = listTmuxWindows();
  for (const win of windows) {
    if (win.cwd === slotDir || win.cwd.startsWith(slotDir + '/')) {
      try {
        execFileSync('tmux', ['select-window', '-t', String(win.index)], { stdio: 'inherit' });
        return { exitCode: 0, output: `Switched to existing tmux window for slot a${slot}` };
      } catch { /* fall through to create */ }
    }
  }

  // Overlay latest hooks before starting — old branches revert hook files
  overlayHooks(lwDir, slotDir);

  // Include current branch in initial window name
  const branch = git(slotDir, 'branch', '--show-current') || 'detached';
  const fullWindowName = sanitizeForTmux(`A${slot}:${branch}`);

  // Isolate tsx compile cache per-slot. tmux's `-e KEY=VALUE` sets the env var
  // on the new window; the shell + any `pnpm crux ...` invocations inside it
  // inherit it. See tsx-cache-isolation.ts.
  const slotTmpDir = ensureSlotTmpDir(slot);
  const tmuxArgs = ['new-window', '-n', fullWindowName, '-c', slotDir, '-e', `TMPDIR=${slotTmpDir}`];
  if (withClaude) tmuxArgs.push('claude');

  try {
    execFileSync('tmux', tmuxArgs, { stdio: 'inherit' });
    return { exitCode: 0, output: `Opened tmux window ${fullWindowName} at ${slotDir}${withClaude ? ' (with claude)' : ''}` };
  } catch (e) {
    return { exitCode: 1, output: `Error opening tmux window: ${e instanceof Error ? e.message : String(e)}` };
  }
}

// ---------------------------------------------------------------------------
// refresh
// ---------------------------------------------------------------------------

async function refresh(_args: string[], _options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const slots = findSlotDirs(lwDir);

  if (slots.length === 0) {
    return { exitCode: 0, output: 'No agent slots found.' };
  }

  const updated: string[] = [];
  const skipped: string[] = [];
  const cleaned: string[] = [];

  for (const { dir, slot } of slots) {
    const branch = git(dir, 'branch', '--show-current');

    // Clean stale stashes from ALL slots (stashes cause branch confusion)
    const stashList = git(dir, 'stash', 'list');
    if (stashList) {
      const stashCount = stashList.split('\n').filter(Boolean).length;
      try {
        execSync('git stash clear', { cwd: dir, encoding: 'utf-8', timeout: 10000 });
        cleaned.push(`  a${slot}: cleared ${stashCount} stale stash(es)`);
      } catch {
        cleaned.push(`  a${slot}: failed to clear ${stashCount} stash(es)`);
      }
    }

    // Clean stale active-branch lock file from idle slots on main
    const activeBranchFile = join(dir, '.claude', 'active-branch');
    if (branch === 'main' && existsSync(activeBranchFile)) {
      try {
        const { unlinkSync } = await import('fs');
        unlinkSync(activeBranchFile);
      } catch { /* ignore */ }
    }

    if (branch !== 'main') {
      // Check if the slot is clean and on a merged branch — safe to reclaim
      const porcelain = git(dir, 'status', '--porcelain');
      if (!porcelain) {
        const mergedBranches = git(dir, 'branch', '--merged', 'origin/main');
        if (mergedBranches.split('\n').some((b) => b.trim() === branch)) {
          try {
            execSync('git checkout main', { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
            execSync('git pull --ff-only origin main', { cwd: dir, encoding: 'utf-8', timeout: 30000, stdio: 'pipe' });
            execFileSync('git', ['branch', '-d', branch], { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
            // Repair .agent-slot — git operations may overwrite it if still tracked
            writeFileSync(join(dir, '.agent-slot'), String(slot) + '\n');
            updated.push(`  a${slot}: returned to main (${branch} was merged)`);
            continue;
          } catch {
            skipped.push(`  a${slot}: on merged branch ${branch} but checkout failed`);
            continue;
          }
        }
      }
      skipped.push(`  a${slot}: on branch ${branch}`);
      continue;
    }

    const porcelain = git(dir, 'status', '--porcelain');
    if (porcelain) {
      skipped.push(`  a${slot}: has uncommitted changes`);
      continue;
    }

    // Prune stale local branches that have been merged
    try {
      const mergedBranches = git(dir, 'branch', '--merged', 'origin/main');
      const staleBranches = mergedBranches
        .split('\n')
        .map((b) => b.trim())
        .filter((b) => b && b !== 'main' && !b.startsWith('*'));
      for (const staleBranch of staleBranches) {
        try {
          execFileSync('git', ['branch', '-d', staleBranch], { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
          cleaned.push(`  a${slot}: pruned merged branch ${staleBranch}`);
        } catch { /* branch delete failed — skip */ }
      }
    } catch { /* branch listing failed — skip */ }

    try {
      execSync('git pull --ff-only origin main', { cwd: dir, encoding: 'utf-8', timeout: 30000, stdio: 'pipe' });
      // Repair .agent-slot — git operations may overwrite it if still tracked
      writeFileSync(join(dir, '.agent-slot'), String(slot) + '\n');
      updated.push(`  a${slot}: pulled latest main`);
    } catch (e) {
      skipped.push(`  a${slot}: git pull failed (${e instanceof Error ? e.message.split('\n')[0] : 'unknown error'})`);
    }
  }

  let output = '';
  if (updated.length > 0) {
    output += `Updated ${updated.length} slot(s):\n${updated.join('\n')}\n`;
  }
  if (cleaned.length > 0) {
    output += `Cleaned:\n${cleaned.join('\n')}\n`;
  }
  if (skipped.length > 0) {
    output += `Skipped ${skipped.length} slot(s):\n${skipped.join('\n')}\n`;
  }
  if (updated.length === 0 && skipped.length === 0 && cleaned.length === 0) {
    output = 'No slots to refresh.';
  }

  // Overlay latest hooks from main/ to all slots — prevents old branches
  // from reverting critical fixes (e.g., -t $TMUX_PANE in heartbeat.sh)
  let hooksOverlaid = 0;
  for (const { dir } of slots) {
    if (overlayHooks(lwDir, dir)) hooksOverlaid++;
  }
  if (hooksOverlaid > 0) {
    output += `Hooks: overlaid latest from main/ to ${hooksOverlaid} slot(s)\n`;
  }

  // Rename tmux windows to match current state after refresh
  const tabsRenamed = renameTmuxWindows(lwDir);
  if (tabsRenamed.length > 0) {
    output += `Tmux tabs renamed:\n${tabsRenamed.join('\n')}\n`;
  }

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// fix-tabs — rename tmux windows to match actual slot + branch
// ---------------------------------------------------------------------------

/**
 * Read the @lw-coord-role marker for every tmux window.
 *
 * Returns a map of window-index → role string ("slots"|"releases") for windows
 * that have the marker set. Requires tmux ≥ 3.0 for `#{@user-option}` format
 * substitution; older tmux returns an empty map (caller falls back to the
 * pre-marker behavior, which is safe because the rename loop just renames
 * everything as before).
 */
function readRoleMarkers(): Map<string, string> {
  const markers = new Map<string, string>();
  // Probe tmux version once. <3.0 doesn't support #{@user-option} → bail.
  try {
    const version = execSync('tmux -V', { encoding: 'utf-8', timeout: 3000 }).trim();
    const m = version.match(/(\d+)\.(\d+)/);
    if (!m || Number(m[1]) < 3) return markers;
  } catch {
    return markers;
  }
  try {
    const raw = execSync(
      `tmux list-windows -a -F '#{window_index}|||#{@lw-coord-role}'`,
      { encoding: 'utf-8', timeout: 5000 },
    );
    for (const line of raw.split('\n')) {
      if (!line.trim()) continue;
      const parts = line.split('|||');
      if (parts.length < 2) continue;
      const role = parts[1].trim();
      if (role === 'slots' || role === 'releases') markers.set(parts[0], role);
    }
  } catch { /* ignore — empty marker map is harmless */ }
  return markers;
}

/** Scan all tmux windows and rename those whose pane CWD is an agent slot or the coordinator */
function renameTmuxWindows(lwDir: string): string[] {
  if (!process.env.TMUX) return [];

  const windows = listTmuxWindows();
  const roleMarkers = readRoleMarkers();
  const renamed: string[] = [];

  for (const win of windows) {
    // Coordinator-claimed window: skip entirely so /agent-slots-start and
    // /agent-releases-start can keep their chosen window names. The marker
    // is set BEFORE rename inside claimWindow() so we never miss it here.
    if (roleMarkers.has(win.index)) continue;

    // Coordinator window — lw/ root (not a slot)
    if (win.cwd === lwDir) {
      if (win.name !== 'LW') {
        try {
          execFileSync('tmux', ['rename-window', '-t', String(win.index), 'LW'], { timeout: 5000 });
          renamed.push(`  LW: ${win.name} → LW`);
        } catch { /* ignore */ }
      }
      continue;
    }

    // Check if this pane is in an agent slot directory under lw/
    const match = win.cwd.match(/\/a(\d+)$/);
    if (!match) continue;

    const expectedDir = join(lwDir, `a${match[1]}`);
    if (win.cwd !== expectedDir) continue;

    const slot = match[1];
    const branch = git(win.cwd, 'branch', '--show-current') || 'detached';
    const newName = sanitizeForTmux(`A${slot}:${branch}`);

    if (win.name !== newName) {
      try {
        execFileSync('tmux', ['rename-window', '-t', String(win.index), newName], { timeout: 5000 });
        renamed.push(`  A${slot}: ${win.name} → ${newName}`);
      } catch { /* tmux rename can fail if window was closed between query and rename */ }
    }
  }

  return renamed;
}

async function fixTabs(_args: string[], _options: CommandOptions): Promise<CommandResult> {
  if (!process.env.TMUX) {
    return { exitCode: 1, output: 'Error: Not inside a tmux session.' };
  }

  const lwDir = getLwDir();
  const renamed = renameTmuxWindows(lwDir);

  if (renamed.length === 0) {
    return { exitCode: 0, output: 'All tmux tabs already correct.' };
  }

  return {
    exitCode: 0,
    output: `Renamed ${renamed.length} tab(s):\n${renamed.join('\n')}`,
  };
}

// ---------------------------------------------------------------------------
// dispatch / dispatch-status / dispatch-stop (QUA-554)
// ---------------------------------------------------------------------------

interface DispatchCliOptions extends CommandOptions {
  model?: string;
  maxBudget?: string;
  allowedTools?: string;
  appendSystemPrompt?: string;
  permissionMode?: string;
  cwd?: string;
  tail?: string;
  prompt?: string;
  promptFile?: string;
}

/** Parse the slot number from the first positional argument. */
export function parseSlot(arg: string | undefined): number | { error: string } {
  if (!arg || !/^\d+$/.test(arg)) {
    return { error: 'Slot number must be a positive integer.' };
  }
  const slot = parseInt(arg, 10);
  if (slot < 1) return { error: 'Slot number must be a positive integer.' };
  return slot;
}

/** Resolve dispatch target cwd: --cwd override OR lw/aN. */
function resolveDispatchCwd(slot: number, override?: string): { cwd: string; note: string } | { error: string } {
  if (override) {
    if (!existsSync(override)) return { error: `--cwd path does not exist: ${override}` };
    return { cwd: override, note: ` (cwd override: ${override})` };
  }
  const lwDir = getLwDir();
  const slotDir = join(lwDir, `a${slot}`);
  if (!existsSync(slotDir)) {
    return { error: `Slot a${slot} does not exist at ${slotDir}. Run setup first.` };
  }
  return { cwd: slotDir, note: '' };
}

/**
 * Resolve the prompt from (in priority order): --prompt-file, --prompt, or the
 * positional args after the slot number. Returns { prompt } or { error }.
 *
 * --prompt-file is the robust escape hatch for prompts containing `--` prefixes,
 * multi-line content, or anything the shell/arg-parser would mangle.
 */
export function resolvePrompt(
  positionalTail: string[],
  opts: { prompt?: string; promptFile?: string },
): { prompt: string } | { error: string } {
  if (opts.promptFile) {
    try {
      const body = readFileSync(opts.promptFile, 'utf-8').trim();
      if (!body) return { error: `--prompt-file is empty: ${opts.promptFile}` };
      return { prompt: body };
    } catch (e) {
      return { error: `Could not read --prompt-file=${opts.promptFile}: ${e instanceof Error ? e.message : String(e)}` };
    }
  }
  if (typeof opts.prompt === 'string' && opts.prompt.trim().length > 0) {
    return { prompt: opts.prompt };
  }
  const joined = positionalTail.join(' ').trim();
  if (!joined) {
    return {
      error:
        'prompt is required. Pass it as a quoted argument, via --prompt="...", or via --prompt-file=<path>.',
    };
  }
  return { prompt: joined };
}

/**
 * Shared preamble for all three dispatch handlers: parse slot, resolve cwd.
 * Returns either a ready-to-use context or a CommandResult-shaped error
 * (caller returns it directly).
 */
function dispatchPreamble(
  args: string[],
  options: DispatchCliOptions,
  usage: string,
):
  | { slot: number; cwd: string; cwdNote: string; positional: string[] }
  | { error: CommandResult } {
  const positional = args.filter((a) => !a.startsWith('--'));
  const slotResult = parseSlot(positional[0]);
  if (typeof slotResult === 'object' && 'error' in slotResult) {
    return { error: { exitCode: 1, output: `Error: ${slotResult.error}\n\n${usage}` } };
  }
  const cwdResult = resolveDispatchCwd(slotResult, options.cwd);
  if ('error' in cwdResult) return { error: { exitCode: 1, output: `Error: ${cwdResult.error}` } };
  return { slot: slotResult, cwd: cwdResult.cwd, cwdNote: cwdResult.note, positional };
}

/** Validate / clamp --max-budget. */
export function parseMaxBudget(raw: string | undefined): { value: number | undefined } | { error: string } {
  if (raw === undefined) return { value: undefined };
  const n = Number(raw);
  if (Number.isNaN(n) || n <= 0) {
    return { error: `--max-budget must be a positive number (got: ${raw}).` };
  }
  return { value: n };
}

async function dispatchCmd(args: string[], options: DispatchCliOptions): Promise<CommandResult> {
  const usage = 'Usage: crux sys agent-workspace dispatch <N> "<prompt>" [options]';
  const ctx = dispatchPreamble(args, options, usage);
  if ('error' in ctx) return ctx.error;
  const { slot, cwd, cwdNote, positional } = ctx;

  const promptResult = resolvePrompt(positional.slice(1), options);
  if ('error' in promptResult) {
    return { exitCode: 1, output: `Error: ${promptResult.error}\n\n${usage}` };
  }
  const prompt = promptResult.prompt;

  if (options.permissionMode !== undefined && !isPermissionMode(options.permissionMode)) {
    return {
      exitCode: 1,
      output: `Error: --permission-mode=${options.permissionMode} is not a recognized claude mode. Allowed: default, acceptEdits, bypassPermissions, plan, auto, dontAsk.`,
    };
  }
  const permissionMode: PermissionMode | undefined = isPermissionMode(options.permissionMode)
    ? options.permissionMode
    : undefined;

  const budgetResult = parseMaxBudget(options.maxBudget);
  if ('error' in budgetResult) {
    return { exitCode: 1, output: `Error: ${budgetResult.error}` };
  }
  const maxBudgetUsd = budgetResult.value;

  const env = realDispatchEnv();
  const paths = makeDispatchPaths(cwd);

  if (!options.force) {
    const conflict = detectDispatchConflict(env, paths);
    if (conflict) {
      return {
        exitCode: 1,
        output:
          `Error: slot a${slot} already has an active dispatch.\n` +
          `  run: ${conflict.runId}  pid: ${conflict.pid}  session: ${conflict.sessionId}\n` +
          `  started: ${conflict.startedAt}\n` +
          `Use 'dispatch-status ${slot}' to watch, 'dispatch-stop ${slot}' to cancel, or --force to override.`,
      };
    }
  } else {
    // --force: SIGTERM the previous worker (if any) and stamp its meta with
    // terminalReason=superseded so abandoned runs aren't indistinguishable
    // from crashes in .dispatch/runs/.
    supersedeDispatch(env, paths);
  }
  clearDispatchCurrent(env, paths);

  const dispatchOpts: DispatchOptions = {
    slot,
    cwd,
    prompt,
    model: options.model,
    maxBudgetUsd,
    allowedTools: options.allowedTools,
    appendSystemPrompt: options.appendSystemPrompt,
    permissionMode,
    force: !!options.force,
    // Isolate tsx compile cache per-slot to eliminate cross-slot fs contention
    // that has caused 25+ minute hangs under heavy concurrent load.
    tmpDir: ensureSlotTmpDir(slot),
  };

  // Alarm bell for QUA-1010/QUA-1057: a parent shell with ANTHROPIC_API_KEY set
  // (e.g., inherited from .env.base) used to make the dispatched worker silently
  // die in ~160ms with "Credit balance is too low" because claude reads the key
  // and switches to API-direct billing. We strip it inside spawnDetached, but
  // also surface a warning so an operator can untangle the env if desired.
  const apiKeyWarning = formatApiKeyWarning(process.env);

  let result;
  try {
    result = spawnDispatch(env, paths, dispatchOpts);
  } catch (e) {
    return { exitCode: 1, output: `Error spawning claude: ${e instanceof Error ? e.message : String(e)}` };
  }

  const { handle } = result;
  const warnings = apiKeyWarning ? [apiKeyWarning] : [];
  const basePayload = {
    slot,
    runId: handle.runId,
    sessionId: handle.sessionId,
    pid: handle.pid,
    runDir: handle.runDir,
    cwd,
    startedAt: handle.startedAt,
    cmd: handle.cmd,
  };

  // Briefly poll for early errors so credit-low / auth failures surface as
  // dispatch failures instead of "Dispatched to slot aN" + silent death. See
  // QUA-1057 for the original symptom. Healthy workers exit on the first
  // events.jsonl write (~100ms); cold-spawn-die paths use the pidAlive guard.
  const earlyError = await pollForEarlyDispatchError(env, handle.eventsFile, { pid: handle.pid });
  if (earlyError) {
    const statusSuffix = earlyError.status !== undefined ? ` (HTTP ${earlyError.status})` : '';
    const stripHint = apiKeyWarning
      ? `\n  hint: parent env had the API key set; even after stripping, the OAuth subscription itself may have failed (check 'claude /login').`
      : '';
    const errorOutput =
      `Error: dispatched worker exited early on slot a${slot}: ${earlyError.message}${statusSuffix}\n` +
      `  run:    ${handle.runId}\n` +
      `  events: ${handle.eventsFile}\n` +
      `  stderr: ${handle.stderrFile}` +
      stripHint;
    if (options.json) {
      return {
        exitCode: 2,
        output: JSON.stringify({ ...basePayload, earlyError, warnings }, null, 2),
      };
    }
    return { exitCode: 2, output: errorOutput };
  }

  const successHeader = apiKeyWarning ? `${apiKeyWarning}\n\n` : '';
  const output =
    successHeader +
    `Dispatched to slot a${slot}${cwdNote}\n` +
    `  run:      ${handle.runId}\n` +
    `  session:  ${handle.sessionId}\n` +
    `  pid:      ${handle.pid}\n` +
    `  run dir:  ${handle.runDir}\n` +
    `\n` +
    `Watch:    crux sys agent-workspace dispatch-status ${slot}\n` +
    `Cancel:   crux sys agent-workspace dispatch-stop ${slot}\n` +
    `Resume:   claude -c ${handle.sessionId}  (if worker crashes before completing)\n`;

  if (options.json) {
    return {
      exitCode: 0,
      output: JSON.stringify({ ...basePayload, warnings }, null, 2),
    };
  }
  return { exitCode: 0, output };
}

async function dispatchStatusCmd(args: string[], options: DispatchCliOptions): Promise<CommandResult> {
  const ctx = dispatchPreamble(args, options, 'Usage: crux sys agent-workspace dispatch-status <N> [--tail=N] [--json]');
  if ('error' in ctx) return ctx.error;
  const { slot, cwd } = ctx;

  const tail = options.tail ? Math.max(1, parseInt(options.tail, 10) || 0) : 10;

  const env = realDispatchEnv();
  const paths = makeDispatchPaths(cwd);

  const current = readDispatchCurrent(env, paths);
  if (!current) {
    return { exitCode: 0, output: `No active dispatch on slot a${slot}.` };
  }

  const rp = makeRunPaths(paths, current.runId);
  let meta = readDispatchMeta(env, rp);
  if (!meta) {
    return { exitCode: 1, output: `Error: current.json points at run ${current.runId} but meta.json is missing.` };
  }

  meta = finalizeDispatchIfComplete(env, paths, rp, meta);

  const events = parseDispatchEvents(env, rp.eventsFile);
  const alive = env.pidAlive(current.pid);
  const elapsedMs = Date.parse(env.now().toISOString()) - Date.parse(current.startedAt);
  const elapsedSec = Math.max(0, Math.floor(elapsedMs / 1000));

  if (options.json) {
    return {
      exitCode: 0,
      output: JSON.stringify(
        {
          slot,
          runId: current.runId,
          sessionId: current.sessionId,
          pid: current.pid,
          pidAlive: alive,
          startedAt: current.startedAt,
          elapsedSeconds: elapsedSec,
          meta,
          events,
        },
        null,
        2,
      ),
    };
  }

  const status = meta.completedAt
    ? `complete (${meta.terminalReason ?? 'unknown'})`
    : alive
      ? 'running'
      : 'dead (no result event)';

  const lines: string[] = [];
  lines.push(`Slot a${slot} dispatch status: ${status}`);
  lines.push(`  run:     ${current.runId}`);
  lines.push(`  session: ${current.sessionId}`);
  lines.push(`  pid:     ${current.pid}  alive=${alive}`);
  lines.push(`  started: ${current.startedAt}  (${elapsedSec}s ago)`);
  lines.push(`  prompt:  ${truncate(meta.prompt, 120)}`);
  if (meta.totalCostUsd !== undefined) {
    lines.push(`  cost:    $${meta.totalCostUsd.toFixed(4)}  turns: ${meta.numTurns}  duration: ${((meta.durationMs ?? 0) / 1000).toFixed(1)}s`);
  }
  lines.push('');
  lines.push(`Last ${Math.min(tail, events.length)} of ${events.length} events:`);
  for (const evt of events.slice(-tail)) {
    lines.push(`  [${evt.kind}] ${evt.summary}`);
  }

  return { exitCode: 0, output: lines.join('\n') };
}

async function dispatchStopCmd(args: string[], options: DispatchCliOptions): Promise<CommandResult> {
  const ctx = dispatchPreamble(args, options, 'Usage: crux sys agent-workspace dispatch-stop <N>');
  if ('error' in ctx) return ctx.error;
  const { slot, cwd } = ctx;

  const env = realDispatchEnv();
  const paths = makeDispatchPaths(cwd);

  const current = readDispatchCurrent(env, paths);
  if (!current) {
    return { exitCode: 0, output: `No active dispatch on slot a${slot}.` };
  }

  const rp = makeRunPaths(paths, current.runId);
  let meta = readDispatchMeta(env, rp);

  // If the worker completed naturally between the last status call and this
  // stop, finalize first so cost / duration / numTurns / exitCode get captured
  // before the stoppedAt marker overwrites the run shape.
  if (meta) meta = finalizeDispatchIfComplete(env, paths, rp, meta);

  const alive = env.pidAlive(current.pid);
  if (alive) {
    env.signal(current.pid, 'SIGTERM');
    // Give the worker up to 3s to drain before escalating to SIGKILL.
    const deadline = Date.now() + 3000;
    while (Date.now() < deadline && env.pidAlive(current.pid)) {
      await new Promise<void>((resolve) => setTimeout(resolve, 50));
    }
    if (env.pidAlive(current.pid)) {
      env.signal(current.pid, 'SIGKILL');
    }
  }

  if (meta) {
    const updated = {
      ...meta,
      stoppedAt: env.now().toISOString(),
      terminalReason: meta.terminalReason ?? 'stopped',
    };
    writeDispatchMeta(env, rp, updated);
  }
  clearDispatchCurrent(env, paths);

  const lines = [
    `Stopped dispatch on slot a${slot}.`,
    `  run:     ${current.runId}`,
    `  session: ${current.sessionId}  (resume with: claude -c ${current.sessionId})`,
    `  pid:     ${current.pid}  (was ${alive ? 'alive → SIGTERM sent' : 'already dead'})`,
  ];
  return { exitCode: 0, output: lines.join('\n') };
}

// ---------------------------------------------------------------------------
// Sentinel + tmux-claim + doctor (QUA-339)
// ---------------------------------------------------------------------------

interface RoleOptions extends CommandOptions {
  role?: string;
}

function parseRole(opts: RoleOptions): Role | { error: string } {
  const v = opts.role;
  if (v === 'slots' || v === 'releases') return v;
  return { error: `--role must be 'slots' or 'releases' (got: ${v ?? 'missing'})` };
}

/** Real-world SentinelEnv backed by node:fs and live tmux. */
function makeSentinelEnv(): SentinelEnv {
  return {
    now: () => new Date(),
    env: process.env,
    hostname: () => os.hostname(),
    uid: () => (typeof process.getuid === 'function' ? process.getuid() : 0),
    ppid: () => process.ppid,
    readFile(path) {
      try { return readFileSync(path, 'utf-8'); } catch { return null; }
    },
    writeFile(path, content) { writeFileSync(path, content); },
    touch(path) {
      const now = new Date();
      utimesSync(path, now, now);
    },
    statMtime(path) {
      try { return Math.floor(statSync(path).mtimeMs / 1000); } catch { return null; }
    },
    unlink(path) {
      try { unlinkSync(path); } catch { /* already gone */ }
    },
    listMatching(dir, prefix) {
      try {
        return readdirSync(dir)
          .filter((n) => n.startsWith(prefix))
          .map((n) => `${dir}/${n}`);
      } catch { return []; }
    },
    listTmuxPanes() {
      if (!process.env.TMUX) return null;
      try {
        const r = execFileSync('tmux', ['list-panes', '-a', '-F', '#{pane_id}'], { encoding: 'utf-8', timeout: 3000 });
        return r.split('\n').map((s) => s.trim()).filter(Boolean);
      } catch { return null; }
    },
    pidAlive(pid) {
      try { process.kill(pid, 0); return true; } catch { return false; }
    },
  };
}

/** Real-world TmuxExec backed by spawnSync. */
function makeTmuxExec(): TmuxExec {
  return {
    inTmux: () => process.env.TMUX ?? null,
    run(args: string[]): TmuxExecResult {
      const r = spawnSync('tmux', args, { encoding: 'utf-8', timeout: 5000 });
      if (r.error) {
        return { stdout: r.stdout ?? '', stderr: r.stderr ?? r.error.message, code: 1 };
      }
      return { stdout: r.stdout ?? '', stderr: r.stderr ?? '', code: r.status ?? 0 };
    },
  };
}

/** Format a thrown error for a user-facing CommandResult. */
function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

async function sentinelWrite(_args: string[], options: RoleOptions): Promise<CommandResult> {
  const role = parseRole(options);
  if (typeof role !== 'string') return { exitCode: 1, output: role.error };
  const env = makeSentinelEnv();
  try {
    const { path, sentinel } = writeSentinelImpl(role, env);
    if (options.json) {
      return { exitCode: 0, output: JSON.stringify({ ok: true, role, path, sentinel }, null, 2) };
    }
    return { exitCode: 0, output: `wrote sentinel: ${path}` };
  } catch (e) {
    const msg = `sentinel-write failed: ${errMsg(e)}`;
    return {
      exitCode: 1,
      output: options.json ? JSON.stringify({ ok: false, role, error: msg }, null, 2) : msg,
    };
  }
}

async function sentinelTouch(_args: string[], options: RoleOptions): Promise<CommandResult> {
  const role = parseRole(options);
  if (typeof role !== 'string') return { exitCode: 1, output: role.error };
  const env = makeSentinelEnv();
  try {
    const { path, touched } = touchSentinelImpl(role, env);
    if (options.json) {
      return { exitCode: 0, output: JSON.stringify({ ok: true, role, path, touched }, null, 2) };
    }
    return { exitCode: 0, output: touched ? `touched ${path}` : `(no sentinel at ${path} to touch)` };
  } catch (e) {
    const msg = `sentinel-touch failed: ${errMsg(e)}`;
    return {
      exitCode: 1,
      output: options.json ? JSON.stringify({ ok: false, role, error: msg }, null, 2) : msg,
    };
  }
}

async function sentinelCheck(_args: string[], options: RoleOptions): Promise<CommandResult> {
  const role = parseRole(options);
  if (typeof role !== 'string') return { exitCode: 1, output: role.error };
  const env = makeSentinelEnv();
  let result: ReturnType<typeof checkConflictImpl>;
  try {
    result = checkConflictImpl(role, env);
  } catch (e) {
    const msg = `sentinel-check failed: ${errMsg(e)}`;
    return {
      exitCode: 1,
      output: options.json ? JSON.stringify({ ok: false, role, error: msg }, null, 2) : msg,
    };
  }

  if (options.json) {
    const exit = result.conflict?.kind === 'same-session' ? 2 : 0;
    return {
      exitCode: exit,
      output: JSON.stringify(
        {
          ok: exit === 0,
          role,
          ourPath: result.ourPath,
          conflict: result.conflict,
          cleaned: result.cleaned,
        },
        null,
        2,
      ),
    };
  }

  if (!result.conflict) {
    const tail = result.cleaned > 0 ? ` (cleaned ${result.cleaned} stale)` : '';
    return { exitCode: 0, output: `✓ no role conflict${tail}` };
  }
  if (result.conflict.kind === 'same-session') {
    const banner = [
      '======================================================================',
      'ROLE CONFLATION DETECTED — this Claude session previously ran the',
      'OTHER coordinator startup skill.',
      '',
      '  • slots owns:   PR patrol, tmux rename, slot lifecycle, dispatch',
      '  • releases owns: ops/ writes, release PRs, deploys, prod incidents',
      '',
      'Running both in one session means: PR patrol may compete with a',
      'release window, ops edits may race PR patrol iterations, context',
      'fills twice as fast, tmux rename loops may double-fire.',
      '',
      'WHAT TO DO:',
      '  1. (RECOMMENDED) Open a new tmux window (Ctrl-b c), cd to lw/,',
      `     run the OTHER startup skill there. Leave THIS session as ${role}.`,
      '  2. (IF YOU ARE SURE) Re-run with --force to override.',
      '======================================================================',
      `existing sentinel: ${result.conflict.path}`,
    ].join('\n');
    return { exitCode: 2, output: banner };
  }
  // cross-session: expected and informational
  return {
    exitCode: 0,
    output: `✓ other role (${result.conflict.sentinel.role}) running in a DIFFERENT session — that's expected. Proceeding.`,
  };
}

async function tmuxClaim(_args: string[], options: RoleOptions): Promise<CommandResult> {
  const role = parseRole(options);
  if (typeof role !== 'string') return { exitCode: 1, output: role.error };
  const exec = makeTmuxExec();
  let result: ReturnType<typeof claimWindowImpl>;
  try {
    result = claimWindowImpl(role, exec);
  } catch (e) {
    const msg = `tmux-claim failed: ${errMsg(e)}`;
    return {
      exitCode: 1,
      output: options.json ? JSON.stringify({ ok: false, role, error: msg }, null, 2) : msg,
    };
  }
  if (options.json) {
    return { exitCode: result.status === 'error' ? 1 : 0, output: JSON.stringify(result, null, 2) };
  }
  if (result.status === 'skipped-no-tmux') {
    return { exitCode: 0, output: '(not in tmux — skipping window rename)' };
  }
  if (result.status === 'skipped-no-current') {
    return { exitCode: 0, output: `(no current tmux window — skipping: ${result.detail})` };
  }
  if (result.status === 'error') {
    return { exitCode: 1, output: `error: ${result.detail}` };
  }
  const markerNote = result.markerUnsupported
    ? ' (tmux <3.0: skipped @lw-coord-role marker)'
    : ` (marker: @lw-coord-role=${result.marker})`;
  return { exitCode: 0, output: `✓ tmux window renamed to '${result.finalName}'${markerNote}` };
}

async function doctor(args: string[], options: CommandOptions): Promise<CommandResult> {
  const which = args.find((a) => !a.startsWith('-'));
  if (which !== 'slots' && which !== 'releases') {
    return {
      exitCode: 1,
      output: 'Usage: crux ws doctor <slots|releases> [--json]',
    };
  }
  const env = realDoctorEnv(getLwDir());
  const checks = which === 'slots' ? SLOTS_CHECKS : RELEASES_CHECKS;
  const report = await runDoctor(which, checks, env);
  const output = options.json ? renderDoctorJson(report) : renderDoctorPretty(report);
  return { exitCode: doctorExitCode(report.worst), output };
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export const commands: Record<string, (args: string[], options: CommandOptions) => Promise<CommandResult>> = {
  default: list,
  setup,
  'sync-env': syncEnv,
  list,
  clean,
  open,
  refresh,
  'fix-tabs': fixTabs,
  dispatch: dispatchCmd,
  'dispatch-status': dispatchStatusCmd,
  'dispatch-stop': dispatchStopCmd,
  'sentinel-write': sentinelWrite,
  'sentinel-check': sentinelCheck,
  'sentinel-touch': sentinelTouch,
  'tmux-claim': tmuxClaim,
  doctor,
};

export function getHelp(): string {
  return `
Agent Workspace — Local multi-agent directory management

Manages the lw/ directory structure for running multiple Claude Code agents
in parallel, each with its own clone and port configuration.

Directory layout:
  lw/
    .env.base       Shared API keys (single source of truth)
    main/           Primary working copy
    a1/ ... a10/    Agent slots (independent clones)

Commands:
  setup <N>         Initialize agent slot N (clone + .env + .agent-slot)
  sync-env          Regenerate .env for all slots from .env.base
  list              Show all slots with branch, PR, and port info (default)
  clean [N]         Show idle slots; use --force to remove them
  open <N>          Open a tmux window at slot N (--claude to launch claude)
  refresh           Pull latest main in idle slots (on main, clean)
  fix-tabs          Rename tmux tabs to match actual slot + branch

Dispatch — headless claude -p workers (QUA-554):
  dispatch <N> "<prompt>"    Spawn a one-shot claude -p worker in slot N
                             Prompt sources (checked in order):
                                      --prompt-file=<path>   robust for multiline / leading --
                                      --prompt="<text>"       inline alternative
                                      positional args after slot (normal case)
                             Options: --model=<sonnet|opus|haiku> (default sonnet)
                                      --max-budget=<usd> (default 5)
                                      --allowed-tools=<list> (default Bash,Edit,Read,Write,Grep,Glob)
                                      --append-system-prompt=<text>
                                      --permission-mode=<default|acceptEdits|bypassPermissions|plan|dontAsk>
                                      --cwd=<path> (override slot dir; testing)
                                      --force (ignore existing dispatch)
  dispatch-status <N>        Show active/most-recent dispatch: pid, last events, cost
                             Options: --tail=<N> (events to show, default 10), --json
  dispatch-stop <N>          SIGTERM the active worker; preserves session_id for resume

Coordinator lifecycle (QUA-339):
  sentinel-write   --role=slots|releases  Write the role-conflation sentinel
  sentinel-touch   --role=slots|releases  Refresh sentinel mtime (long sessions)
  sentinel-check   --role=slots|releases  Detect conflict; exit 2 = same-session
  tmux-claim       --role=slots|releases  Rename window + set @lw-coord-role marker
  doctor slots                            Run all 11 slots-doctor checks
  doctor releases                         Run all 12 releases-doctor checks
  (all support --json for skill consumption)

Port assignments (deterministic from slot number):
  Agent N → Next.js on port (3010+N), wiki-server on port (3110+N)
  e.g. slot 1 → 3011/3111, slot 10 → 3020/3120

Options:
  --force    Force re-init (setup) or actually delete (clean)
  --json     JSON output (list)

Examples:
  crux sys agent-workspace setup 3           Create agent slot a3
  crux sys agent-workspace sync-env          Regenerate .env for all slots
  crux sys agent-workspace list              Show all slots and their status
  crux sys agent-workspace clean --force     Remove idle slots (on main, no changes)
`;
}
