/**
 * Agent Workspace Command Handlers — Local multi-agent directory management
 *
 * Manages the `lw/` directory structure for running multiple Claude Code agents
 * in parallel, each with its own clone and port configuration.
 *
 * Usage:
 *   crux agent-workspace setup <N>       Initialize agent slot N (clone + .env + .agent-slot)
 *   crux agent-workspace sync-env        Regenerate .env for all agent slots from .env.base
 *   crux agent-workspace list            Show all agent slots with branch/PR/status info
 *   crux agent-workspace clean [N]       Remove idle agent slots (on main, no changes)
 *   crux agent-workspace reset <N|all>   Reset merged-PR slots back to main
 */

import { existsSync, readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { execSync } from 'child_process';
import type { CommandOptions as BaseOptions, CommandResult } from '../lib/command-types.ts';
import { PROJECT_ROOT } from '../lib/content-types.ts';
import { getColors } from '../lib/output.ts';

interface CommandOptions extends BaseOptions {
  ci?: boolean;
  json?: boolean;
  force?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Resolve the `lw/` parent directory (sibling to the repo) */
function getLwDir(): string {
  // PROJECT_ROOT is the repo root (e.g., /Users/.../lw/a3 or /Users/.../longterm-wiki)
  // The lw/ dir is the parent when running from an agent slot,
  // or needs to be explicitly at the same level as the repo.
  const parent = dirname(PROJECT_ROOT);
  const dirName = PROJECT_ROOT.split('/').pop() || '';

  // If we're already inside lw/aN or lw/main, parent is lw/
  if (/^(a\d+|main)$/.test(dirName) && parent.endsWith('/lw')) {
    return parent;
  }

  // Otherwise, lw/ is a sibling directory
  return join(parent, 'lw');
}

function getGitRemoteUrl(): string {
  try {
    return execSync('git remote get-url origin', { cwd: PROJECT_ROOT, encoding: 'utf-8' }).trim();
  } catch {
    return 'git@github.com:quantified-uncertainty/longterm-wiki.git';
  }
}

/** Read the slot number from a directory's .agent-slot file */
function readSlot(dir: string): number | null {
  try {
    const raw = readFileSync(join(dir, '.agent-slot'), 'utf-8').trim();
    const n = parseInt(raw, 10);
    return Number.isInteger(n) && n > 0 ? n : null;
  } catch {
    return null;
  }
}

/** Find all agent slot directories under lw/ */
function findSlotDirs(lwDir: string): Array<{ dir: string; slot: number }> {
  if (!existsSync(lwDir)) return [];

  const entries = readdirSync(lwDir).filter((name) => /^a\d+$/.test(name));
  const results: Array<{ dir: string; slot: number }> = [];

  for (const name of entries) {
    const dir = join(lwDir, name);
    if (!statSync(dir).isDirectory()) continue;
    const slot = readSlot(dir);
    if (slot !== null) {
      results.push({ dir, slot });
    }
  }

  return results.sort((a, b) => a.slot - b.slot);
}

/** Generate .env content from .env.base + port overrides for a given slot */
function generateEnv(envBasePath: string, slot: number): string {
  const base = readFileSync(envBasePath, 'utf-8');

  // Remove any existing port-related lines from base
  const filtered = base
    .split('\n')
    .filter((line) => {
      const key = line.split('=')[0]?.trim();
      return !['DEV_PORT', 'PORT', 'LONGTERMWIKI_SERVER_URL', 'PLAYWRIGHT_BASE_URL'].includes(key);
    })
    .join('\n');

  const portBlock = [
    '',
    `# Agent ${slot} port config (auto-generated by crux agent-workspace)`,
    `DEV_PORT=${3010 + slot}`,
    `PORT=${3110 + slot}`,
    `LONGTERMWIKI_SERVER_URL=http://localhost:${3110 + slot}`,
    `PLAYWRIGHT_BASE_URL=http://localhost:${3010 + slot}`,
    '',
  ].join('\n');

  return filtered.trimEnd() + '\n' + portBlock;
}

/** Run a git command in a directory and return trimmed output */
function git(dir: string, ...args: string[]): string {
  try {
    return execSync(`git ${args.join(' ')}`, { cwd: dir, encoding: 'utf-8', timeout: 10000 }).trim();
  } catch {
    return '';
  }
}

// ---------------------------------------------------------------------------
// setup
// ---------------------------------------------------------------------------

async function setup(args: string[], options: CommandOptions): Promise<CommandResult> {
  const slotArg = args.find((a) => !a.startsWith('--'));
  if (!slotArg) {
    return {
      exitCode: 1,
      output: `Usage: crux agent-workspace setup <N>

  Initialize agent slot N with a fresh clone, .env, and .agent-slot file.

  Creates lw/aN/ with:
    - Git clone of the repository
    - .agent-slot file (contains the slot number)
    - .env generated from lw/.env.base with per-agent port overrides

  Port assignments (deterministic from slot number):
    Agent N → Next.js on port (3010+N), wiki-server on port (3110+N)
    e.g. slot 1 → 3011/3111, slot 10 → 3020/3120

Options:
  --force    Re-initialize even if the slot directory already exists`,
    };
  }

  if (!/^\d+$/.test(slotArg)) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer' };
  }
  const slot = parseInt(slotArg, 10);
  if (slot < 1 || slot > 99) {
    return { exitCode: 1, output: 'Error: Slot number must be between 1 and 99' };
  }

  const lwDir = getLwDir();
  const slotDir = join(lwDir, `a${slot}`);
  const envBasePath = join(lwDir, '.env.base');

  // Ensure lw/ exists
  if (!existsSync(lwDir)) {
    execSync(`mkdir -p "${lwDir}"`);
  }

  // Check for .env.base
  if (!existsSync(envBasePath)) {
    return {
      exitCode: 1,
      output: `Error: ${envBasePath} not found.\n\nCreate it first by copying your .env (without port-specific lines):\n  cp ${PROJECT_ROOT}/.env ${envBasePath}`,
    };
  }

  // Clone if needed
  if (existsSync(slotDir)) {
    if (!options.force) {
      const existingSlot = readSlot(slotDir);
      if (existingSlot !== null) {
        return {
          exitCode: 0,
          output: `Slot a${slot} already exists at ${slotDir}. Use --force to re-initialize .env and .agent-slot.`,
        };
      }
    }
  } else {
    const remote = getGitRemoteUrl();
    console.error(`Cloning ${remote} → ${slotDir}...`);
    execSync(`git clone "${remote}" "${slotDir}"`, { stdio: 'inherit', timeout: 300000 });
  }

  // Write .agent-slot
  writeFileSync(join(slotDir, '.agent-slot'), String(slot) + '\n');

  // Generate .env
  const envContent = generateEnv(envBasePath, slot);
  writeFileSync(join(slotDir, '.env'), envContent);

  let output = `✓ Agent slot a${slot} ready at ${slotDir}\n`;
  output += `  Next.js:     http://localhost:${3010 + slot}\n`;
  output += `  Wiki-server: http://localhost:${3110 + slot}\n`;
  output += `  .env:        generated from .env.base\n`;
  output += `\nNext steps:\n`;
  output += `  cd ${slotDir} && pnpm install && pnpm setup:quick\n`;

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// sync-env
// ---------------------------------------------------------------------------

async function syncEnv(_args: string[], _options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const envBasePath = join(lwDir, '.env.base');

  if (!existsSync(envBasePath)) {
    return {
      exitCode: 1,
      output: `Error: ${envBasePath} not found.`,
    };
  }

  const slots = findSlotDirs(lwDir);
  if (slots.length === 0) {
    return { exitCode: 0, output: 'No agent slots found.' };
  }

  const lines: string[] = [];
  for (const { dir, slot } of slots) {
    const envContent = generateEnv(envBasePath, slot);
    writeFileSync(join(dir, '.env'), envContent);

    // Remove apps/web/.env.local if it exists — it overrides root .env values
    const webEnvLocal = join(dir, 'apps', 'web', '.env.local');
    if (existsSync(webEnvLocal)) {
      execSync(`rm -f "${webEnvLocal}"`);
      lines.push(`  ✓ a${slot}/.env regenerated (ports ${3010 + slot}/${3110 + slot}) — removed stale apps/web/.env.local`);
    } else {
      lines.push(`  ✓ a${slot}/.env regenerated (ports ${3010 + slot}/${3110 + slot})`);
    }
  }

  return {
    exitCode: 0,
    output: `Synced .env for ${slots.length} agent slot(s) from ${envBasePath}:\n${lines.join('\n')}`,
  };
}

// ---------------------------------------------------------------------------
// list
// ---------------------------------------------------------------------------

async function list(_args: string[], options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const slots = findSlotDirs(lwDir);

  // Also check for lw/main
  const mainDir = join(lwDir, 'main');
  const hasMain = existsSync(mainDir) && statSync(mainDir).isDirectory();

  if (slots.length === 0 && !hasMain) {
    return { exitCode: 0, output: `No agent workspace found at ${lwDir}` };
  }

  interface SlotInfo {
    slot: string;
    branch: string;
    dirty: number;
    pr: string;
    ports: string;
  }

  const infos: SlotInfo[] = [];

  if (hasMain) {
    const branch = git(mainDir, 'branch', '--show-current') || 'detached';
    const mainPorcelain = git(mainDir, 'status', '--porcelain');
    const dirty = mainPorcelain ? mainPorcelain.split('\n').filter(Boolean).length : 0;
    infos.push({ slot: 'main', branch, dirty, pr: '', ports: 'default' });
  }

  for (const { dir, slot } of slots) {
    const branch = git(dir, 'branch', '--show-current') || 'detached';
    const porcelain = git(dir, 'status', '--porcelain');
    const dirty = porcelain ? porcelain.split('\n').filter(Boolean).length : 0;

    // Try to get PR number (best-effort, don't fail if gh isn't available)
    let pr = '';
    try {
      const prJson = execSync(
        `gh pr view --json number,state --jq '"#" + (.number|tostring) + " " + .state' 2>/dev/null`,
        { cwd: dir, encoding: 'utf-8', timeout: 10000 },
      ).trim();
      if (prJson) pr = prJson;
    } catch {
      // No PR or gh not available
    }

    infos.push({
      slot: `a${slot}`,
      branch,
      dirty,
      pr,
      ports: `${3010 + slot}/${3110 + slot}`,
    });
  }

  if (options.json) {
    return { exitCode: 0, output: JSON.stringify(infos, null, 2) };
  }

  const c = getColors(options.ci);

  let output = `Agent Workspace (${lwDir})\n\n`;
  output += `  ${'Slot'.padEnd(6)} ${'Branch'.padEnd(35)} ${'Dirty'.padEnd(6)} ${'PR'.padEnd(15)} Ports\n`;
  output += `  ${'─'.repeat(6)} ${'─'.repeat(35)} ${'─'.repeat(6)} ${'─'.repeat(15)} ${'─'.repeat(12)}\n`;

  for (const info of infos) {
    const dirtyStr = info.dirty > 0 ? `${info.dirty}` : '—';
    const line = `  ${info.slot.padEnd(6)} ${info.branch.padEnd(35)} ${dirtyStr.padEnd(6)} ${(info.pr || '—').padEnd(15)} ${info.ports}`;

    // Color: idle (main+clean) → dim, active (branch or dirty) → green, merged PR → yellow
    if (info.pr.includes('MERGED')) {
      output += `${c.yellow}${line}${c.reset}\n`;
    } else if (info.branch !== 'main' || info.dirty > 0) {
      output += `${c.green}${line}${c.reset}\n`;
    } else {
      output += `${c.dim}${line}${c.reset}\n`;
    }
  }

  // Merged-PR hint
  const mergedSlots = infos.filter((i) => i.pr.includes('MERGED'));
  if (mergedSlots.length > 0) {
    output += `\n${c.yellow}${mergedSlots.length} slot(s) have merged PRs — run \`crux agent-workspace refresh\` to reset them${c.reset}\n`;
  }

  // Branch collision detection: warn if two slots share a non-main branch
  const branchMap = new Map<string, string[]>();
  for (const info of infos) {
    if (info.branch !== 'main' && info.branch !== 'detached') {
      const existing = branchMap.get(info.branch) || [];
      existing.push(info.slot);
      branchMap.set(info.branch, existing);
    }
  }
  for (const [branch, slots] of branchMap) {
    if (slots.length > 1) {
      output += `\n${c.yellow}⚠ Branch collision: ${branch} is checked out in ${slots.join(', ')}${c.reset}`;
    }
  }

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// clean
// ---------------------------------------------------------------------------

async function clean(args: string[], options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const slots = findSlotDirs(lwDir);

  const targetSlot = args.find((a) => !a.startsWith('--'));
  if (targetSlot && !/^\d+$/.test(targetSlot)) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer' };
  }
  const toCheck = targetSlot
    ? slots.filter((s) => s.slot === parseInt(targetSlot, 10))
    : slots;

  if (toCheck.length === 0) {
    return { exitCode: 0, output: 'No agent slots to clean.' };
  }

  const cleaned: string[] = [];
  const skipped: string[] = [];

  for (const { dir, slot } of toCheck) {
    const branch = git(dir, 'branch', '--show-current');
    const porcelain = git(dir, 'status', '--porcelain');
    const dirty = porcelain ? porcelain.split('\n').filter(Boolean).length : 0;

    if (branch !== 'main' || dirty > 0) {
      const reasons: string[] = [];
      if (branch !== 'main') reasons.push(`on branch ${branch}`);
      if (dirty > 0) reasons.push(`${dirty} uncommitted changes`);
      skipped.push(`  a${slot}: ${reasons.join(', ')}`);
      continue;
    }

    if (!options.force) {
      skipped.push(`  a${slot}: idle (use --force to remove)`);
      continue;
    }

    execSync(`rm -rf "${dir}"`);
    cleaned.push(`  ✓ a${slot} removed`);
  }

  let output = '';
  if (cleaned.length > 0) {
    output += `Cleaned ${cleaned.length} slot(s):\n${cleaned.join('\n')}\n`;
  }
  if (skipped.length > 0) {
    output += `Skipped ${skipped.length} slot(s):\n${skipped.join('\n')}\n`;
  }

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// open
// ---------------------------------------------------------------------------

async function open(args: string[], _options: CommandOptions): Promise<CommandResult> {
  const slotArg = args.find((a) => !a.startsWith('--'));
  if (!slotArg) {
    return { exitCode: 1, output: 'Usage: crux agent-workspace open <N> [--claude]\n\nOpens a tmux window at the agent slot directory.' };
  }

  if (!process.env.TMUX) {
    return { exitCode: 1, output: 'Error: Not inside a tmux session. Run this from within tmux.' };
  }

  if (!/^\d+$/.test(slotArg)) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer.' };
  }
  const slot = parseInt(slotArg, 10);
  if (slot < 1) {
    return { exitCode: 1, output: 'Error: Slot number must be a positive integer.' };
  }

  const lwDir = getLwDir();
  const slotDir = join(lwDir, `a${slot}`);

  if (!existsSync(slotDir)) {
    return { exitCode: 1, output: `Error: Slot a${slot} does not exist at ${slotDir}. Run setup first.` };
  }

  const withClaude = args.includes('--claude');
  const windowName = `A${slot}`;
  const devPort = 3010 + slot;
  const serverPort = 3110 + slot;

  // Build a shell command that sources .env (for env vars like API keys)
  // and exports port vars (so pnpm dev / pnpm start use the right port)
  const shellInit = `source "${slotDir}/.env" 2>/dev/null; export DEV_PORT=${devPort} PORT=${serverPort}`;
  const cmd = withClaude
    ? `${shellInit}; claude`
    : `${shellInit}; exec $SHELL`;

  try {
    execSync(`tmux new-window -n "${windowName}" -c "${slotDir}" '${cmd}'`, { stdio: 'inherit' });
    return { exitCode: 0, output: `Opened tmux window ${windowName} at ${slotDir} (ports ${devPort}/${serverPort})${withClaude ? ' with claude' : ''}` };
  } catch (e) {
    return { exitCode: 1, output: `Error opening tmux window: ${e instanceof Error ? e.message : String(e)}` };
  }
}

// ---------------------------------------------------------------------------
// refresh
// ---------------------------------------------------------------------------

async function refresh(_args: string[], _options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const slots = findSlotDirs(lwDir);

  if (slots.length === 0) {
    return { exitCode: 0, output: 'No agent slots found.' };
  }

  const resetResults: string[] = [];
  const updated: string[] = [];
  const skipped: string[] = [];

  for (const { dir, slot } of slots) {
    const branch = git(dir, 'branch', '--show-current');

    // Auto-reset slots whose PR has been merged
    if (branch !== 'main') {
      let prState = '';
      try {
        prState = execSync(
          `gh pr view "${branch}" --json state --jq .state 2>/dev/null`,
          { cwd: dir, encoding: 'utf-8', timeout: 10000 },
        ).trim();
      } catch {
        // gh not available or no PR
      }

      if (prState === 'MERGED') {
        try {
          execSync('git checkout -- .', { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' }).toString();
        } catch { /* no tracked changes */ }
        try {
          execSync('git clean -fd --exclude=.agent-slot', { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
        } catch { /* ignore */ }
        try {
          execSync('git checkout main', { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
          execSync('git pull --ff-only origin main', { cwd: dir, encoding: 'utf-8', timeout: 60000, stdio: 'pipe' });
          execSync(`git branch -D "${branch}"`, { cwd: dir, encoding: 'utf-8', timeout: 5000, stdio: 'pipe' });
          resetResults.push(`  ✓ a${slot}: ${branch} → main (PR merged)`);
          continue;
        } catch {
          skipped.push(`  a${slot}: reset failed after merged PR`);
          continue;
        }
      }

      skipped.push(`  a${slot}: on branch ${branch}`);
      continue;
    }

    const porcelain = git(dir, 'status', '--porcelain');
    // Ignore untracked .agent-slot — it's expected in every slot
    const significantChanges = porcelain
      ? porcelain.split('\n').filter((l) => l && !l.endsWith('.agent-slot'))
      : [];
    if (significantChanges.length > 0) {
      skipped.push(`  a${slot}: has uncommitted changes`);
      continue;
    }

    try {
      execSync('git pull --ff-only origin main', { cwd: dir, encoding: 'utf-8', timeout: 30000, stdio: 'pipe' });
      updated.push(`  ✓ a${slot}: pulled latest main`);
    } catch (e) {
      skipped.push(`  a${slot}: git pull failed (${e instanceof Error ? e.message.split('\n')[0] : 'unknown error'})`);
    }
  }

  let output = '';
  if (resetResults.length > 0) {
    output += `Reset ${resetResults.length} merged-PR slot(s):\n${resetResults.join('\n')}\n`;
  }
  if (updated.length > 0) {
    output += `Pulled ${updated.length} slot(s):\n${updated.join('\n')}\n`;
  }
  if (skipped.length > 0) {
    output += `Skipped ${skipped.length} slot(s):\n${skipped.join('\n')}\n`;
  }
  if (resetResults.length === 0 && updated.length === 0 && skipped.length === 0) {
    output = 'No slots to refresh.';
  }

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// reset
// ---------------------------------------------------------------------------

async function reset(args: string[], options: CommandOptions): Promise<CommandResult> {
  const lwDir = getLwDir();
  const slots = findSlotDirs(lwDir);

  const targetSlot = args.find((a) => !a.startsWith('--'));
  if (!targetSlot) {
    return {
      exitCode: 1,
      output: `Usage: crux agent-workspace reset <N|all> [--force]

Reset an agent slot back to main after its PR has been merged.

Steps performed:
  1. Verify the slot's branch has a merged PR (skip with --force)
  2. Discard all local changes (git checkout + git clean)
  3. Switch to main and pull latest
  4. Delete the old local branch

Use "all" to reset every slot whose PR is merged.`,
    };
  }

  const resetAll = targetSlot === 'all';
  let toReset: Array<{ dir: string; slot: number }>;

  if (resetAll) {
    toReset = slots;
  } else {
    if (!/^\d+$/.test(targetSlot)) {
      return { exitCode: 1, output: 'Error: Slot number must be a positive integer (or "all")' };
    }
    const slotNum = parseInt(targetSlot, 10);
    toReset = slots.filter((s) => s.slot === slotNum);
    if (toReset.length === 0) {
      return { exitCode: 1, output: `Error: Slot a${slotNum} not found.` };
    }
  }

  const resetResults: string[] = [];
  const skippedResults: string[] = [];

  for (const { dir, slot } of toReset) {
    const branch = git(dir, 'branch', '--show-current');

    // Already on main — nothing to reset
    if (branch === 'main') {
      skippedResults.push(`  a${slot}: already on main`);
      continue;
    }

    // Check if the branch's PR is merged (unless --force)
    if (!options.force) {
      let prState = '';
      try {
        prState = execSync(
          `gh pr view "${branch}" --json state --jq .state 2>/dev/null`,
          { cwd: dir, encoding: 'utf-8', timeout: 10000 },
        ).trim();
      } catch {
        // gh not available or no PR exists
      }

      if (prState !== 'MERGED') {
        const reason = prState ? `PR state is ${prState}` : 'no merged PR found';
        skippedResults.push(`  a${slot}: ${reason} (use --force to override)`);
        continue;
      }
    }

    // Discard all local changes
    try {
      execSync('git checkout -- .', { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
    } catch {
      // May fail if there are no tracked changes — that's fine
    }
    // Remove untracked files but keep .agent-slot
    try {
      execSync('git clean -fd --exclude=.agent-slot', { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
    } catch {
      // Ignore
    }

    // Switch to main
    try {
      execSync('git checkout main', { cwd: dir, encoding: 'utf-8', timeout: 10000, stdio: 'pipe' });
    } catch (e) {
      skippedResults.push(`  a${slot}: failed to checkout main (${e instanceof Error ? e.message.split('\n')[0] : 'unknown'})`);
      continue;
    }

    // Pull latest
    try {
      execSync('git pull --ff-only origin main', { cwd: dir, encoding: 'utf-8', timeout: 60000, stdio: 'pipe' });
    } catch {
      // Pull failed but we're still on main — continue
    }

    // Delete old branch
    try {
      execSync(`git branch -D "${branch}"`, { cwd: dir, encoding: 'utf-8', timeout: 5000, stdio: 'pipe' });
    } catch {
      // Branch may already be gone
    }

    resetResults.push(`  ✓ a${slot}: ${branch} → main`);
  }

  let output = '';
  if (resetResults.length > 0) {
    output += `Reset ${resetResults.length} slot(s):\n${resetResults.join('\n')}\n`;
  }
  if (skippedResults.length > 0) {
    output += `Skipped ${skippedResults.length} slot(s):\n${skippedResults.join('\n')}\n`;
  }
  if (resetResults.length === 0 && skippedResults.length === 0) {
    output = 'No slots to reset.';
  }

  return { exitCode: 0, output };
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export const commands: Record<string, (args: string[], options: CommandOptions) => Promise<CommandResult>> = {
  default: list,
  setup,
  'sync-env': syncEnv,
  list,
  clean,
  reset,
  open,
  refresh,
};

export function getHelp(): string {
  return `
Agent Workspace — Local multi-agent directory management

Manages the lw/ directory structure for running multiple Claude Code agents
in parallel, each with its own clone and port configuration.

Directory layout:
  lw/
    .env.base       Shared API keys (single source of truth)
    main/           Primary working copy
    a1/ ... a10/    Agent slots (independent clones)

Commands:
  setup <N>         Initialize agent slot N (clone + .env + .agent-slot)
  sync-env          Regenerate .env for all slots from .env.base
  list              Show all slots with branch, PR, and port info (default)
  clean [N]         Show idle slots; use --force to remove them
  reset <N|all>     Reset merged-PR slots back to main (--force to skip PR check)
  open <N>          Open a tmux window at slot N (--claude to launch claude)
  refresh           Reset merged-PR slots + pull latest main in idle slots

Port assignments (deterministic from slot number):
  Agent N → Next.js on port (3010+N), wiki-server on port (3110+N)
  e.g. slot 1 → 3011/3111, slot 10 → 3020/3120

Options:
  --force    Force re-init (setup), actually delete (clean), or skip PR check (reset)
  --json     JSON output (list)

Examples:
  crux agent-workspace setup 3           Create agent slot a3
  crux agent-workspace sync-env          Regenerate .env for all slots
  crux agent-workspace list              Show all slots and their status
  crux agent-workspace reset all         Reset all slots with merged PRs back to main
  crux agent-workspace reset 2           Reset slot a2 back to main
  crux agent-workspace clean --force     Remove idle slots (on main, no changes)
`;
}
