/**
 * Docs Command — Generate CLI reference documentation
 *
 * Walks all registered command groups and domains, extracts help text,
 * and generates a formatted MDX reference page.
 */

import { GROUPS, type GroupDef } from '../lib/groups.ts';
import type { CommandResult } from '../lib/cli.ts';

/** Strip ANSI escape codes from help text */
function stripAnsi(text: string): string {
  return text.replace(/\x1b\[[0-9;]*m/g, '');
}

/** Escape MDX-sensitive characters ($ and <) outside code blocks */
export function escapeMdx(text: string): string {
  // Escape $ followed by digits (would be parsed as math)
  // and bare < followed by lowercase (would be parsed as JSX)
  return text
    .replace(/\\/g, '\\\\')
    .replace(/\$/g, '\\$')
    .replace(/<(?=[a-z])/g, '\\<');
}

/** Format a domain's help text into a markdown section */
function formatDomainHelp(domainName: string, helpText: string): string {
  const clean = stripAnsi(helpText).trim();
  if (!clean) return '';

  // Extract first line as description (shown outside code block)
  const lines = clean.split('\n');
  const firstLine = lines[0]?.trim() || '';
  const rest = lines.slice(1).join('\n').trim();

  let result = `### \`${domainName}\`\n\n`;
  if (firstLine) {
    result += `${escapeMdx(firstLine)}\n\n`;
  }
  if (rest) {
    // Wrap detailed help in a code block to avoid MDX parsing issues
    // (help text contains <t>, <path>, <id> etc. which look like JSX)
    result += `\`\`\`\n${rest}\n\`\`\`\n`;
  }
  return result;
}

/** Generate the full CLI reference as MDX content */
async function generateReference(
  domains: Record<string, { getHelp?: () => string; commands?: Record<string, unknown> }>,
): Promise<string> {
  const sections: string[] = [];

  // Top-level overview
  sections.push(`## Command Groups

| Group | Shortcut | Description |
|-------|----------|-------------|`);

  for (const [name, def] of Object.entries(GROUPS)) {
    sections.push(`| ${name} | \`${def.shortcut}\` | ${def.description} |`);
  }

  sections.push(`| query | — | Query wiki-server DB (search, entity, facts, related, risk, stats) |`);
  sections.push(`| context | — | Assemble research bundles (for-page, for-issue, for-entity, for-topic) |`);
  sections.push('');

  // Per-group sections
  for (const [groupName, def] of Object.entries(GROUPS)) {
    sections.push(`## ${groupName} (\`${def.shortcut}\`)

${def.description}
`);

    for (const domainName of def.domains) {
      const handler = domains[domainName];
      if (!handler) continue;

      if (handler.getHelp) {
        const helpText = handler.getHelp();
        sections.push(formatDomainHelp(domainName, helpText));
      } else {
        // List available commands if getHelp isn't available
        const commandNames = handler.commands ? Object.keys(handler.commands).filter(k => k !== 'default') : [];
        if (commandNames.length > 0) {
          sections.push(`### \`${domainName}\`

Commands: ${commandNames.map(c => `\`${c}\``).join(', ')}
`);
        }
      }
    }
  }

  // Cross-cutting commands
  sections.push(`## Cross-cutting commands

These are not part of any group — invoke directly as \`pnpm crux <command>\`.
`);

  for (const domainName of ['query', 'context']) {
    const handler = domains[domainName];
    if (handler?.getHelp) {
      sections.push(formatDomainHelp(domainName, handler.getHelp()));
    }
  }

  return sections.join('\n');
}

/** Write the reference page */
async function writeReferencePage(content: string): Promise<void> {
  const { writeFileSync, existsSync } = await import('fs');
  const { join } = await import('path');
  const { PROJECT_ROOT } = await import('../lib/content-types.ts');

  const outputPath = join(PROJECT_ROOT, 'content/docs/internal/cli-reference.mdx');

  const lastEdited = new Date().toISOString().slice(0, 10);

  const mdx = `---
wikiId: E2170
title: "CLI Reference"
description: "Auto-generated reference for all crux CLI commands — groups, domains, subcommands, options, and examples."
subcategory: architecture
contentFormat: article
lastEdited: "${lastEdited}"
---

{/* Auto-generated by: pnpm crux sys docs reference */}
{/* Do not edit manually — regenerate with the command above. */}

This page is auto-generated from the \`--help\` output of every crux CLI command. Run \`pnpm crux sys docs reference\` to regenerate.

${content}
`;

  writeFileSync(outputPath, mdx, 'utf-8');
  return;
}

export const commands: Record<string, (args: string[], options: Record<string, unknown>) => Promise<CommandResult>> = {
  reference: async (_args, _options) => {
    // Dynamically import the domains object from crux.mjs
    // We can't import it statically because crux.mjs imports us
    // Instead, we import each command file directly
    const domainImports: Record<string, { getHelp?: () => string; commands?: Record<string, unknown> }> = {};

    // Import all command files that are registered in the domains object
    const importMap: Record<string, string> = {
      'validate': './validate.ts',
      'analyze': './analyze.ts',
      'fix': './fix.ts',
      'content': './content.ts',
      'generate': './generate.ts',
      'visual': './visual.ts',
      'resources': './resources.ts',
      'updates': './updates.ts',
      'auto-update': './auto-update.ts',
      'check-links': './check-links.ts',
      'citations': './citations.ts',
      'footnotes': './footnotes.ts',
      'enrich': './enrich.ts',
      'importance': './importance.ts',
      'pages': './pages.ts',
      'qa-sweep': './qa-sweep.ts',
      'qa-checks': './qa-checks.ts',
      'evals': './evals.ts',
      'research': './research.ts',
      'grokipedia': './grokipedia.ts',
      'sourcing-wiki-pages': './sourcing-wiki-pages.ts',
      'verify-consistency': './verify-consistency.ts',
      'extract-structured-data': './extract-structured-data.ts',
      'auto-verify-stakeholders': './auto-verify-stakeholders.ts',
      'factbase': './factbase.ts',
      'wikidata-enrich': './wikidata-enrich.ts',
      'import-990': './import-990.ts',
      'tablebase': './tablebase.ts',
      'matrix': './matrix.ts',
      'entity': './entity.ts',
      'ids': './ids.ts',
      'people': './people.ts',
      'orgs': './orgs.ts',
      'sourcing': './verify-entity.ts',
      'benchmarks': './benchmarks.ts',
      'legislation': './legislation.ts',
      'issues': './issues.ts',
      'pr': './pr.ts',
      'ci': './ci.ts',
      'epic': './epic.ts',
      'release': './release.ts',
      'deploy-tasks': './deploy-tasks.ts',
      'agents': './agents.ts',
      'agent-checklist': './agent-checklist.ts',
      'agent-workspace': './agent-workspace.ts',
      'jobs': './jobs.ts',
      'sessions': './sessions.ts',
      'health': './health.ts',
      'audits': './audits.ts',
      'quality': './data-quality.ts',
      'query': './query.ts',
      'context': './context.ts',
    };

    let loaded = 0;
    let failed = 0;
    for (const [name, path] of Object.entries(importMap)) {
      try {
        const mod = await import(path);
        domainImports[name] = mod;
        loaded++;
      } catch {
        failed++;
      }
    }

    console.log(`Loaded ${loaded} command modules (${failed} failed)`);

    const content = await generateReference(domainImports);
    await writeReferencePage(content);

    console.log('✓ Generated content/docs/internal/cli-reference.mdx');
    return { output: `Generated CLI reference (${loaded} modules)`, exitCode: 0 };
  },
};

export function getHelp(): string {
  return `Docs Domain — Generate CLI reference documentation

Commands:
  reference    Generate the CLI reference page from all command help text

Usage:
  crux sys docs reference

The generated page is written to content/docs/internal/cli-reference.mdx.
It is auto-generated from the --help output of every command module.`;
}
