/**
 * Facts Loader
 *
 * Loads canonical facts from YAML, normalizes structured values,
 * resolves computed facts, enriches with resource metadata,
 * and builds timeseries index.
 *
 * Extracted from build-data.mjs for modularity.
 */

import { readFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';
import { parse } from 'yaml';
import { parseNumericValue, resolveComputedFacts } from './computed-facts.mjs';

// ---------------------------------------------------------------------------
// Value formatting helpers
// ---------------------------------------------------------------------------

function cleanDecimal(n) {
  return n % 1 === 0 ? String(n) : n.toFixed(1);
}

function formatFactNumber(n, measure) {
  if (measure?.unit === 'USD') {
    if (Math.abs(n) >= 1e12) return `$${cleanDecimal(n / 1e12)} trillion`;
    if (Math.abs(n) >= 1e9) return `$${cleanDecimal(n / 1e9)} billion`;
    if (Math.abs(n) >= 1e6) return `$${cleanDecimal(n / 1e6)} million`;
    return `$${n.toLocaleString('en-US')}`;
  }
  if (measure?.unit === 'percent') return `${cleanDecimal(n)}%`;
  if (measure?.unit === 'count') {
    if (Math.abs(n) >= 1e9) return `${cleanDecimal(n / 1e9)} billion`;
    if (Math.abs(n) >= 1e6) return `${cleanDecimal(n / 1e6)} million`;
    return n.toLocaleString('en-US');
  }
  if (Math.abs(n) >= 1e9) return `${cleanDecimal(n / 1e9)} billion`;
  if (Math.abs(n) >= 1e6) return `${cleanDecimal(n / 1e6)} million`;
  return n.toLocaleString('en-US');
}

function formatFactRange(lo, hi, measure) {
  if (measure?.unit === 'percent') return `${cleanDecimal(lo)}-${cleanDecimal(hi)}%`;
  if (measure?.unit === 'USD') {
    if (lo >= 1e9 && hi >= 1e9) return `$${cleanDecimal(lo / 1e9)}-${cleanDecimal(hi / 1e9)} billion`;
    if (lo >= 1e6 && hi >= 1e6) return `$${cleanDecimal(lo / 1e6)}-${cleanDecimal(hi / 1e6)} million`;
    return `$${lo.toLocaleString('en-US')}-$${hi.toLocaleString('en-US')}`;
  }
  if (measure?.unit === 'count') {
    if (lo >= 1e6 && hi >= 1e6) return `${cleanDecimal(lo / 1e6)}-${cleanDecimal(hi / 1e6)} million`;
    return `${lo.toLocaleString('en-US')}-${hi.toLocaleString('en-US')}`;
  }
  return `${lo.toLocaleString('en-US')}-${hi.toLocaleString('en-US')}`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Load canonical facts from data/facts/*.yaml.
 * @param {string} dataDir - Path to the data/ directory
 * @returns {Record<string, object>} facts keyed by "entity.factId"
 */
export function loadFacts(dataDir) {
  const factsDir = join(dataDir, 'facts');
  const facts = {};

  if (!existsSync(factsDir)) return facts;

  const factFiles = readdirSync(factsDir).filter(f => f.endsWith('.yaml'));
  let totalFacts = 0;

  for (const file of factFiles) {
    const filepath = join(factsDir, file);
    try {
      const content = readFileSync(filepath, 'utf-8');
      const parsed = parse(content);
      if (parsed && parsed.entity && parsed.facts) {
        if (parsed.deprecated_by) {
          console.warn(`  [DEPRECATED] data/facts/${file} is managed in packages/kb/data/things/${parsed.entity}.yaml — do not edit this file`);
        }
        for (const [factId, factData] of Object.entries(parsed.facts)) {
          const key = `${parsed.entity}.${factId}`;
          facts[key] = { ...factData, entity: parsed.entity, factId };
          totalFacts++;
        }
      }
    } catch (e) {
      console.error(`Failed to parse YAML ${filepath}: ${e.message}`);
      process.exitCode = 1;
    }
  }

  console.log(`  facts: ${totalFacts} canonical facts from ${factFiles.length} files`);
  return facts;
}

/**
 * Load fact measure definitions from data/fact-measures.yaml.
 * @param {string} dataDir
 * @returns {Record<string, object>}
 */
export function loadFactMeasures(dataDir) {
  const factMeasuresPath = join(dataDir, 'fact-measures.yaml');
  const factMeasures = {};

  if (!existsSync(factMeasuresPath)) return factMeasures;

  try {
    const content = readFileSync(factMeasuresPath, 'utf-8');
    const parsed = parse(content);
    if (parsed && parsed.measures) {
      for (const [measureId, measureDef] of Object.entries(parsed.measures)) {
        factMeasures[measureId] = { id: measureId, ...measureDef };
      }
    }
    console.log(`  factMeasures: ${Object.keys(factMeasures).length} measure definitions`);
  } catch (e) {
    console.error(`Failed to parse YAML ${factMeasuresPath}: ${e.message}`);
    process.exitCode = 1;
  }

  return factMeasures;
}

/**
 * Validate measure references and normalize structured values.
 * Mutates facts in-place.
 * @param {Record<string, object>} facts
 * @param {Record<string, object>} factMeasures
 */
export function normalizeFactValues(facts, factMeasures) {
  // Validate measure references
  const knownMeasureIds = new Set(Object.keys(factMeasures));
  let measuredCount = 0;
  for (const [key, fact] of Object.entries(facts)) {
    if (fact.measure) {
      measuredCount++;
      if (!knownMeasureIds.has(fact.measure)) {
        console.warn(`  WARNING: fact ${key} references unknown measure "${fact.measure}"`);
      }
    }
  }
  if (measuredCount > 0) {
    console.log(`  measures: ${measuredCount} facts have explicit measure assignments`);
  }

  // Normalize structured values → flat format
  let structuredCount = 0;
  for (const [_key, fact] of Object.entries(facts)) {
    const val = fact.value;
    const measure = fact.measure ? factMeasures[fact.measure] : null;

    if (typeof val === 'number') {
      if (measure?.unit === 'percent') {
        fact.numeric = val / 100;
      } else {
        fact.numeric = val;
      }
      fact.value = formatFactNumber(val, measure);
      structuredCount++;

    } else if (Array.isArray(val) && val.length === 2 && typeof val[0] === 'number') {
      const [lo, hi] = val;
      if (measure?.unit === 'percent') {
        fact.low = lo / 100;
        fact.high = hi / 100;
        fact.numeric = (lo + hi) / 200;
      } else {
        fact.low = lo;
        fact.high = hi;
        fact.numeric = (lo + hi) / 2;
      }
      fact.value = formatFactRange(lo, hi, measure);
      structuredCount++;

    } else if (val && typeof val === 'object' && !Array.isArray(val) && 'min' in val) {
      const n = val.min;
      if (measure?.unit === 'percent') {
        fact.numeric = n / 100;
      } else {
        fact.numeric = n;
      }
      fact.value = formatFactNumber(n, measure) + '+';
      structuredCount++;

    } else if (typeof val === 'string') {
      if (fact.numeric == null && !fact.compute) {
        const parsed = parseNumericValue(val);
        if (parsed !== null) {
          fact.numeric = parsed;
        }
      }
    }
  }

  if (structuredCount > 0) {
    console.log(`  values: normalized ${structuredCount} structured values`);
  }

  // Evaluate computed facts (topological order)
  const computedCount = resolveComputedFacts(facts);
  if (computedCount > 0) {
    console.log(`  computed: ${computedCount} facts resolved`);
  }
}

/**
 * Enrich facts with source resource metadata. Auto-matches source URLs to resources.
 * Mutates facts in-place.
 * @param {Record<string, object>} facts
 * @param {Array<object>} resources
 * @param {Array<object>} publications
 */
export function enrichFactSources(facts, resources, publications) {
  const resourceById = new Map(resources.map(r => [r.id, r]));
  const publicationById = new Map(publications.map(p => [p.id, p]));

  // Build URL → resource ID map for auto-matching
  const sourceUrlToResourceId = new Map();
  for (const r of resources) {
    if (!r.url) continue;
    sourceUrlToResourceId.set(r.url, r.id);
    sourceUrlToResourceId.set(r.url.replace(/\/$/, ''), r.id);
    if (!r.url.endsWith('/')) sourceUrlToResourceId.set(r.url + '/', r.id);
  }

  let resolvedCount = 0;
  let autoMatchedCount = 0;

  for (const [key, fact] of Object.entries(facts)) {
    // Auto-match
    if (fact.source && !fact.sourceResource) {
      const matchedId = sourceUrlToResourceId.get(fact.source) || sourceUrlToResourceId.get(fact.source.replace(/\/$/, ''));
      if (matchedId) {
        fact.sourceResource = matchedId;
        autoMatchedCount++;
      }
    }

    // Resolve
    if (fact.sourceResource) {
      const resource = resourceById.get(fact.sourceResource);
      if (resource) {
        fact.sourceTitle = resource.title;
        if (resource.publication_id) {
          const pub = publicationById.get(resource.publication_id);
          if (pub) {
            fact.sourcePublication = pub.name;
            fact.sourceCredibility = pub.credibility;
          }
        }
        if (resource.credibility_override != null) {
          fact.sourceCredibility = resource.credibility_override;
        }
        if (!fact.source && resource.url) {
          fact.source = resource.url;
        }
        resolvedCount++;
      } else {
        console.warn(`  ⚠ fact ${key}: sourceResource "${fact.sourceResource}" not found in resources`);
      }
    }
  }

  if (resolvedCount > 0 || autoMatchedCount > 0) {
    console.log(`  sourceResource: ${resolvedCount} resolved, ${autoMatchedCount} auto-matched from URLs`);
  }
}

/**
 * Build timeseries index: group facts by measure, sorted chronologically.
 * @param {Record<string, object>} facts
 * @returns {Record<string, Array<object>>}
 */
export function buildFactTimeseries(facts) {
  const timeseries = {};

  for (const [_key, fact] of Object.entries(facts)) {
    if (!fact.measure || !fact.asOf) continue;
    if (fact.subject) continue; // Skip benchmark/comparison facts

    if (!timeseries[fact.measure]) {
      timeseries[fact.measure] = [];
    }
    timeseries[fact.measure].push({
      entity: fact.entity,
      factId: fact.factId,
      measure: fact.measure,
      asOf: fact.asOf,
      value: fact.value,
      numeric: fact.numeric,
      low: fact.low,
      high: fact.high,
      note: fact.note,
      source: fact.source,
    });
  }

  // Sort each timeseries chronologically
  for (const series of Object.values(timeseries)) {
    series.sort((a, b) => a.asOf.localeCompare(b.asOf));
  }

  const totalObs = Object.values(timeseries).reduce((sum, s) => sum + s.length, 0);
  console.log(`  factTimeseries: ${totalObs} observations across ${Object.keys(timeseries).length} measures`);

  return timeseries;
}
