/**
 * Program Matcher — Maps grants to their funding programs.
 *
 * Uses a rule-based approach: each rule maps (source, funderId, focusArea pattern)
 * to a funding program ID. The program IDs must match those generated by
 * `import-funding-programs.ts` using `generateId(idSeed)`.
 *
 * The matching is deterministic and does not require DB access — program IDs
 * are derived from the same seeds used in `import-funding-programs.ts`.
 */

import { generateId } from "./id.ts";
import { FUNDER_IDS } from "./constants.ts";

// ---------------------------------------------------------------------------
// Program ID generation — uses same seeds as import-funding-programs.ts
// ---------------------------------------------------------------------------

/** Generate program ID from the canonical seed string. Must match import-funding-programs.ts. */
function progId(seed: string): string {
  return generateId(seed);
}

// Pre-compute program IDs for all known programs
export const PROGRAM_IDS = {
  // Open Philanthropy / Coefficient Giving — broad programs
  OP_AI_SAFETY: progId("prog|open-philanthropy|ai-safety"),
  OP_BIOSECURITY: progId("prog|open-philanthropy|biosecurity"),
  OP_GLOBAL_HEALTH: progId("prog|open-philanthropy|global-health"),

  // Coefficient Giving — specific programs
  CG_GCR_OPPORTUNITIES: progId("prog|coefficient-giving|gcr-opportunities"),
  CG_FARM_ANIMAL_WELFARE: progId("prog|coefficient-giving|farm-animal-welfare"),
  CG_SCIENCE_RD: progId("prog|coefficient-giving|science-rd"),
  CG_FORECASTING: progId("prog|coefficient-giving|forecasting"),
  CG_EFFECTIVE_GIVING: progId("prog|coefficient-giving|effective-giving-careers"),
  CG_GLOBAL_AID: progId("prog|coefficient-giving|global-aid-policy"),
  CG_GLOBAL_GROWTH: progId("prog|coefficient-giving|global-growth"),
  CG_AIR_QUALITY: progId("prog|coefficient-giving|air-quality"),
  CG_LEAF: progId("prog|coefficient-giving|lead-exposure"),
  CG_ABUNDANCE_GROWTH: progId("prog|coefficient-giving|abundance-growth-grants"),
  CG_TECHNICAL_AI_SAFETY_RFP: progId("prog|coefficient-giving|technical-ai-safety-rfp-2025"),

  // EA Funds
  LTFF_GRANTS: progId("prog|ea-funds|ltff-grants"),
  AWF_GRANTS: progId("prog|ea-funds|awf-grants"),
  EAIF_GRANTS: progId("prog|ea-funds|eaif-grants"),
  GHD_GRANTS: progId("prog|ea-funds|ghd-grants"),

  // SFF
  SFF_S_PROCESS: progId("prog|sff|s-process"),
  SFF_SPECULATION: progId("prog|sff|speculation-grants"),

  // FTX Future Fund
  FTX_GENERAL: progId("prog|ftx|general-grants"),
  FTX_REGRANTING: progId("prog|ftx|regranting-program"),

  // Manifund
  MANIFUND_REGRANTING: progId("prog|manifund|regranters"),

  // ACX Grants
  ACX_2022: progId("prog|acx|grants-2022"),
  ACX_2023: progId("prog|acx|grants-2023"),
  ACX_2025: progId("prog|acx|grants-2025"),
} as const;

// ---------------------------------------------------------------------------
// Matching rules
// ---------------------------------------------------------------------------

interface ProgramRule {
  /** Grant source ID (e.g. "ea-funds", "coefficient-giving") */
  source: string;
  /** Funder entity stableId */
  funderId?: string;
  /** If provided, focusArea must match this pattern (case-insensitive) */
  focusAreaPattern?: RegExp;
  /** If provided, grant name must match this pattern (case-insensitive) */
  namePattern?: RegExp;
  /** If provided, grant description must match this pattern (case-insensitive) */
  descriptionPattern?: RegExp;
  /** The resulting program ID */
  programId: string;
}

/**
 * Rules are evaluated in order — first match wins.
 * More specific rules should come before more general ones.
 */
const RULES: ProgramRule[] = [
  // ===== EA Funds =====
  // EA Funds grants have focusArea set to the fund name
  {
    source: "ea-funds",
    focusAreaPattern: /long.?term future fund/i,
    programId: PROGRAM_IDS.LTFF_GRANTS,
  },
  {
    source: "ea-funds",
    focusAreaPattern: /animal welfare fund/i,
    programId: PROGRAM_IDS.AWF_GRANTS,
  },
  {
    source: "ea-funds",
    focusAreaPattern: /ea infrastructure fund|effective altruism infrastructure/i,
    programId: PROGRAM_IDS.EAIF_GRANTS,
  },
  {
    source: "ea-funds",
    focusAreaPattern: /global health.*development fund/i,
    programId: PROGRAM_IDS.GHD_GRANTS,
  },

  // ===== Coefficient Giving (Open Philanthropy) =====
  // Coefficient Giving grants have focusArea extracted from bracketed prefix in notes.
  // More specific rules come first; general catch-all is last.

  // --- Specific programs (most specific patterns first) ---

  // Technical AI Safety RFP — specific RFP under the AI safety umbrella
  {
    source: "coefficient-giving",
    focusAreaPattern: /technical ai safety rfp|technical ai safety research rfp/i,
    programId: PROGRAM_IDS.CG_TECHNICAL_AI_SAFETY_RFP,
  },

  // AI Safety (broad) — covers AI governance, AI policy, alignment research
  {
    source: "coefficient-giving",
    focusAreaPattern: /potential risks from advanced ai|ai safety|ai governance|technical ai safety|ai policy/i,
    programId: PROGRAM_IDS.OP_AI_SAFETY,
  },

  // Biosecurity and Pandemic Preparedness
  {
    source: "coefficient-giving",
    focusAreaPattern: /biosecurity|pandemic preparedness|global catastrophic biological/i,
    programId: PROGRAM_IDS.OP_BIOSECURITY,
  },

  // GCR Opportunities — global catastrophic risks beyond AI/bio
  {
    source: "coefficient-giving",
    focusAreaPattern: /global catastrophic risks|gcr|existential risk/i,
    programId: PROGRAM_IDS.CG_GCR_OPPORTUNITIES,
  },

  // Farm Animal Welfare — must match before general global health catch-all
  {
    source: "coefficient-giving",
    focusAreaPattern: /farm animal welfare/i,
    programId: PROGRAM_IDS.CG_FARM_ANIMAL_WELFARE,
  },

  // Science & Global Health R&D
  {
    source: "coefficient-giving",
    focusAreaPattern: /science.*global health r&d|scientific research|global health r&d/i,
    programId: PROGRAM_IDS.CG_SCIENCE_RD,
  },

  // Forecasting
  {
    source: "coefficient-giving",
    focusAreaPattern: /forecasting/i,
    programId: PROGRAM_IDS.CG_FORECASTING,
  },

  // Effective Giving & Careers / EA Community Building
  {
    source: "coefficient-giving",
    focusAreaPattern: /effective giving|effective altruism community|community building/i,
    programId: PROGRAM_IDS.CG_EFFECTIVE_GIVING,
  },

  // Global Aid Policy
  {
    source: "coefficient-giving",
    focusAreaPattern: /global aid|u\.s\. policy/i,
    programId: PROGRAM_IDS.CG_GLOBAL_AID,
  },

  // Global Growth / Economic Growth in Developing Countries
  {
    source: "coefficient-giving",
    focusAreaPattern: /global economic growth|economic growth.*developing/i,
    programId: PROGRAM_IDS.CG_GLOBAL_GROWTH,
  },

  // Air Quality
  {
    source: "coefficient-giving",
    focusAreaPattern: /air quality|south asian air quality/i,
    programId: PROGRAM_IDS.CG_AIR_QUALITY,
  },

  // Lead Exposure Action Fund (LEAF)
  {
    source: "coefficient-giving",
    focusAreaPattern: /lead exposure|lead poisoning/i,
    programId: PROGRAM_IDS.CG_LEAF,
  },

  // Abundance & Growth Grants
  {
    source: "coefficient-giving",
    focusAreaPattern: /abundance|scientific innovation/i,
    programId: PROGRAM_IDS.CG_ABUNDANCE_GROWTH,
  },

  // --- General catch-all for remaining Coefficient Giving grants ---
  // Catches global health, criminal justice, land use, immigration, macroeconomic, etc.
  {
    source: "coefficient-giving",
    focusAreaPattern: /global health|criminal justice|land use|immigration|macroeconomic/i,
    programId: PROGRAM_IDS.OP_GLOBAL_HEALTH,
  },

  // Final fallback for any coefficient-giving grant with a focus area
  // that didn't match any specific program above
  {
    source: "coefficient-giving",
    programId: PROGRAM_IDS.OP_GLOBAL_HEALTH,
  },

  // ===== SFF =====
  // SFF grants are from the S-Process by default
  // Speculation grants are identified by description patterns
  {
    source: "sff",
    descriptionPattern: /speculation/i,
    programId: PROGRAM_IDS.SFF_SPECULATION,
  },
  {
    source: "sff",
    programId: PROGRAM_IDS.SFF_S_PROCESS,
  },

  // ===== FTX Future Fund =====
  // FTX grants: regrants vs general
  {
    source: "ftx-future-fund",
    focusAreaPattern: /regrant/i,
    programId: PROGRAM_IDS.FTX_REGRANTING,
  },
  {
    source: "ftx-future-fund",
    programId: PROGRAM_IDS.FTX_GENERAL,
  },

  // ===== Manifund =====
  // Default to regranting (the primary mechanism)
  {
    source: "manifund",
    programId: PROGRAM_IDS.MANIFUND_REGRANTING,
  },

  // ===== ACX Grants =====
  // ACX grants have description like "ACX Grants 2021 round"
  // Note: ACX_2022 program represents the first round (results announced 2022, using 2021 data)
  // ACX_2023 program represents the second round (results announced 2024)
  // The 2025 round has no dedicated program yet — falls back to the catch-all
  {
    source: "acx-grants",
    descriptionPattern: /acx grants 2021/i,
    programId: PROGRAM_IDS.ACX_2022,
  },
  {
    source: "acx-grants",
    descriptionPattern: /acx grants 2024/i,
    programId: PROGRAM_IDS.ACX_2023,
  },
  {
    source: "acx-grants",
    descriptionPattern: /acx grants 2025/i,
    programId: PROGRAM_IDS.ACX_2025,
  },
];

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ProgramMatchInput {
  source: string;
  funderId: string;
  focusArea: string | null;
  name: string;
  description: string | null;
}

/**
 * Match a grant to a funding program ID.
 *
 * Returns the 10-char program ID if matched, null otherwise.
 */
export function matchProgram(input: ProgramMatchInput): string | null {
  for (const rule of RULES) {
    if (rule.source !== input.source) continue;
    if (rule.funderId && rule.funderId !== input.funderId) continue;

    if (rule.focusAreaPattern) {
      if (!input.focusArea || !rule.focusAreaPattern.test(input.focusArea)) {
        continue;
      }
    }

    if (rule.namePattern) {
      if (!rule.namePattern.test(input.name)) continue;
    }

    if (rule.descriptionPattern) {
      if (!input.description || !rule.descriptionPattern.test(input.description)) {
        continue;
      }
    }

    return rule.programId;
  }

  return null;
}

/**
 * Get all known program IDs as a flat array (for validation).
 */
export function getAllProgramIds(): string[] {
  return Object.values(PROGRAM_IDS);
}
