/**
 * QUA-503: Generate the bare10 → sid_ mapping for the resources.stable_id rewrite.
 *
 * Reads `data/resources-snapshot.json` (produced by
 * `pnpm crux wiki-server snapshot-resources`), finds every row whose
 * `stable_id` matches `^[A-Za-z0-9]{10}$` (legacy bare10 format), and mints a
 * deterministic new `sid_` + 10-char id for each one using `contentHash()`.
 *
 * Deterministic-by-design so the mapping is stable across reruns and can be
 * regenerated to verify the committed file. The `"qua-503-bare10"` namespace
 * is included in the hash input to avoid collisions with any other
 * content-hashed identifiers derived from the same raw string.
 *
 * Outputs:
 *   - apps/wiki-server/scripts/qua-503-bare10-mapping.json
 *       Array of { old, new, resourceId } — used by the MDX sweep.
 *   - apps/wiki-server/scripts/qua-503-rewrite-bare10.sql
 *       Manual migration that applies the mapping to PG. Self-contained.
 *
 * Usage:
 *   pnpm tsx crux/scripts/qua-503-generate-mapping.ts
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { contentHash } from "../../packages/factbase/src/ids.ts";
import { PROJECT_ROOT } from "../lib/content-types.ts";
import { loadResources } from "../resource-io.ts";

const SCRIPTS_DIR = join(PROJECT_ROOT, "apps", "wiki-server", "scripts");
const MAPPING_JSON = join(SCRIPTS_DIR, "qua-503-bare10-mapping.json");
const SQL_OUT = join(SCRIPTS_DIR, "qua-503-rewrite-bare10.sql");

const BARE10_RE = /^[A-Za-z0-9]{10}$/;
const SID_RE = /^sid_[A-Za-z0-9]{10}$/;

function mintNewSid(oldBare10: string): string {
  return "sid_" + contentHash(["qua-503-bare10", oldBare10]);
}

function main(): void {
  const resources = loadResources();

  const mapping: { old: string; new: string; resourceId: string }[] = [];
  const seenOld = new Set<string>();
  const seenNew = new Set<string>();
  const existingSidSuffixes = new Set<string>();

  for (const r of resources) {
    if (r.stable_id && SID_RE.test(r.stable_id)) {
      existingSidSuffixes.add(r.stable_id.slice(4));
    }
  }

  for (const r of resources) {
    const s = r.stable_id;
    if (!s || !BARE10_RE.test(s)) continue;
    if (seenOld.has(s)) {
      throw new Error(`Duplicate bare10 stable_id in snapshot: ${s}`);
    }
    seenOld.add(s);
    const fresh = mintNewSid(s);
    if (!SID_RE.test(fresh)) {
      throw new Error(`Generated id does not match sid_ format: ${fresh}`);
    }
    if (seenNew.has(fresh)) {
      throw new Error(
        `Deterministic collision in generated sid_ values for ${s} → ${fresh}`,
      );
    }
    if (existingSidSuffixes.has(fresh.slice(4))) {
      throw new Error(
        `Generated id ${fresh} collides with an existing sid_-prefixed resource`,
      );
    }
    seenNew.add(fresh);
    mapping.push({ old: s, new: fresh, resourceId: r.id });
  }

  mapping.sort((a, b) => (a.old < b.old ? -1 : a.old > b.old ? 1 : 0));

  writeFileSync(MAPPING_JSON, JSON.stringify(mapping, null, 2) + "\n");
  console.log(`Wrote ${mapping.length} mappings to ${MAPPING_JSON}`);

  const sql = buildSql(mapping);
  writeFileSync(SQL_OUT, sql);
  console.log(`Wrote SQL migration to ${SQL_OUT}`);
}

function buildSql(
  mapping: { old: string; new: string; resourceId: string }[],
): string {
  const header = `-- QUA-503: rewrite ${mapping.length} bare10 \`resources.stable_id\` rows to canonical \`sid_\` format.
--
-- AUTO-GENERATED by crux/scripts/qua-503-generate-mapping.ts — do not edit by hand.
-- Run \`pnpm tsx crux/scripts/qua-503-generate-mapping.ts\` to regenerate.
--
-- Context: see Linear QUA-503 and the coordinator audit comments. The strategic
-- decision (hard cutover, no backward-compat tier) means every bare10 id in
-- PG must be rewritten to \`sid_<10>\` in the same merge as the MDX sweep in
-- \`content/docs/\`.
--
-- Usage (from a release session):
--   psql "$DATABASE_MIGRATION_URL" -v ON_ERROR_STOP=1 -f apps/wiki-server/scripts/qua-503-rewrite-bare10.sql
--
-- Pre-conditions verified by the script itself:
--   1. The count of rows matching \`^[A-Za-z0-9]{10}$\` equals the mapping size.
--   2. Every \`old\` value in the mapping still exists in \`resources.stable_id\`.
--   3. No \`new\` value already exists in \`resources.stable_id\` or \`things.id\`.
--
-- If any pre-condition fails, the transaction rolls back and nothing changes.
--
-- Post-conditions verified at the end:
--   1. \`SELECT count(*) FROM resources WHERE stable_id ~ '^[A-Za-z0-9]{10}$' AND stable_id !~ '^sid_'\` returns 0.
--   2. \`SELECT count(*) FROM things WHERE source_table = 'resources' AND id ~ '^[A-Za-z0-9]{10}$' AND id !~ '^sid_'\` returns 0.
--
-- The DDL that drops + re-adds FKs on \`things\` is required because PG does not
-- allow PK updates when referenced rows exist and the FKs are not \`ON UPDATE
-- CASCADE\`. We drop, update, re-add as \`ON DELETE SET NULL\` (matching the
-- original definition). The re-add uses \`NOT VALID\` + a separate
-- \`VALIDATE CONSTRAINT\` so the AccessExclusive lock is held for milliseconds,
-- not the time it takes to scan the entire \`things\` table. This avoids the
-- QUA-302 / QUA-156 outage pattern where an unsplit DDL on a hot \`things\`-
-- adjacent table deadlocked with a concurrent MV refresh and bricked deploy
-- for ~12 hours. See \`.claude/rules/database-migrations.md\` § "ADD CONSTRAINT
-- ... NOT VALID + separate VALIDATE CONSTRAINT".
--
-- The \`things_search\` MV refresh is intentionally OUTSIDE the transaction
-- (run as a separate statement after \`COMMIT\`). Refreshing it inside the
-- transaction would hold SELECT locks on every base table the MV reads,
-- compounding any concurrent-reader contention with the FK validation.

BEGIN;

SET LOCAL lock_timeout = '60s';
SET LOCAL statement_timeout = '0';

-- ---------------------------------------------------------------------------
-- 1. Load the mapping into a temp table.
-- ---------------------------------------------------------------------------

CREATE TEMP TABLE qua503_mapping (
  old_id text PRIMARY KEY,
  new_id text NOT NULL UNIQUE
) ON COMMIT DROP;

INSERT INTO qua503_mapping (old_id, new_id) VALUES
`;

  const valuesLines = mapping.map((m, i) => {
    const suffix = i === mapping.length - 1 ? ";" : ",";
    return `  (${pgLit(m.old)}, ${pgLit(m.new)})${suffix}`;
  });

  const verify = `
-- ---------------------------------------------------------------------------
-- 2. Pre-condition checks — abort the transaction if anything is off.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  actual_bare10 int;
  mapping_size int;
  missing_old int;
  collision_new_resources int;
  collision_new_things int;
BEGIN
  SELECT count(*) INTO actual_bare10
  FROM resources
  WHERE stable_id ~ '^[A-Za-z0-9]{10}$' AND stable_id !~ '^sid_';

  SELECT count(*) INTO mapping_size FROM qua503_mapping;

  IF actual_bare10 <> mapping_size THEN
    RAISE EXCEPTION
      'QUA-503: live bare10 count (%) does not match mapping size (%). Prod has drifted since the snapshot was taken. Regenerate by running: pnpm crux wiki-server snapshot-resources && pnpm tsx crux/scripts/qua-503-generate-mapping.ts && pnpm tsx crux/scripts/qua-503-sweep-mdx.ts',
      actual_bare10, mapping_size;
  END IF;

  SELECT count(*) INTO missing_old
  FROM qua503_mapping m
  WHERE NOT EXISTS (
    SELECT 1 FROM resources r
    WHERE r.stable_id = m.old_id
  );

  IF missing_old > 0 THEN
    RAISE EXCEPTION 'QUA-503: % mapping rows have no matching resources.stable_id. Regenerate.',
      missing_old;
  END IF;

  SELECT count(*) INTO collision_new_resources
  FROM qua503_mapping m
  JOIN resources r ON r.stable_id = m.new_id;

  IF collision_new_resources > 0 THEN
    RAISE EXCEPTION 'QUA-503: % new sid_ values already exist in resources.stable_id — refusing to overwrite.',
      collision_new_resources;
  END IF;

  SELECT count(*) INTO collision_new_things
  FROM qua503_mapping m
  JOIN things t ON t.id = m.new_id;

  IF collision_new_things > 0 THEN
    RAISE EXCEPTION 'QUA-503: % new sid_ values already exist in things.id — refusing to overwrite.',
      collision_new_things;
  END IF;

  RAISE NOTICE 'QUA-503: pre-condition checks passed; % rows to rewrite', mapping_size;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Drop EVERY FK that references things.id so the PK update can proceed.
--
--    We discover these dynamically via pg_constraint instead of hardcoding a
--    table list. The committed schema only references things.id from things
--    (parent_thing_id self-ref) and qa_page_checks (thing_id), but a hot-fix
--    or partially-reverted migration could add or remove constraints, and a
--    hardcoded list would silently miss new ones — the UPDATE in step 4 would
--    then fail with a foreign-key violation mid-transaction.
--
--    The qa503_dropped_fks temp table records what we dropped so step 5 can
--    re-add exactly the same constraints in NOT VALID mode without baking in
--    a list that drifts from the schema.
-- ---------------------------------------------------------------------------

CREATE TEMP TABLE qua503_dropped_fks (
  table_name text NOT NULL,
  constraint_name text NOT NULL,
  fk_column text NOT NULL
) ON COMMIT DROP;

DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT
      t.relname AS table_name,
      c.conname AS constraint_name,
      a.attname AS fk_column
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_attribute a
      ON a.attrelid = c.conrelid
     AND a.attnum = c.conkey[1]
    WHERE c.contype = 'f'
      AND c.confrelid = 'things'::regclass
      AND array_length(c.conkey, 1) = 1
  LOOP
    INSERT INTO qua503_dropped_fks
      (table_name, constraint_name, fk_column)
    VALUES (rec.table_name, rec.constraint_name, rec.fk_column);
    RAISE NOTICE 'QUA-503: dropping FK %.% (% -> things.id)',
      rec.table_name, rec.constraint_name, rec.fk_column;
    EXECUTE format(
      'ALTER TABLE %I DROP CONSTRAINT %I',
      rec.table_name,
      rec.constraint_name
    );
  END LOOP;
  IF NOT EXISTS (SELECT 1 FROM qua503_dropped_fks) THEN
    RAISE EXCEPTION 'QUA-503: expected at least one FK referencing things.id but found none — schema drift?';
  END IF;
END $$;

-- Assert that the dropped FK set matches what step 4's UPDATEs cover.
-- If a new FK to things.id is added to the schema, this assertion fires so the
-- script author MUST add a corresponding UPDATE in step 4 instead of silently
-- leaving stale references.
DO $$
DECLARE
  unexpected int;
BEGIN
  SELECT count(*) INTO unexpected
  FROM qua503_dropped_fks
  WHERE (table_name, fk_column) NOT IN (
    ('things',         'parent_thing_id'),
    ('qa_page_checks', 'thing_id')
  );
  IF unexpected > 0 THEN
    RAISE EXCEPTION
      'QUA-503: % unexpected FK column(s) reference things.id; add UPDATEs for them in step 4 of this script and update this assertion',
      unexpected;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 4. Apply the mapping.
-- ---------------------------------------------------------------------------

UPDATE resources r
   SET stable_id = m.new_id
  FROM qua503_mapping m
 WHERE r.stable_id = m.old_id;

UPDATE things t
   SET id = m.new_id,
       updated_at = now(),
       synced_at  = now()
  FROM qua503_mapping m
 WHERE t.source_table = 'resources'
   AND t.id = m.old_id;

UPDATE things t
   SET parent_thing_id = m.new_id
  FROM qua503_mapping m
 WHERE t.parent_thing_id = m.old_id;

UPDATE qa_page_checks q
   SET thing_id = m.new_id
  FROM qua503_mapping m
 WHERE q.thing_id = m.old_id;

-- ---------------------------------------------------------------------------
-- 5. Re-add FKs in NOT VALID mode, matching the original ON DELETE SET NULL
--    semantics. NOT VALID skips the full-table validation scan, so the
--    ACCESS EXCLUSIVE lock is held for milliseconds rather than the time it
--    takes to scan the entire \`things\` table — avoiding the QUA-302 outage
--    pattern where a long DDL deadlocked with a concurrent MV refresh.
--    The matching VALIDATE CONSTRAINT runs in step 7 (after COMMIT) under
--    SHARE UPDATE EXCLUSIVE which permits concurrent reads/writes.
--
--    These are STATIC despite step 3 being dynamic because:
--    (a) the assertion between steps 3 and 4 guarantees the dropped set
--        matches exactly these two (table, column) pairs,
--    (b) both FKs are ON DELETE SET NULL in the committed schema, and
--    (c) a dynamic EXECUTE format() loop here would be harder to review
--        for a one-shot migration than explicit DDL.
--
--    The constraint names change from PG auto-names (things_parent_thing_id_fkey,
--    qa_page_checks_thing_id_fkey) to Drizzle-convention names (*_things_id_fk).
--    This aligns with what Drizzle Kit generates from the schema declaration.
-- ---------------------------------------------------------------------------

ALTER TABLE things
  ADD CONSTRAINT things_parent_thing_id_things_id_fk
  FOREIGN KEY (parent_thing_id) REFERENCES things(id) ON DELETE SET NULL
  NOT VALID;

ALTER TABLE qa_page_checks
  ADD CONSTRAINT qa_page_checks_thing_id_things_id_fk
  FOREIGN KEY (thing_id) REFERENCES things(id) ON DELETE SET NULL
  NOT VALID;

-- ---------------------------------------------------------------------------
-- 6. Post-condition checks.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  remaining_resources int;
  remaining_things int;
BEGIN
  SELECT count(*) INTO remaining_resources
  FROM resources
  WHERE stable_id ~ '^[A-Za-z0-9]{10}$' AND stable_id !~ '^sid_';

  IF remaining_resources <> 0 THEN
    RAISE EXCEPTION 'QUA-503: % bare10 rows still in resources.stable_id after update',
      remaining_resources;
  END IF;

  SELECT count(*) INTO remaining_things
  FROM things
  WHERE source_table = 'resources'
    AND id ~ '^[A-Za-z0-9]{10}$'
    AND id !~ '^sid_';

  IF remaining_things <> 0 THEN
    RAISE EXCEPTION 'QUA-503: % bare10 rows still in things.id for source_table=resources',
      remaining_things;
  END IF;

  RAISE NOTICE 'QUA-503: post-condition checks passed';
END $$;

COMMIT;

-- ---------------------------------------------------------------------------
-- 7. Validate the FKs we re-added in NOT VALID mode. Runs OUTSIDE the
--    main transaction under SHARE UPDATE EXCLUSIVE so concurrent reads and
--    writes against \`things\` proceed normally during the validation scan.
-- ---------------------------------------------------------------------------

ALTER TABLE things VALIDATE CONSTRAINT things_parent_thing_id_things_id_fk;
ALTER TABLE qa_page_checks VALIDATE CONSTRAINT qa_page_checks_thing_id_things_id_fk;

-- ---------------------------------------------------------------------------
-- 8. Refresh the things_search materialized view so search stays in sync.
--    Outside the main transaction so the SELECT locks the refresh acquires
--    on every base table do not compound with any other DDL contention.
--    REFRESH MATERIALIZED VIEW CONCURRENTLY requires a UNIQUE INDEX on the
--    MV (created by migration 0181).
-- ---------------------------------------------------------------------------

REFRESH MATERIALIZED VIEW CONCURRENTLY things_search;
`;

  return header + valuesLines.join("\n") + "\n" + verify;
}

function pgLit(s: string): string {
  // Values are bare10 (old) or sid_ + alphanumeric (new). The conservative
  // character class rejects quotes outright, so no further escaping is needed.
  if (!/^[A-Za-z0-9_]+$/.test(s)) {
    throw new Error(`Unexpected character in literal: ${s}`);
  }
  return `'${s}'`;
}

main();
