/**
 * QUA-503: Generate the bare10 → sid_ mapping for the resources.stable_id rewrite.
 *
 * Reads `data/resources-snapshot.json` (produced by
 * `pnpm crux wiki-server snapshot-resources`), finds every row whose
 * `stable_id` matches `^[A-Za-z0-9]{10}$` (legacy bare10 format), and mints a
 * deterministic new `sid_` + 10-char id for each one using `contentHash()`.
 *
 * Deterministic-by-design so the mapping is stable across reruns and can be
 * regenerated to verify the committed file. The `"qua-503-bare10"` namespace
 * is included in the hash input to avoid collisions with any other
 * content-hashed identifiers derived from the same raw string.
 *
 * Outputs:
 *   - apps/wiki-server/scripts/qua-503-bare10-mapping.json
 *       Array of { old, new, resourceId } — used by the MDX sweep.
 *   - apps/wiki-server/scripts/qua-503-rewrite-bare10.sql
 *       Manual migration that applies the mapping to PG. Self-contained.
 *
 * Usage:
 *   pnpm tsx crux/scripts/qua-503-generate-mapping.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { contentHash } from "../../packages/factbase/src/ids.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");
const SNAPSHOT = join(REPO_ROOT, "data", "resources-snapshot.json");
const MAPPING_JSON = join(
  REPO_ROOT,
  "apps",
  "wiki-server",
  "scripts",
  "qua-503-bare10-mapping.json",
);
const SQL_OUT = join(
  REPO_ROOT,
  "apps",
  "wiki-server",
  "scripts",
  "qua-503-rewrite-bare10.sql",
);

const BARE10_RE = /^[A-Za-z0-9]{10}$/;
const SID_RE = /^sid_[A-Za-z0-9]{10}$/;

interface ResourceRow {
  id: string;
  stable_id: string | null;
}

function mintNewSid(oldBare10: string): string {
  return "sid_" + contentHash(["qua-503-bare10", oldBare10]);
}

function main(): void {
  const raw = readFileSync(SNAPSHOT, "utf-8");
  const resources = JSON.parse(raw) as ResourceRow[];

  const mapping: { old: string; new: string; resourceId: string }[] = [];
  const seenOld = new Set<string>();
  const seenNew = new Set<string>();
  const existingSidSuffixes = new Set<string>();

  for (const r of resources) {
    if (r.stable_id && SID_RE.test(r.stable_id)) {
      existingSidSuffixes.add(r.stable_id.slice(4));
    }
  }

  for (const r of resources) {
    const s = r.stable_id;
    if (!s || !BARE10_RE.test(s)) continue;
    if (seenOld.has(s)) {
      throw new Error(`Duplicate bare10 stable_id in snapshot: ${s}`);
    }
    seenOld.add(s);
    const fresh = mintNewSid(s);
    if (!SID_RE.test(fresh)) {
      throw new Error(`Generated id does not match sid_ format: ${fresh}`);
    }
    if (seenNew.has(fresh)) {
      throw new Error(
        `Deterministic collision in generated sid_ values for ${s} → ${fresh}`,
      );
    }
    if (existingSidSuffixes.has(fresh.slice(4))) {
      throw new Error(
        `Generated id ${fresh} collides with an existing sid_-prefixed resource`,
      );
    }
    seenNew.add(fresh);
    mapping.push({ old: s, new: fresh, resourceId: r.id });
  }

  mapping.sort((a, b) => (a.old < b.old ? -1 : a.old > b.old ? 1 : 0));

  writeFileSync(MAPPING_JSON, JSON.stringify(mapping, null, 2) + "\n");
  console.log(`Wrote ${mapping.length} mappings to ${MAPPING_JSON}`);

  const sql = buildSql(mapping);
  writeFileSync(SQL_OUT, sql);
  console.log(`Wrote SQL migration to ${SQL_OUT}`);
}

function buildSql(
  mapping: { old: string; new: string; resourceId: string }[],
): string {
  const header = `-- QUA-503: rewrite 5,002 bare10 \`resources.stable_id\` rows to canonical \`sid_\` format.
--
-- AUTO-GENERATED by crux/scripts/qua-503-generate-mapping.ts — do not edit by hand.
-- Run \`pnpm tsx crux/scripts/qua-503-generate-mapping.ts\` to regenerate.
--
-- Context: see Linear QUA-503 and the coordinator audit comments. The strategic
-- decision (hard cutover, no backward-compat tier) means every bare10 id in
-- PG must be rewritten to \`sid_<10>\` in the same merge as the MDX sweep in
-- \`content/docs/\`.
--
-- Usage (from a release session):
--   psql "$DATABASE_MIGRATION_URL" -v ON_ERROR_STOP=1 -f apps/wiki-server/scripts/qua-503-rewrite-bare10.sql
--
-- Pre-conditions verified by the script itself:
--   1. The count of rows matching \`^[A-Za-z0-9]{10}$\` equals the mapping size.
--   2. Every \`old\` value in the mapping still exists in \`resources.stable_id\`.
--   3. No \`new\` value already exists in \`resources.stable_id\` or \`things.id\`.
--
-- If any pre-condition fails, the transaction rolls back and nothing changes.
--
-- Post-conditions verified at the end:
--   1. \`SELECT count(*) FROM resources WHERE stable_id ~ '^[A-Za-z0-9]{10}$' AND stable_id !~ '^sid_'\` returns 0.
--   2. \`SELECT count(*) FROM things WHERE source_table = 'resources' AND id ~ '^[A-Za-z0-9]{10}$' AND id !~ '^sid_'\` returns 0.
--
-- The DDL that drops + re-adds FKs on \`things\` is required because PG does not
-- allow PK updates when referenced rows exist and the FKs are not \`ON UPDATE
-- CASCADE\`. We drop, update, re-add as \`ON DELETE SET NULL\` (matching the
-- original definition). All of this happens in one transaction so partial
-- failure rolls back cleanly.

BEGIN;

SET LOCAL lock_timeout = '60s';
SET LOCAL statement_timeout = '0';

-- ---------------------------------------------------------------------------
-- 1. Load the mapping into a temp table.
-- ---------------------------------------------------------------------------

CREATE TEMP TABLE qua503_mapping (
  old_id text PRIMARY KEY,
  new_id text NOT NULL UNIQUE,
  resource_pk text NOT NULL
) ON COMMIT DROP;

INSERT INTO qua503_mapping (old_id, new_id, resource_pk) VALUES
`;

  const valuesLines = mapping.map((m, i) => {
    const suffix = i === mapping.length - 1 ? ";" : ",";
    return `  (${pgLit(m.old)}, ${pgLit(m.new)}, ${pgLit(m.resourceId)})${suffix}`;
  });

  const verify = `
-- ---------------------------------------------------------------------------
-- 2. Pre-condition checks — abort the transaction if anything is off.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  actual_bare10 int;
  mapping_size int;
  missing_old int;
  collision_new_resources int;
  collision_new_things int;
BEGIN
  SELECT count(*) INTO actual_bare10
  FROM resources
  WHERE stable_id ~ '^[A-Za-z0-9]{10}$' AND stable_id !~ '^sid_';

  SELECT count(*) INTO mapping_size FROM qua503_mapping;

  IF actual_bare10 <> mapping_size THEN
    RAISE EXCEPTION 'QUA-503: live bare10 count (%) does not match mapping size (%). Regenerate the mapping.',
      actual_bare10, mapping_size;
  END IF;

  SELECT count(*) INTO missing_old
  FROM qua503_mapping m
  WHERE NOT EXISTS (
    SELECT 1 FROM resources r
    WHERE r.stable_id = m.old_id
  );

  IF missing_old > 0 THEN
    RAISE EXCEPTION 'QUA-503: % mapping rows have no matching resources.stable_id. Regenerate.',
      missing_old;
  END IF;

  SELECT count(*) INTO collision_new_resources
  FROM qua503_mapping m
  JOIN resources r ON r.stable_id = m.new_id;

  IF collision_new_resources > 0 THEN
    RAISE EXCEPTION 'QUA-503: % new sid_ values already exist in resources.stable_id — refusing to overwrite.',
      collision_new_resources;
  END IF;

  SELECT count(*) INTO collision_new_things
  FROM qua503_mapping m
  JOIN things t ON t.id = m.new_id;

  IF collision_new_things > 0 THEN
    RAISE EXCEPTION 'QUA-503: % new sid_ values already exist in things.id — refusing to overwrite.',
      collision_new_things;
  END IF;

  RAISE NOTICE 'QUA-503: pre-condition checks passed; % rows to rewrite', mapping_size;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Drop FKs that reference things.id so the PK update can proceed.
--    Drizzle does not name these constraints, so we look them up by pattern.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT c.conname AS fk_name, t.relname AS table_name
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    WHERE c.contype = 'f'
      AND c.confrelid = 'things'::regclass
      AND t.relname IN ('things', 'qa_page_checks')
  LOOP
    RAISE NOTICE 'QUA-503: dropping FK %.% -> things.id', rec.table_name, rec.fk_name;
    EXECUTE format(
      'ALTER TABLE %I DROP CONSTRAINT %I',
      rec.table_name,
      rec.fk_name
    );
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 4. Apply the mapping.
-- ---------------------------------------------------------------------------

UPDATE resources r
   SET stable_id = m.new_id
  FROM qua503_mapping m
 WHERE r.stable_id = m.old_id;

UPDATE things t
   SET id = m.new_id,
       updated_at = now(),
       synced_at  = now()
  FROM qua503_mapping m
 WHERE t.source_table = 'resources'
   AND t.id = m.old_id;

UPDATE things t
   SET parent_thing_id = m.new_id
  FROM qua503_mapping m
 WHERE t.parent_thing_id = m.old_id;

UPDATE qa_page_checks q
   SET thing_id = m.new_id
  FROM qua503_mapping m
 WHERE q.thing_id = m.old_id;

-- ---------------------------------------------------------------------------
-- 5. Re-add FKs. Matches the original \`ON DELETE SET NULL\` semantics.
-- ---------------------------------------------------------------------------

ALTER TABLE things
  ADD CONSTRAINT things_parent_thing_id_things_id_fk
  FOREIGN KEY (parent_thing_id) REFERENCES things(id) ON DELETE SET NULL;

ALTER TABLE qa_page_checks
  ADD CONSTRAINT qa_page_checks_thing_id_things_id_fk
  FOREIGN KEY (thing_id) REFERENCES things(id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- 6. Post-condition checks.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  remaining_resources int;
  remaining_things int;
BEGIN
  SELECT count(*) INTO remaining_resources
  FROM resources
  WHERE stable_id ~ '^[A-Za-z0-9]{10}$' AND stable_id !~ '^sid_';

  IF remaining_resources <> 0 THEN
    RAISE EXCEPTION 'QUA-503: % bare10 rows still in resources.stable_id after update',
      remaining_resources;
  END IF;

  SELECT count(*) INTO remaining_things
  FROM things
  WHERE source_table = 'resources'
    AND id ~ '^[A-Za-z0-9]{10}$'
    AND id !~ '^sid_';

  IF remaining_things <> 0 THEN
    RAISE EXCEPTION 'QUA-503: % bare10 rows still in things.id for source_table=resources',
      remaining_things;
  END IF;

  RAISE NOTICE 'QUA-503: post-condition checks passed';
END $$;

-- ---------------------------------------------------------------------------
-- 7. Refresh the things_search materialized view so search stays in sync.
-- ---------------------------------------------------------------------------

REFRESH MATERIALIZED VIEW CONCURRENTLY things_search;

COMMIT;
`;

  return header + valuesLines.join("\n") + "\n" + verify;
}

function pgLit(s: string): string {
  // Values are bare10 (old), sid_ + alphanumeric (new), or resource ids.
  // Resource ids are normally hex16 but can be slugged test probes like
  // "test-fresh-probe". Allow a conservative character class and single-quote
  // escape for safety.
  if (!/^[A-Za-z0-9_-]+$/.test(s)) {
    throw new Error(`Unexpected character in literal: ${s}`);
  }
  return `'${s.replace(/'/g, "''")}'`;
}

main();
