/**
 * Merge vitest coverage-summary.json files from multiple workspaces
 * into a single markdown report suitable for a PR comment.
 *
 * Usage: npx tsx crux/ci/merge-coverage.ts [--output=/path/to/output.md]
 *
 * Reads coverage/coverage-summary.json from each workspace directory.
 * Outputs a markdown table with per-workspace and total coverage.
 */

import fs from "fs";
import path from "path";

interface CoverageSummaryEntry {
  total: number;
  covered: number;
  skipped: number;
  pct: number;
}

interface CoverageSummary {
  total: {
    lines: CoverageSummaryEntry;
    statements: CoverageSummaryEntry;
    functions: CoverageSummaryEntry;
    branches: CoverageSummaryEntry;
  };
}

const WORKSPACES = [
  { name: "wiki-server", dir: "apps/wiki-server" },
  { name: "web", dir: "apps/web" },
  { name: "discord-bot", dir: "apps/discord-bot" },
  { name: "crux", dir: "crux" },
];

function readCoverageSummary(
  rootDir: string,
  workspaceDir: string
): CoverageSummary | null {
  const summaryPath = path.join(
    rootDir,
    workspaceDir,
    "coverage",
    "coverage-summary.json"
  );
  if (!fs.existsSync(summaryPath)) {
    return null;
  }
  try {
    return JSON.parse(fs.readFileSync(summaryPath, "utf-8"));
  } catch (e) {
    console.warn(
      `Failed to read coverage summary at ${summaryPath}: ${e instanceof Error ? e.message : String(e)}`
    );
    return null;
  }
}

function formatPct(pct: number): string {
  if (pct < 0) return "N/A";
  return `${pct.toFixed(1)}%`;
}

function main() {
  const rootDir = path.resolve(import.meta.dirname, "../..");

  const outputArg = process.argv.find((a) => a.startsWith("--output="));
  const outputPath = outputArg
    ? outputArg.replace("--output=", "")
    : undefined;

  const rows: {
    name: string;
    lines: number;
    branches: number;
    functions: number;
    statements: number;
  }[] = [];

  let totalLines = { total: 0, covered: 0 };
  let totalBranches = { total: 0, covered: 0 };
  let totalFunctions = { total: 0, covered: 0 };
  let totalStatements = { total: 0, covered: 0 };

  for (const ws of WORKSPACES) {
    const summary = readCoverageSummary(rootDir, ws.dir);
    if (!summary) {
      rows.push({
        name: ws.name,
        lines: -1,
        branches: -1,
        functions: -1,
        statements: -1,
      });
      continue;
    }

    const t = summary.total;
    rows.push({
      name: ws.name,
      lines: t.lines.pct,
      branches: t.branches.pct,
      functions: t.functions.pct,
      statements: t.statements.pct,
    });

    totalLines.total += t.lines.total;
    totalLines.covered += t.lines.covered;
    totalBranches.total += t.branches.total;
    totalBranches.covered += t.branches.covered;
    totalFunctions.total += t.functions.total;
    totalFunctions.covered += t.functions.covered;
    totalStatements.total += t.statements.total;
    totalStatements.covered += t.statements.covered;
  }

  const overallLines =
    totalLines.total > 0
      ? (totalLines.covered / totalLines.total) * 100
      : -1;
  const overallBranches =
    totalBranches.total > 0
      ? (totalBranches.covered / totalBranches.total) * 100
      : -1;
  const overallFunctions =
    totalFunctions.total > 0
      ? (totalFunctions.covered / totalFunctions.total) * 100
      : -1;
  const overallStatements =
    totalStatements.total > 0
      ? (totalStatements.covered / totalStatements.total) * 100
      : -1;

  const lines: string[] = [];
  lines.push("## Test Coverage Report");
  lines.push("");
  lines.push(
    "| Workspace | Lines | Branches | Functions | Statements |"
  );
  lines.push(
    "|-----------|-------|----------|-----------|------------|"
  );

  for (const row of rows) {
    lines.push(
      `| ${row.name} | ${formatPct(row.lines)} | ${formatPct(row.branches)} | ${formatPct(row.functions)} | ${formatPct(row.statements)} |`
    );
  }

  lines.push(
    `| **Total** | **${formatPct(overallLines)}** | **${formatPct(overallBranches)}** | **${formatPct(overallFunctions)}** | **${formatPct(overallStatements)}** |`
  );
  lines.push("");
  lines.push(
    "_Coverage is advisory only — no thresholds enforced. Generated by `vitest --coverage`._"
  );

  const markdown = lines.join("\n");

  if (outputPath) {
    fs.writeFileSync(outputPath, markdown);
    console.log(`Coverage report written to ${outputPath}`);
  } else {
    console.log(markdown);
  }
}

main();
